### PR TITLE
Latex

### PR DESCRIPTION
**Pull request by jdfreder**

### CODE REVIEW

**Comment by jdfreder** [comment]
maths

**Comment by betatim** [comment]
screen shot 2016-05-12 at 23 28 08

**Comment by jdfreder** [comment]
Okay, this is good to go I think...  I updated to process outputs too.

**Comment by rgbkrk** [comment]
Looking quite good.

We'll probably want to change up our LaTeX transform too. If KaTeX errors, the whole show is brought down.

screen shot 2016-05-13 at 12 15 19 pm

**Pull request merged**
