### PR TITLE
The subtree ash way

### PR DESCRIPTION
**Pull request by rgbkrk**
Again? Seriously Kyle? Must you really keep doing this?

### CODE REVIEW

**Comment by rgbkrk** [comment]
Totes not mergable without a rebase.

**Comment by rgbkrk** [comment]
used: 

```
NAME=enchannel-zmq-backend git subtree add --prefix=packages-${NAME} git@github.com:nteract/${NAME}.git master
```

**Comment by smashwilson** [comment]
🤔 Weeeeird

**Comment by rgbkrk** [comment]
Would have been sweet, there were many conflicts for merging though.

**Comment by smashwilson** [comment]
What kind of conflicts were there? The merge should have constrained changes to the `packages-enchannel-zmq-backend/` subdirectory which doesn't exist on master.

**Comment by rgbkrk** [comment]
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

Mostly files in the base, like the `README.md`, `index.js`, etc.

It wants me to rectify the changes between 2016 READMEs amongst both projects.

I can do a squash merge from the GitHub UI here though. 
¯\\\_(ツ)\_/¯

**Comment by rgbkrk** [comment]
Going with one of #1810 or #1807, closing this.

**Pull request closed without merging**
