### PR TITLE
Add new configuration prop to register custom commands

### PR DESCRIPTION
**Pull request by resaldiv**
### Checklist

- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [x] I have updated the changelogs/current_changelog.md file with some information about the change that I am making the appropriate file.
- [X] I have validated or unit-tested the changes that I have made.
- [X] I have run through the TEST_PLAN.md to ensure that my change does not break anything else.

### Context
In a monaco editor instance, a command can be used upon the acceptance of a [completion item](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html). This is helpful to trigger specific actions and log events, so it would be nice to add support to register custom commands in the monaco editor.

### Solution
A way to achieve this, is by adding a command handler to the monaco configuration props (similar to the shortcuts handler). In this way, a user can call the [addCommand](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#addcommand) method and add some logic on what type of action will be triggered.

```
<MonacoEditor
    ...
    commandHandler={myCommandHandler}
/>

myCommandHandler(editor) {
    // Add some logic on what type of action will be triggered
    const commandHandler = () => {
        alert('My command is executing');
    };

    const myCommand = editor.addCommand(0, commandHandler);
    
    // The alert will be triggered upon the acceptance of this completion item
    const myCompletionItem = {
        ...
        command: myCommand
    }
}
```

This PR adds an optional prop to the `IMonacoConfiguration`, so that a user can register and handle custom commands in the editor.

### Side notes
While running the `TEST_PLAN.md` I opened the **Explore Your World with GeoJSON** example and the maps look like this (not sure if it's a bug or not):
image

### CODE REVIEW

**Comment by captainsafia** [comment]
> A way to achieve this, is by adding a command handler to the monaco configuration props (similar to the shortcuts handler). In this way, a user can call the addCommand method and add some logic on what type of action will be triggered.

Can you share a code sample of how this API would be used?

**Comment by resaldiv** [comment]
@captainsafia thanks for taking a look into this! I updated the description to include an example.

**Review by captainsafia — APPROVED** [review]
Looks fine but cc @vivek1729 since has more insight on the Monaco stuff

**Review by vivek1729 — APPROVED** [review]

**Comment by resaldiv** [comment]
Thank you @captainsafia and @vivek1729 for the review. I did a minor change to include this functionality when the component gets updated.

**Pull request merged**
