### PR TITLE
perf(load): bundle and tree shake assets with webpack

### LINKED ISSUE #1014: Bundle a subset of assets through webpack
For everything but native modules, we could try using webpack to improve performance of loading (while also getting rid of the `cross-env` setup we use to set NODE_ENV to production).

**Resources**
- [Backend Apps with Webpack](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #1014 by slowly introducing webpack.

To try it out, fetch this branch and then: `npm install`. It does the build automatically.

### CODE REVIEW

**Comment by rgbkrk** [comment]
To run, fetch this branch and then:

```
npm install
./node_modules/.bin/webpack
```

**Comment by rgbkrk** [comment]
P.S. If you thought I did this all in one neat commit, you'd be mistaken. I fought this for a good while. :wink:

**Comment by rgbkrk** [comment]
Current status:

```
$ ./node_modules/.bin/webpack
Hash: 5b7f6997245969189638
Version: webpack 1.13.2
Time: 14197ms
                    Asset     Size  Chunks             Chunk Names
    webpacked-notebook.js  8.71 MB       0  [emitted]  main
webpacked-notebook.js.map  10.5 MB       0  [emitted]  main
[1223] ./src/notebook/components ^\.\/.*$ 1.64 kB {0} [optional] [built]
    + 1228 hidden modules

WARNING in ./src/notebook/components/notebook.js
Critical dependencies:
71:6-60 the request of a dependency is an expression
 @ ./src/notebook/components/notebook.js 71:6-60

WARNING in ./app/~/plotly.js/dist/plotly.js
Critical dependencies:
7:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./app/~/plotly.js/dist/plotly.js 7:479-486
```

**Comment by rgbkrk** [comment]
It's working!

Since we're doing global MathJax anyways, it's tempting to put MathJax on the page globally as well. If/when I come back to this PR I'll probably do that.

**Comment by rgbkrk** [comment]
:tada: Webpack is working! :tada:

Good news for the future - we should be able to use this to reduce the overall size of our app:

```
                    Asset     Size  Chunks             Chunk Names
    webpacked-notebook.js  8.71 MB       0  [emitted]  main
webpacked-notebook.js.map  10.5 MB       0  [emitted]  main
```

Not everything can we take out from our build though:

```
nteract/nteract/app/node_modules$ du -sh * | gsort -h | tail -n 25
1.4M    github
1.5M    uglify-js
1.8M    d3
1.8M    node-ninja
2.2M    shelf-pack
2.2M    whoots-js
2.4M    node-gyp
2.5M    JSV
2.6M    lodash-es
2.7M    codemirror <---- have to keep for styles
2.8M    moment
2.9M    gl-plot3d
3.0M    mathjax-electron <----- we're stuck bringing in parts of this
3.0M    react
3.1M    es5-ext
4.0M    sane-topojson
4.8M    lodash
5.1M    fbjs
5.9M    mapbox-gl
6.6M    core-js
7.2M    rxjs
 14M    leaflet
 16M    nteract-assets   <---- absolute must, includes our fonts
 40M    plotly.js
 41M    zmq-prebuilt <---- can't get around this really, except for trimming out Windows libs
```

**Comment by lgeiger** [comment]
Fixes #979

**Comment by rgbkrk** [comment]
I wonder if I should extract the Mathjax bits to a new PR. It's a nice cleanup that doesn't require webpack.

**Comment by lgeiger** [comment]
We should get the mathjax bits merged before the next release. It depends on how much time is needed for webpack.

**Comment by rgbkrk** [comment]
The webpack stuff here is good to go, it mostly needs someone else to check it out and help decide of we want to go this route.

**Pull request merged**
