### PR TITLE
ensure sockets are connected before usage

### LINKED ISSUE #2156: Kernel sometimes isn't really starting
With the desktop app, on `master`, it seems that sometimes the app acts like its connected to the kernel even though it isn't responding to messages. It _seems_ like it's a timing issue of the kernel not quite being ready. Ever since we optimized things in #2137 I've noticed this behavior. That leads me to believe that there's a readiness issue that before was a non-issue due to timing.

One other thing I noticed while doing #2137 is that it seems like registering callbacks (other than `message`) on the jmp sockets is not giving us access to the zeromq events.

/cc @captainsafia @lgeiger

### PR DESCRIPTION
**Pull request by rgbkrk**
closes #2156 (thankfully)

I've made the interface to `enchannel-zmq-backend`'s channel creation to be a promise that resolves when all the sockets have been properly connected. This does use the monitoring that was suggested by @lgeiger.

With this, I think we've finished off the last release blocker (that I can recall).

### CODE REVIEW

**Comment by rgbkrk** [comment]
Working on fixing up the tests and adding new ones.

**Comment by rgbkrk** [comment]
This will soon be good to go and we'll have a much more stable app as a result. 🎉

**Comment by rgbkrk** [comment]
Readyyyyy

**Comment by rgbkrk** [comment]
Luck of the draw, I've still gotten the app to boot with a kernel not really quite attached / ready.

I'll debug now.

**Comment by rgbkrk** [comment]
Ok, things are more stable now. If I go after anything similar again, I think I'll bring the message encoding and decoding in from jmp, handling it inline with enchannel-zmq while having more control / insight of what's going on with zeromq.

**Comment by rgbkrk** [comment]
@captainsafia check this out when you get a chance.

**Comment by rgbkrk** [comment]
Now I fully understand how I fixed then broke this. The monitoring did patch around the sockets to make sure they're ready. Where I made a fatal mistake was when I did a refactor I connected to zeromq twice with the same identity (two socket connections). This completely broke all the `ROUTER` sockets (`shell` showing the most glaring of symptoms). After noticing this and cleaning it up, the sockets connect properly and stay connected.

All that's to say -- 🎉  this is now working and stable and I learned a bit about how to break zeromq connections.

**Comment by Madhu94** [comment]
@rgbkrk @captainsafia Thank  you so much! My build works again!

**Comment by rgbkrk** [comment]
Sweet! We'll get a new release out soon.

**Pull request merged**
