### PR TITLE
Fix #4547: Allow naming new notebooks from CLI

### LINKED ISSUE #4547: Nonexisting file in CLI arguments ignored
**Application or Package Used**
nteract desktop 0.14.5

**Describe the bug**
When specifying a nonexistent file on the command line nteract should create a new notebook with that name.  Currently it ignores the argument and creates a new file named `Untitled.ipynb`.

**To Reproduce**
In an empty directory run `nteract a.ipynb`

nteract starts with the filename `Untitled.ipynb` in the titlebar.  Pressing ctrl+s creates the file `Untitled.ipynb` in the current directory.

**Expected behavior**
A new notebook is created with the name `a.ipynb` and not `Untitled.ipynb`.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version 0.14.5

**Additional context**
I searched with various terms to see if there's a duplicate issue anywhere and found nothing, I apologize if this is a repeat or is already fixed.

### PR DESCRIPTION
**Pull request by rendaw**
If a filename is specified on the command line that doesn't exist a
new notebook will be created with that name instead of Untitled.ipynb.

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rendaw** [comment]
For now only CLI allows creating new named notebooks, but I think it would be simple enough to extend to other interfaces if there's one that would be applicable.

**Review by captainsafia — COMMENTED** [review]
Can you update the documentation in USER_GUIDE.md as well? Thanks!

**Comment by rendaw** [comment]
Thanks, done!

**Review by captainsafia — APPROVED** [review]
Thanks!

**Pull request merged**
