### PR TITLE
Tracking the Data Explorer TypeScript Migration

### PR DESCRIPTION
**Pull request by rgbkrk**
In order to migrate Data Explorer over to TypeScript we're centralizing on a branch on the nteract remote. To get changes into this branch, submit a pull request that targets `nteractors/jan/dx-ts-migration`. This branch will frequently get rebased against master (when necessary) to make getting this finished as easy as possible.

Should likely be done (in new PRs):

* [ ] Convert the index spec test file to typescript
* [x] Convert from `styled-jsx` to `styled-components` #3941

### CODE REVIEW

**Comment by rgbkrk** [comment]
@jdetle @BenRussert @emeeks Any last reviews / requests for this?

**Comment by BenRussert** [comment]
With tests passing I think we should merge and refine later. I definitely learned some things working on this.

Thanks for all the work on this everyone! I've not worked on a PR with 5 different contributors before! (There is no "I" in nteract)

**Comment by rgbkrk** [comment]
> There is no "I" in nteract

😂🤣

**Comment by rgbkrk** [comment]
And so it is.

**Pull request merged**
