### PR TITLE
[WIP] Add undo and redo for Notebook state

### PR DESCRIPTION
**Pull request by captainsafia**
Here goes.

### CODE REVIEW

**Comment by captainsafia** [comment]
Will be making updates to `commutable` in parallel.

**Comment by jdfreder** [comment]
Okay, this post may not be comprehensive, but it's all I've thought about now.
I think you'll want to tackle this in steps,

## First

You'll want to make sure that the document state is decoupled from the rest of the application state.  For example, in the following app state:

``` js
{
  cellPagers: Map,
  cellStatuses: Map,
  channels: Object,
  connectionFile: "/run/user/1000/jupyter/kernel-aaf19a34-c0da-4968-bc2f-d2f8c8ba904b.json",
  executionState: "idle",
  filename: "/home/jon/github.com/nteract/nteract/intro.ipynb",
  focusedCell: "260f6a26-9623-46b7-a83f-ce5f1830d21a",
  github: module.exports,
  notificationSystem: Constructor,
  spawn: ChildProcess,
  notebook: {
    cellMap: {
      "260f6a26-9623-46b7-a83f-ce5f1830d21a": {
        cell_type: "markdown",
        metadata: {},
        source: "a"
      },
      "2bc3af2b-43e7-4284-94a4-1bf135b15110": {
        cell_type: "code",
        execution_count: 2,
        metadata: {
          collapsed: false
        },
        outputs: [ ],
        source: "b"
      },
    },
    cellOrder: [
      "260f6a26-9623-46b7-a83f-ce5f1830d21a",
      "2bc3af2b-43e7-4284-94a4-1bf135b15110",
    ],
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        mimetype: "text/x-python",
        nbconvert_exporter: "python",
        name: "python",
        pygments_lexer: "ipython2",
        version: "2.7.10",
        file_extension: ".py",
        codemirror_mode: {
          version: 2,
          name: "ipython"
        }
      }
    },
    nbformat: 4,
    nbformat_minor: 0
  },
```

`cellPagers`, `cellStatuses`, `focusedCell`, `notebook` probably should be
recorded in the undo/redo stack.  It may make sense to sort the state (this is
something we'll have to do when we get to implementing RTC anyways):

``` js
{
  appState: { ... },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

## Second

You'll want two stacks in the application state, undo and redo.  

``` js
{
  appState: {
    undo: [],
    redo: [],
    ...
  },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

and two corresponding reductions, SET_FORWARD_CHECKPOINT and 
SET_BACKWARD_CHECKPOINT.  SET_BACKWARD_CHECKPOINT takes the current `userState`
and `documentState` and stores it in the `appState` under an `undo` stack.  For 
example, this would result in:

``` js
{
  appState: {
    undo: [
      {
        userState,
        documentState,
      },
    ],
    redo: [],
    ...
  },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

You'll want to have sane limits on the number of recorded undo and redo actions.

SET_FORWARD_CHECKPOINT does the same thing but into the `redo` stack.

Lastly, the corresponding action for the SET_BACKWARD_CHECKPOINT reducer should
have a flag that optionally clears the redo stack (via a CLEAR_REDO reducer).

## Third

Create UNDO and REDO actions & reductions.

UNDO action will do the following:
- abort if `undo` stack length = 0
- SET_FORWARD_CHECKPOINT
- UNDO reduction: pop state from `undo` stack over `userState` and `documentState`

REDO action will do the following:
- abort if `redo` stack length = 0
- SET_BACKWARD_CHECKPOINT (clear redo = false)
- REDO reduction: pop state from `redo` stack over `userState` and `documentState`

## Forth

Call SET_BACKWARD_CHECKPOINT (clear redo = true) at the beginning of relevant, 
top-level user actions.

## Fifth

Implement menu items that point to the UNDO REDO reduction actions.

**Comment by rgbkrk** [comment]
Super outline @jdfreder

**Comment by captainsafia** [comment]
This is stale. Opening another.

**Comment by rgbkrk** [comment]
Worth bringing Jon's outline over, probably in the main PR text (or a new issue with a checklist).

**Comment by captainsafia** [comment]
I migrated Jon's comment and added checklist to the new PR: #510.

**Pull request closed without merging**
