### PR TITLE
Test GitHub Publish

### PR DESCRIPTION
**Pull request by jdetle**
Courtesy of some late night pair programming

### CODE REVIEW

**Comment by rgbkrk** [comment]
Woohoo!

**Comment by jdetle** [comment]
I should be paying @captainsafia for the tutelage hours.

**Comment by captainsafia** [comment]
> I should be paying @captainsafia for the tutelage hours.

I'll email you an invoice tomorrow morning. 😜

**Comment by rgbkrk** [comment]
:shipit: 

Well done y'all.

**Pull request merged**
