### PR TITLE
chore(pkg): upgrade all the deps in packages

### PR DESCRIPTION
**Pull request by rgbkrk**
Finish off all the upgrades missed in #1700

### CODE REVIEW

**Comment by rgbkrk** [comment]
Seems like electron is just generally failing...  
¯\\\_(ツ)\_/¯

```
$ ./node_modules/.bin/electron
/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:570:32)
```

**Comment by rgbkrk** [comment]
I ran `npm install electron` locally, things are ok now.

**Comment by rgbkrk** [comment]
```
packages/display-area/lib/output.js.flow:53
 53:           return <Ansi className={classPrefix + name}>{text}</Ansi>;
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 53:           return <Ansi className={classPrefix + name}>{text}</Ansi>;
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Ansi`

packages/display-area/lib/output.js.flow:62
               v----
 62:           <Ansi
 63:             className={classPrefix + "traceback"}
 64:           >{`${output.get("ename")}: ${output.get("evalue")}`}</Ansi>
               ^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
               v----
 62:           <Ansi
 63:             className={classPrefix + "traceback"}
 64:           >{`${output.get("ename")}: ${output.get("evalue")}`}</Ansi>
               ^ props of React element `Ansi`

packages/display-area/lib/output.js.flow:68
 68:         <Ansi className={classPrefix + "traceback"}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 68:         <Ansi className={classPrefix + "traceback"}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Ansi`

packages/display-area/src/output.js:53
 53:           return <Ansi className={classPrefix + name}>{text}</Ansi>;
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 53:           return <Ansi className={classPrefix + name}>{text}</Ansi>;
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Ansi`

packages/display-area/src/output.js:62
               v----
 62:           <Ansi
 63:             className={classPrefix + "traceback"}
 64:           >{`${output.get("ename")}: ${output.get("evalue")}`}</Ansi>
               ^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
               v----
 62:           <Ansi
 63:             className={classPrefix + "traceback"}
 64:           >{`${output.get("ename")}: ${output.get("evalue")}`}</Ansi>
               ^ props of React element `Ansi`

packages/display-area/src/output.js:68
 68:         <Ansi className={classPrefix + "traceback"}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 68:         <Ansi className={classPrefix + "traceback"}>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Ansi`

packages/transforms/lib/text.js.flow:18
 18:     return <Ansi linkify>{this.props.data}</Ansi>;
                ^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 18:     return <Ansi linkify>{this.props.data}</Ansi>;
                ^^^^^^^^^^^^^^ props of React element `Ansi`

packages/transforms/src/text.js:18
 18:     return <Ansi linkify>{this.props.data}</Ansi>;
                ^^^^^^^^^^^^^^ React element `Ansi`
 93: function Ansi(props: {children: string, className?: string}) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: node_modules/ansi-to-react/lib/index.js.flow:93
 18:     return <Ansi linkify>{this.props.data}</Ansi>;
                ^^^^^^^^^^^^^^ props of React element `Ansi`


Found 17 errors

```

**Comment by rgbkrk** [comment]
All that remains:

```
> nteract@0.1.0 flow /Users/kylek/code/src/github.com/nteract/nteract
> flow

Launching Flow server for /Users/kylek/code/src/github.com/nteract/nteract
Spawned flow server (pid=72569)
Logs will go to /private/tmp/flow/zSUserszSkylekzScodezSsrczSgithub.comzSnteractzSnteract.log
node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/interactive-supports-focus.js:46
 46:   create: (context: ESLintContext) => ({
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/media-has-caption.js:43
 43:   create: (context: ESLintContext) => ({
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-interactive-element-to-noninteractive-role.js:47
 47:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-interactive-element-to-noninteractive-role.js:51
 51:         attribute: ESLintJSXAttribute,
                        ^^^^^^^^^^^^^^^^^^ identifier `ESLintJSXAttribute`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-interactions.js:46
 46:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-to-interactive-role.js:47
 47:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-to-interactive-role.js:51
 51:         attribute: ESLintJSXAttribute,
                        ^^^^^^^^^^^^^^^^^^ identifier `ESLintJSXAttribute`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-tabindex.js:45
 45:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/react-scripts/node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-tabindex.js:49
 49:           node: JSXOpeningElement,
                     ^^^^^^^^^^^^^^^^^ identifier `JSXOpeningElement`. Could not resolve name


Found 9 errors
```

**Comment by rgbkrk** [comment]
With _all_ this, all deprecation warnings are now gone within the dev console.

**Comment by lgeiger** [comment]
Thanks for fixing this mess. That's awesome!

**Pull request merged**
