### PR TITLE
docs(notebooks): javascript notebook on JSON.parse

### PR DESCRIPTION
**Pull request by rgbkrk**
This is a notebook that covers the use of `JSON.parse`, a little bit on how we load notebooks, and an attempt to optimize loading with `JSON.parse` revivers.

### CODE REVIEW

**Review by lgeiger — APPROVED** [review]
Awesome!

Should we add a menu item for it?

**Comment by rgbkrk** [comment]
If you think it's a good notebook for general demonstration. We should probably include a bit fat JS logo at the top then.

**Comment by rgbkrk** [comment]
Updated with a JS logo, I'll add it into the menu too.

**Comment by peggyrayzis** [comment]
Really cool seeing a notebook used as documentation! 👍 It's super clear and informative.

**Comment by rgbkrk** [comment]
Menu in now, just have to wait on Travis. I'm at least glad I put this notebook together even though it seems I probably won't use a custom reviver for the loading of the notebook.

**Pull request merged**
