### PR TITLE
Bump Dockerfile base to node8

### PR DESCRIPTION
**Pull request by yuvipanda**
- [ ] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by betatim** [comment]
LGTM, just to double check you tried 8.9 locally? I seem to still be on 8.1 which works nicely.

**Comment by yuvipanda** [comment]
I picked it out of https://hub.docker.com/_/node/

**Comment by betatim** [comment]
Should we close this in favour of #2124 ?

**Comment by rgbkrk** [comment]
I think we'll just merge both. Since this one is passing already, I'll go ahead and bring it in.

**Comment by rgbkrk** [comment]
As is customary after your first PRs, welcome to the nteract party @yuvipanda! 🎉

**Comment by betatim** [comment]
🍰 !

**Pull request merged**
