### PR TITLE
Test reports are not being published to Azure Pipelines

### PR DESCRIPTION
**Pull request by vagisha-nidhi**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

This PR is related to the issue #3675 
The PR helps to publish test results for reporting in Azure Pipelines.

Azure Pipelines provides excellent reporting capabilities that can be leveraged by this PR.
An example report is shown in the image below.
image

### CODE REVIEW

**Review by rgbkrk — APPROVED** [review]
I love this, thank you!

**Comment by rgbkrk** [comment]
Welcome to the nteract party! 🎉

**Comment by rgbkrk** [comment]
Feel free to keep sending over more azure pipelines PRs and let us know if you'd like to learn more within the overall code base to see what else might be of interest.

**Comment by vagisha-nidhi** [comment]
Sure. We'll be happy to contribute wherever possible!

**Pull request merged**
