### PR TITLE
[WIP] chore: bump rxjs and redux-observable

### PR DESCRIPTION
**Pull request by alexandercbooth**
Closes #2793 and #3019.

So far, 
- completed the new imports for rxjs (though entirely possible with this many files that I missed some 😨 )
- started changing the epic pattern to accept state as the `redux-observable` bump requires. Started with core epics since I was using Jext as the test app. Kernel not currently connecting up, though 😞
- started changing the store configuration (I think just Jext so far) for `redux-observable`

## TODO

* [ ] Update redux-observable flow definition
* [ ] Write flow types for creation operators we use
  * [ ] `bindNodeCallback`
  * [ ] `fromEvent`
  * [ ] `merge`
* [ ] Remove all usage of `pluck` due to lack of type safety
* [ ] Reduce the longer `pipe()` chains OR make more definitions of `pipe` that can handle more arguments
* [ ] Send PRs to flow type for each flow definition update

### CODE REVIEW

**Comment by alexandercbooth** [comment]
Not passing circle at the moment because of flow, which doesn't like the simplified rxjs imports 🤔

**Comment by rgbkrk** [comment]
Alright, I'm going to give this a spin and do some rebasing.

**Comment by rgbkrk** [comment]
Oh hey now that we have real type safety on Rx, it found real bugs:

```
Cannot call catchError with function bound to selector because FetchKernelspecsFailed [1] is incompatible with
rxjs$Observable [2] in the return value.

     packages/core/src/epics/kernelspecs.js
      53│             kernelspecs
      54│           });
      55│         }),
      56│         catchError(error => {
      57│           return actions.fetchKernelspecsFailed({ kernelspecsRef, error });
      58│         })
      59│       );
      60│     })
      61│   );

     flow-typed/npm/rxjs_v6.x.x.js
 [2] 887│       selector: (err: any, caught: rxjs$Observable<T>) => rxjs$Observable<U>

     packages/core/src/actions.js
 [1] 108│ }): actionTypes.FetchKernelspecsFailed => ({
```

**Comment by rgbkrk** [comment]
Note: I'm copying definitions of creation operators like `forkJoin` from later on in the file to add them to the top level namespace. There's got to be a better way to share those across the flow definitions. :-/ Just going to make this work for now. 😬

**Comment by alexandercbooth** [comment]
Sheesh, I need to set aside some time (and courage, _lots_ of courage 😅)  to come back to this soon.

**Comment by rgbkrk** [comment]
This sucker is going to require some major rebasing.

**Comment by alexandercbooth** [comment]
Just rebased to make this easier to continue with 😅

**Comment by rgbkrk** [comment]
Nice.

**Comment by lgeiger** [comment]
Closing in favor of #3399.

**Pull request closed without merging**
