### PR TITLE
docs(releases): provide an "example" notebook that looks at our download counts

### PR DESCRIPTION
**Pull request by rgbkrk**
Dog fooding our app by taking a look at download counts.

Some improvements I'd love to see (which I can post an issue for, def new-contributor-friendly):
- Rely completely on pandas for fetching the json and stripping out what we need (potentially)
- Plot with x-axis being version, y-axis being count, and a line for each download type

### CODE REVIEW

**Comment by rgbkrk** [comment]
screen shot 2016-10-05 at 12 29 00 pm

**Comment by captainsafia** [comment]
Oh wow, what a coincidence! I was just looking into making a command line tool for this so we can get stats to use in grant reports. This is better though!

**Comment by rgbkrk** [comment]
Awesome! I won't update this branch anymore then, I'll leave you to data-science-fu it after.

My ideal for getting the data over time -- we're going to have to run a job that continuously polls the releases API and captures this for us.

**Pull request merged**
