### PR TITLE
App state should use Immutable.Record

### PR DESCRIPTION
**Pull request by captainsafia**
I heard you liked `Record`s.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Yusssss I dooooo

**Comment by rgbkrk** [comment]
This only keeps the `app` state as a Record before the first reduction. It's a normal object after (need to change all the reducers too).

**Comment by rgbkrk** [comment]
(I'll tackle this right now, amusingly I have this in a branch too).

**Comment by captainsafia** [comment]
> This only keeps the app state as a Record before the first reduction. It's a normal object after (need to change all the reducers too).

OHHHH!

> (I'll tackle this right now, amusingly I have this in a branch too).

Sweet! I'll merge when you're ready.

**Pull request merged**
