### PR TITLE
[WIP][DO NOT MERGE] Typescript upgrade

### PR DESCRIPTION
**Pull request by rgbkrk**
This starts off an upgrade of our Typescript setup.

### CODE REVIEW

**Comment by rgbkrk** [comment]
```
packages/rx-jupyter/src/kernels.ts:150:33 - error TS2339: Property 'closeObserver' does not exist on type 'ServerConfig'.

150     closeObserver: serverConfig.closeObserver
                                    ~~~~~~~~~~~~~

[4:35:34 PM] Building project '/Users/kylek/code/src/github.com/nteract/nteract/packages/selectors/tsconfig.json'...

packages/selectors/src/core/hosts.ts:26:5 - error TS2322: Type '{ endpoint: string; crossDomain: true | undefined; token: string | undefined; ajaxOptions: Partial<AjaxRequest> | undefined; wsProtocol: string | string[] | undefined; closeObserver: any; }' is not assignable to type 'ServerConfig'.
  Object literal may only specify known properties, and 'closeObserver' does not exist in type 'ServerConfig'.

26     closeObserver: host.closeObserver,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/selectors/src/core/hosts.ts:26:25 - error TS2339: Property 'closeObserver' does not exist on type 'JupyterHostRecord'.

26     closeObserver: host.closeObserver,
                           ~~~~~~~~~~~~~

```

`closeObserver` totally exists on `ServerConfig` and on `JupyterHostRecord` so I don't know what gives...

**Comment by rgbkrk** [comment]
Nice, I got it all fixed for typescript. ❤️

**Comment by rgbkrk** [comment]
This is the error that comes up with a desktop build right now

```
TypeError: The 'compilation' argument must be an instance of Compilation
```

Supposedly this is from having multiple versions of webpack in a repo (and/or installed globally), but I think I got them all upgraded...

**Comment by rgbkrk** [comment]
```
$ yarn why webpack
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "webpack"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "webpack@5.38.1"
info Has been hoisted to "webpack"
info Reasons this module exists
   - "workspace-aggregator-c3ba5cd3-b7ef-44cd-acc4-4c75060c3b45" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#webpack"
   - Hoisted from "_project_#nteract-on-jupyter#webpack"
info Disk size without dependencies: "14.31MB"
info Disk size with unique dependencies: "18.71MB"
info Disk size with transitive dependencies: "29.86MB"
info Number of shared dependencies: 108
=> Found "next#webpack@4.44.1"
info This module exists because "_project_#@nteract#web#next" depends on it.
info Disk size without dependencies: "3.49MB"
info Disk size with unique dependencies: "10.14MB"
info Disk size with transitive dependencies: "25.41MB"
info Number of shared dependencies: 129
✨  Done in 1.79s.
```

It looks like this is because next relies on webpack 4.44.1, so either webpack has to stay at an older version or next has to be upgraded.

**Comment by rgbkrk** [comment]
Hmmmm, can't upgrade webpack because react-styleguidist is on v4. https://github.com/styleguidist/react-styleguidist/blob/master/package.json#L169

**Comment by rgbkrk** [comment]
Don't believe the ✅ , the desktop app does not run (at least on my machine).

**Comment by captainsafia** [comment]
Heads up that automatic releases are now enabled on the repo (see #5568 for more info). To support automated releases, please make sure that the commits in this PR adhere to the conventional commit format (see https://www.conventionalcommits.org/en/v1.0.0/). Once this PR is merged, a release will be triggered for the modified packages based on the commit message.

**Comment by rgbkrk** [comment]
I think I'll drop this PR for now and hopefully I or someone else comes back to it. We need some upstream changes first.

**Pull request closed without merging**
