### PR TITLE
chore(Components): Resolved Flow errors resulting from installing third party libdefs

### PR DESCRIPTION
**Pull request by peggyrayzis**
Fixed the errors resulting from the flow-typed libdefs. Hopefully this results in a clean Travis build with no Flow errors 😄

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looking at the Travis log for `flow`:

```
 43: function isDragUpper(props: Props, monitor: DropTargetMonitor, el: HTMLElement): boolean {
                                                 ^^^^^^^^^^^^^^^^^ identifier `DropTargetMonitor`. Could not resolve name
```

**Comment by peggyrayzis** [comment]
😡  Travis is showing 4 Flow errors that aren't showing when I run Flow locally. I think it might have something to do with the types not being exported:

https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-dnd_v2.x.x/flow_v0.23.x-/react-dnd_v2.x.x.js#L205-L211

**Comment by rgbkrk** [comment]
Yeah I was wondering how to get to those. Unsure what to do here.

**Comment by rgbkrk** [comment]
> I think it might have something to do with the types not being exported

Perhaps we can make a PR or raise an issue on the `flow-typed` repo.

**Comment by rgbkrk** [comment]
In the meantime, we could declare the types here I suppose.

**Comment by peggyrayzis** [comment]
> Perhaps we can make a PR or raise an issue on the flow-typed repo.

Good call. I'm going to mess around with it for one more day and try to use only their exported types, but if I can't get it to work, then we should def raise an issue.

**Comment by peggyrayzis** [comment]
Fixed the Flow errors but now we have a build problem! @rgbkrk any ideas as to why?

**Comment by rgbkrk** [comment]
Only on x86 too, let me restart the build.

**Comment by rgbkrk** [comment]
```
Error output:
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global jsonlint-lines-primitives@1.6.0 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g
prebuild WARN install got an error, rolling back install
prebuild ERR! configure error 
prebuild ERR! stack Error: connect ETIMEDOUT 23.23.162.51:443
prebuild ERR! stack     at Object.exports._errnoException (util.js:1026:11)
prebuild ERR! stack     at exports._exceptionWithHostPort (util.js:1049:20)
prebuild ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
prebuild ERR! not ok 
prebuild ERR! build Error: connect ETIMEDOUT 23.23.162.51:443
prebuild ERR! build     at Object.exports._errnoException (util.js:1026:11)
prebuild ERR! build     at exports._exceptionWithHostPort (util.js:1049:20)
prebuild ERR! build     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999" "--build-from-source"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! zmq-prebuilt@2.1.0 install: `prebuild --install`
```

Weird that only x86 had problems @lgeiger. I rekicked the build for now.

**Comment by rgbkrk** [comment]
All is passing now!

**Comment by rgbkrk** [comment]
Another excellent flow PR @peggyrayzis! Thank you!

**Comment by peggyrayzis** [comment]
No prob! On to the Redux code 🚀 !

**Comment by rgbkrk** [comment]
Since this goes with `monitor: Object` for now, what should our follow up be? Posting in `flow-typed`?

**Comment by peggyrayzis** [comment]
I actually don't know if we need to. By using DragSource & DropTarget as our types, I believe it [checks the subtypes of the monitor & connector](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-dnd_v2.x.x/flow_v0.23.x-/react-dnd_v2.x.x.js#L169-L177) through the third parameter ([collect function](https://gaearon.github.io/react-dnd/docs-drop-target.html)) passed to the DropTarget/DragSource wrappers.

What do you think?

**Comment by rgbkrk** [comment]
That sounds perfectly fine, plenty more to tackle here.

**Comment by lgeiger** [comment]
@rgbkrk It looks like a network problem. We could tell AppVeyor and Travis to retry the installation if we experience more issues like this.

Anyway, ~~I'll make~~ I made a [PR](https://github.com/sindresorhus/shell-env/pull/6) to the `shell-env` package to remove the deprecation warning.

**Pull request merged**
