### PR TITLE
Flow typed cleanup

### PR DESCRIPTION
**Pull request by lgeiger**
This PR cleans up our flow definitions, with the goal to simplify `rxjs` and `redux-observable` upgrades going on in #3042

This PR introduces the following changes
- I removed all stubs, since to my knowledge they don't provide a lot of benefit, other than cluttering the repo
- installed the latest definitions using `flow-typed install --skip`, skipping stubs for definitions that are not available
- added `redux-observable` typings converted from [typescript](https://github.com/redux-observable/redux-observable/blob/master/index.d.ts) using [`flowgen`](https://github.com/joarwilk/flowgen/) since the previously used typings aren't compatible
- fixed all remaining flow issues and added FixMe's in cases were flow definitions are still incomplete (mainly redux connect)

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is great, thank you!

**Comment by rgbkrk** [comment]
We should probably just go ahead and delete the TODOs that come from upstream flow definitions.

**Comment by lgeiger** [comment]
> We should probably just go ahead and delete the TODOs that come from upstream flow definitions.

I agree, but this may cause problems, when later upgrading them via the CLI, because flow-typed will recognize the change and abort

**Comment by rgbkrk** [comment]
I see, so we'll just let [the todo bot](https://todo.jasonet.co/) make the issues, then we'll keep 'em open or close 'em?

**Comment by lgeiger** [comment]
> Then we'll keep 'em open or close 'em?

I'd say close them 😇

**Pull request merged**
