### PR TITLE
chore(lint): Fix indentation

### PR DESCRIPTION
**Pull request by lgeiger**
This should fix the travis failures in the greenkeeper PRs.

### CODE REVIEW

**Comment by lgeiger** [comment]
Whaaat??
Travis tells me this:

```
/home/travis/build/nteract/nteract/src/notebook/components/cell/cell.js
  123:13  error  Expected indentation of 10 space characters but found 12  react/jsx-indent
/home/travis/build/nteract/nteract/src/notebook/components/cell/markdown-cell.js
  141:12  error  Expected indentation of 9 space characters but found 11  react/jsx-indent
/home/travis/build/nteract/nteract/src/notebook/components/notebook.js
  238:13  error  Expected indentation of 10 space characters but found 12  react/jsx-indent
/home/travis/build/nteract/nteract/src/notebook/components/status-bar.js
  30:17  error  Expected indentation of 14 space characters but found 16  react/jsx-indent
✖ 4 problems (4 errors, 0 warnings)
```

My local machine told me before this PR:

```
/Users/lukasgeiger/code/nteract/src/notebook/components/cell/cell.js
  123:11  error  Expected indentation of 12 space characters but found 10  react/jsx-indent

/Users/lukasgeiger/code/nteract/src/notebook/components/cell/markdown-cell.js
  141:10  error  Expected indentation of 11 space characters but found 9  react/jsx-indent

/Users/lukasgeiger/code/nteract/src/notebook/components/notebook.js
  238:11  error  Expected indentation of 12 space characters but found 10  react/jsx-indent

/Users/lukasgeiger/code/nteract/src/notebook/components/status-bar.js
  30:15  error  Expected indentation of 16 space characters but found 14  react/jsx-indent

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by rgbkrk** [comment]
What I tend to do for the lint update PRs is either do the package bumps + the linting or submit commits to the branches that greenkeeper created.

**Comment by lgeiger** [comment]
I'll do that. Maybe I have a different version on my local machine.

**Comment by rgbkrk** [comment]
> Whaaat?? 

The linting rule changed, you'll also want to bump/update the dependency to the levels that are in the greenkeeper PRs.

**Comment by lgeiger** [comment]
I tested it again and get this error with the current master. This isn't related to the greenkeeper PR.

I think travis fails because it has a old version of the eslint-plugin installed. Since we cache `node_modules` this could be possible.

**Comment by rgbkrk** [comment]
Alright, let's bring it in and see if all is passing. I'll clear the Travis cache.

**Pull request merged**
