### PR TITLE
Add a Azure Pipelines status badge to the Readme

### PR DESCRIPTION
**Pull request by vijayma**
- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by vijayma** [comment]
This is a follow-up to the comment here: https://github.com/nteract/nteract/pull/3360#issuecomment-424071509 to get a status badge for the Azure Pipelines build.

**Review by rgbkrk — APPROVED** [review]
Thank you!

**Comment by rgbkrk** [comment]
Welcome to the nteract party! I look forward to more azure pipelines goodness to supplement or replace what we have on CircleCI. 😄

**Comment by vijayma** [comment]
Thanks. I am on the Azure Pipelines team. I will be happy to answer any questions or solve issues as you go along.

**Comment by rgbkrk** [comment]
Awesome. I'm having trouble figuring out how to add more people as admins, I'd like to enable as many folks as possible, including you Vijay.

**Comment by vijayma** [comment]
In dev.azure.com/nteract/nteract, select Project settings (gear icon in the bottom left) -> Security -> Build administrators.

**Pull request merged**
