### PR TITLE
[notebook-render]Fix raw html and styles

### PR DESCRIPTION
**Pull request by ghost**
- By default react-markdown do not allow raw html, this allow html in markdown as in other notebook viewers.
- include jsx styles when rendering `NotebookRender` component.

### CODE REVIEW

**Comment by ghost** [comment]
@rgbkrk I added you to reviewers but maybe I could merge it alone and you'll review on next publish later.

**Comment by rgbkrk** [comment]
Fantastic, this is great. I can ship this right now too.

**Comment by rgbkrk** [comment]
```
$ lerna publish
lerna info version 2.8.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with @nteract/commuter@5.4.0.
lerna info Checking for prereleased packages...
? Select a new version for @nteract/gatsby-transformer-ipynb (currently 1.0.1) Patch (1.0.2)
? Select a new version for @nteract/notebook-render (currently 1.0.1) Patch (1.0.2)
? Select a new version for @nteract/showcase (currently 0.1.22) Patch (0.1.23)

Changes:
 - @nteract/gatsby-transformer-ipynb: 1.0.1 => 1.0.2
 - @nteract/notebook-render: 1.0.1 => 1.0.2
 - @nteract/showcase: 0.1.22 => 0.1.23

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published @nteract/notebook-render
lerna info published @nteract/showcase
lerna info published @nteract/gatsby-transformer-ipynb
lerna info git Pushing tags...
Successfully published:
 - @nteract/gatsby-transformer-ipynb@1.0.2
 - @nteract/notebook-render@1.0.2
 - @nteract/showcase@0.1.23
lerna success publish finished
```

**Comment by ghost** [comment]
Nice work :zap:

**Pull request merged**
