### PR TITLE
Dynamically set base path for notebook

### LINKED ISSUE #1242: Markdown cells don't render local images
bildschirmfoto 2016-11-24 um 22 48 59

~~The same happens with local images~~

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/nteract/nteract/issues/1242.

Relative paths within a notebook are now relative to the location of the notebook file.

For new notebooks, this will continue to default to the location of the install. If we want, we can do something like default it to their home directory.

### CODE REVIEW

**Comment by mpacer** [comment]
What is react helmet doing?

I hadn’t realized this about relative paths wasn’t being already taken into account. Could you give a concrete example of where this comes up?

**Comment by mpacer** [comment]
Ah from #1242 


it only affects markdown cells.

**Comment by mpacer** [comment]
Is there a good place to put tests for this behaviour?

**Review by BenRussert — APPROVED** [review]

**Comment by captainsafia** [comment]
> Is there a good place to put tests for this behaviour?

Hm. Depends on what this behavior is referring to. If we just wanted to check that the `<base>` attribute was set properly, we could do that in Jest. I'll add those tests to this PR.

For checking that the image was rendered properly, we would probably need to set up some integration tests.

**Pull request merged**
