### PR TITLE
docs(install): Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by lgeiger**
Please test this. It sounds to good to be true 😆

### CODE REVIEW

**Comment by rgbkrk** [comment]
Yeah I'm pretty surprised about `pkg-config`.

**Comment by rgbkrk** [comment]
The only true way we can test this on OS X is to put it on a fresh Mac.

For Linux, we can test this in Docker or a VM. 🤔

**Comment by rgbkrk** [comment]
Even if we have to add them back in later, the brilliant thing is that the dep check script here can be updated and we'll still inform devs in automation.

**Comment by lgeiger** [comment]
I'm pretty confident about `pkg-config`. I ran `sudo apt-get remove pkg-config` and everything still works.

**Comment by lgeiger** [comment]
I'm going to test this on a fresh install:
- [x] OS X 10.11.6
- [x] Ubuntu 16.04

**Comment by lgeiger** [comment]
The installation works out of the box on a fresh install of OS X. 🎉 

I get a warning because `python2` is unset. But we can check for `python2.7` which is the default.
Fun fact: 2GB RAM isn't enough to build zeromq on the first try 😄

**Comment by rgbkrk** [comment]
> Fun fact: 2GB RAM isn't enough to build zeromq on the first try

Wow that is a very important fun fact.

**Comment by lgeiger** [comment]
It isn't that bad. On the second try the build starts where it left of and succeeds.

**Comment by lgeiger** [comment]
All good on Ubuntu as well! 🎉

**Pull request merged**
