### PR TITLE
Back to hoisting

### PR DESCRIPTION
**Pull request by rgbkrk**
Apologies to @lgeiger for all the swapping back and forth on yarn, npm, and hoisting. I'm trying to see if I can get styled-jsx hoisted at the very least and generally make everything neat and tidy. For now I'm going after general hoisting again though I'm running into issues during desktop's postinstall, which I'm now trying to debug manually:

```
nteract/packages/desktop$ ./node_modules/.bin/electron-builder install-app-deps
electron-builder 19.46.4
Error: Unresolved node modules: follow-redirects, https-proxy-agent, mime, netrc, jp-kernel, zeromq, lodash
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder-lib/src/util/packageDependencies.ts:112:19
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder-lib/out/util/packageDependencies.js:208:11)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder-lib/src/util/packageDependencies.ts:88:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

### CODE REVIEW

**Comment by lgeiger** [comment]
Are you on the latest version of electron-builder?

**Comment by rgbkrk** [comment]
As of #2103, `master` now is. I'll rebase this PR.

**Comment by rgbkrk** [comment]
Ok, rebased against master and running into the same issue as before.

**Comment by rgbkrk** [comment]
As pointed out by @lgeiger in chat, https://github.com/electron-userland/electron-builder/issues/2222 is a culprit for this.

**Comment by rgbkrk** [comment]
Just to see what else might be an issue, I disabled the postinstall of desktop to go ahead and run tests. Across the board `jest` couldn't resolve `uuid` (which is at the root):

```
 FAIL  packages/editor/__tests__/tooltip-spec.js
  ● Test suite failed to run

    Configuration error:

    Could not locate module uuid (mapped as /Users/kylek/code/src/github.com/nteract/nteract/packages/commutable/node_modules/uuid)

    Please check:

    "moduleNameMapper": {
      "/uuid/": "/Users/kylek/code/src/github.com/nteract/nteract/packages/commutable/node_modules/uuid"
    },
    "resolver": undefined
```

**Comment by rgbkrk** [comment]
Oh wait, that was hardcoded into the `moduleNameMapper`

**Comment by rgbkrk** [comment]
```
$ ./packages/desktop/node_modules/.bin/electron-builder install-app-deps
electron-builder 19.46.9
No native production dependencies
```

~~Um what?~~ Edit: oh right, I need to be in the desktop package directory

**Comment by rgbkrk** [comment]
Interesting, on travis desktop is failing to build because it can't resolve nteract asset's css files.

**Comment by rgbkrk** [comment]
Closing, let's revisit after the next electron builder release.

**Pull request closed without merging**
