### PR TITLE
fix(display): pass width and height through to img component

### PR DESCRIPTION
**Pull request by rgbkrk**
screen shot 2016-10-06 at 10 48 01 pm

### CODE REVIEW

**Comment by rgbkrk** [comment]
Closes #885.

**Comment by jdetle** [comment]
Nice! Does the laptop have a name?

**Comment by rgbkrk** [comment]
You know, I'm not sure we named lappy. I guess that's lappy's name. It's featured on https://nteract.io/.

**Review by jdetle — APPROVED** [review]

**Comment by jdetle** [comment]
:+1: for lappy 3000

**Pull request merged**
