### PR TITLE
Add code that creates a menu

### PR DESCRIPTION
**Pull request by jdfreder**
Problem: We don't have an application menu
Sln: Create code that can generate one and dispatch store actions

cc: @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
I definitely see how we can rely on some of this with a web based version too, straddling similar actions. Don't activate on coding or designing for that yet, just a thought.

**Comment by jdfreder** [comment]
Right now the 'Open' menu item is bound to the `readJSON` method which requires a single parameter, the JSON file path.  Really what we need here is an action that displays an open dialog and then invokes readJSON for the user selected path.

It's important to note that with the menu, only actions that accept 0 parameters can be invoked!

**Comment by rgbkrk** [comment]
Weird that the first menu item is `Electron` here (on Mac at least):

screenshot 2016-02-08 10 40 12

**Comment by rgbkrk** [comment]
> Really what we need here is an action that displays an open dialog and then invokes readJSON for the user selected path.
> It's important to note that with the menu, only actions that accept 0 parameters can be invoked!

ohhhh, so the action needs to be one that triggers the open dialog and then results in reading the notebook

**Comment by jdfreder** [comment]
Yeah, but I bound to readJSON just to show that the dispatcher is working.

**Comment by rgbkrk** [comment]
Yeah, that's cool. I'm stating it as an understanding mostly for myself and others to know what follow on PRs for other actions needs to be.

**Pull request merged**
