### PR TITLE
Execution

### PR DESCRIPTION
**Pull request by rgbkrk**
It's alive!

screenshot 2016-02-09 22 12 01

### CODE REVIEW

**Comment by rgbkrk** [comment]
Alright, we now have basic execution running. Lots of missing things here: detecting the status change to busy followed by idle, updating the input numbering, etc. Many of these can be brought over from ick pretty easily.

**Comment by rgbkrk** [comment]
One thing I'm not sure of for fixing - shift-enter currently causes a newline. I'm not sure how to prevent that yet.

**Comment by rgbkrk** [comment]
@jdfreder tested your language switching!

screenshot 2016-02-09 22 27 33

**Comment by captainsafia** [comment]
Let me check this out...

**Comment by rgbkrk** [comment]
> Let me check this out...

:eyes:

**Comment by captainsafia** [comment]
A small annoying detail I noticed is that even when pressing Shift + Enter, a new line is added to the text area. Adding  `e.preventDefault()` should do the trick, I think...

EDIT: Ha! Just realized you pointed out the new line thing yourself. Does `e.preventDefault()` work?

**Comment by rgbkrk** [comment]
Haven't tried yet! I expected fixing that to be tricky enough that I didn't want it tangled in this PR. If it's as simple as you say, then a follow on PR should be pretty quick.

Little iterations over time to refine towards the experience we want.

**Comment by kenwheeler** [comment]
@rgbkrk @captainsafia e.preventDefault does indeed work

**Comment by rgbkrk** [comment]
Super awesome, thanks @captainsafia and @kenwheeler

**Comment by jdfreder** [comment]
:tada:

**Pull request merged**
