### PR TITLE
Jupyter Extension

### PR DESCRIPTION
**Pull request by rgbkrk**
:tada:

I've been working on a jupyter extension that will load the nteract web app at `/nteract/`. This is very early stages and I'm thinking the "first" release can just be a simple viewer since we'll have to lay the base foundations for webpack, the python handler(s), and initial imports of styling, etc.

## Overview

If it was possible to use next.js underneath the tornado web server without overengineering (proxying, would have to handle both HTTP/2 and websockets), I would just use next.js. Instead of that, I'll try to mirror much of the next.js design here, while working in tandem with the style of the jupyter notebook handlers.

### Views (pages)

Aim to be compatible with the classic Notebook server user facing URLs (though with an `nteract` prefix)

* `/tree/`
* `/edit/` - edit scripts _and_ notebooks
* `/view/` - literally just a view, still needs to defer to `/files/` in the same way we do on commuter (and the notebook server)

We'll take a contents API first approach, effectively replicating `commuter` over to here.

### Must haves for this PR

* [x] webpack setup that builds our main app
* [x] basic layout that others can install and run
* [x] basic viewing of notebooks at `/nteract/view`
* [x] proper handling of being served on a base path (e.g. `/users/rgbkrk/`)

## Collaborate

If anyone wants to collaborate on this, let me know! I can get this PR in a mergeable state with just the basic building blocks and we can carve things up.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Alright, this finishes off the must-haves I declared above. I wouldn't say this is a _useful_ extension yet by any means. It just paves a little setup for us to hack on and start distributing.

**Comment by rgbkrk** [comment]
I'm hoping I "fixed" the flow errors and everything is situated pretty well now.

**Comment by rgbkrk** [comment]
What the fresh hell?

```
Logs will go to /tmp/flow/zShomezStraviszSbuildzSnteractzSnteract.log
src/notebook/reducers/document.js:62
 62:   // $FlowFixMe: Not sure what the issue is for why it doesn't think the List is not the same as a List
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
src/notebook/reducers/document.js:292
292:   // $FlowFixMe: Not sure what the issue is for why it doesn't think the List is not the same as a List
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
src/notebook/reducers/document.js:311
311:   // $FlowFixMe: Not sure what the issue is for why it doesn't think the List is not the same as a List
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
src/notebook/reducers/document.js:415
415:   // $FlowFixMe: Not sure what the issue is for why it doesn't think the List is not the same as a List
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
src/notebook/reducers/document.js:583
583: [0m      // $FlowFixMe: Not sure what the issue is for why it doesn't think this Map matches
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

```

**Comment by rgbkrk** [comment]
My wtf is because those exact lines were having trouble before (earlier in this PR).

**Comment by rgbkrk** [comment]
Yay, this is working and semi-shippable!

**Comment by nelix** [comment]
This is a pretty good start.. I was thinking about yanking npm support from codesandbox or upkg last night...

**Comment by rgbkrk** [comment]
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension

**Pull request merged**
