### PR TITLE
Rely on the new ansi-to-react

### PR DESCRIPTION
**Pull request by rgbkrk**
This bumps us to the new transformime and react display area.

screenshot 2016-03-19 18 30 39

### CODE REVIEW

**Comment by jdfreder** [comment]
Strange, what happens when you dump the whole thing, spans and all, into a pre tag

**Comment by rgbkrk** [comment]
Had to set `white-space: pre` to make it work. Back in business.

**Comment by rgbkrk** [comment]
screenshot 2016-03-19 18 30 39

**Comment by jdfreder** [comment]
Awesome!  :cake:

**Comment by rgbkrk** [comment]
I'm not sure what's going on (environment variables?) but I'm getting stripped plain text in both the jupyter notebook and in nteract:

screenshot 2016-03-20 09 30 16

Not on tmpnb.org though:

screenshot 2016-03-20 09 31 43

(though also wrong in a different way).

**Comment by rgbkrk** [comment]
If I load that same notebook from tmpnb.org on nteract though, we get the right colors. :smile:

screenshot 2016-03-20 09 35 28

**Pull request merged**
