### PR TITLE
Explicit transpile

### PR DESCRIPTION
**Pull request by jdfreder**
This PR makes the "transpilation" of es6 to es5 explicit.  Developers should run `npm run build:watch` to automatically incrementally compile as changes are made.  This will **greatly** simplify the problem of redistributing and packaging nteract.

Pleasant side effect, nteract seems to launch quicker!

### CODE REVIEW

**Comment by rgbkrk** [comment]
> Pleasant side effect, nteract seems to launch quicker!

That's definitely going to happen since it doesn't have to compile on start everytime (production mode for electron compile does this too).

**Comment by rgbkrk** [comment]
There's currently a merge conflict, though I'm in favor of switching to the build system to make distribution simpler.

**Comment by jdfreder** [comment]
This is good to go...

**Comment by rgbkrk** [comment]
Curious what made you choose es5 instead of `dist` or `build`.

It will take me some time mentally to wrap my head around the new hierarchy with static resources in a separate folder rather than being grouped logically with the app using them.

**Comment by jdfreder** [comment]
No reason in particular, just trying to avoid conflicts with later build steps

**Comment by Carreau** [comment]
> No reason in particular, just trying to avoid conflicts with later build steps

Should we maybe make make it underscore or dot prefix to be more sure people won't modify these ?

**Comment by rgbkrk** [comment]
```
$ npm t

> nteract@0.0.1 test /Users/kyle6475/code/src/github.com/nteract/nteract
> npm run test:main && npm run test:renderer


> nteract@0.0.1 test:main /Users/kyle6475/code/src/github.com/nteract/nteract
> electron-mocha --compilers js:babel-core/register 'test/main/**/*.js'

{ [Error: Cannot find module '../../es5/main/launch'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '../../es5/main/launch'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (launch.js:3:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/mocha/lib/mocha.js:468:10)
    at Object.run (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/electron-mocha/mocha.js:60:28)
    at EventEmitter.<anonymous> (/Users/kyle6475/code/src/github.com/nteract/nteract/node_modules/electron-mocha/index.js:45:11)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
```

**Comment by jdfreder** [comment]
Hmm strange, I thought I had npm t working here

**Comment by jdfreder** [comment]
@Carreau I think dist and build are both standard names for compiled content, they should be okay

**Pull request merged**
