### PR TITLE
Disco Mode

### PR DESCRIPTION
**Pull request by kenwheeler**
I'm so sorry:

disco-mode

### CODE REVIEW

**Comment by rgbkrk** [comment]
Beautiful. 10/10 best use of undefined.

**Comment by captainsafia** [comment]
I stopped doing Important Things to merge this because I agree this is high priority!

**Comment by captainsafia** [comment]
If anyone else merges this I will be a very angry cat.

**Comment by rgbkrk** [comment]
At least we'll very clearly know what code path our users went down to get to the hidden theme.

**Comment by Carreau** [comment]
Hide it behind a konami code and I'll merge it.

**Comment by captainsafia** [comment]
Checks cannot finish quickly enough!

**Comment by rgbkrk** [comment]
It's currently hidden behind the theme variable being unset. :wink:

**Comment by Carreau** [comment]
> It's currently hidden behind the theme variable being unset.

Sure, I still think it should be hidden behind a konami code :-P

**Comment by rgbkrk** [comment]
We should definitely enable a konami code here.

**Comment by rgbkrk** [comment]
RxJS 4 (with RxDOM) has [an example for konami codes](https://github.com/Reactive-Extensions/RxJS/blob/master/examples/konamicode/konamicode.js).

**Comment by jdfreder** [comment]
> Checks cannot finish quickly enough!

Yeah we need to cache the ZMQ stuff

**Comment by captainsafia** [comment]
@jdfreder, how could you take this life-changing merge opportunity from me?!!!?

My life is never going to be satisfying and none of my dreams will ever be fulfilled.

**Comment by jdfreder** [comment]
:trollface:

**Comment by jdfreder** [comment]
> If anyone else merges this I will be a very angry cat.

Actually I didn't see this, sorry!

**Pull request merged**
