### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by rgbkrk**
Trying out Azure Pipelines for nteract.

Created this PR straight from the Azure Pipelines UI:

screen shot 2018-09-24 at 9 56 49 am

Their [JavaScript and Node.js Section](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml) has much more detail on what we can do.

### CODE REVIEW

**Comment by rgbkrk** [comment]
screen shot 2018-09-24 at 9 56 49 am

**Comment by rgbkrk** [comment]
I don't understand how/why CircleCI tests were cancelled...

**Comment by rgbkrk** [comment]
Not sure why CircleCI called that a redundant build. I'm going to go ahead and allow redundant builds.

**Comment by rgbkrk** [comment]
Seems like we're running out of memory on Circle CI because of parallel babel builds again. Lame.

**Comment by kaylangan** [comment]
I'm a Program Manager for Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by rgbkrk** [comment]
Pretty awesome so far @kaylangan! I'd love to get Windows builds happening via Azure pipelines too -- is there a good guide for us to follow? (We'll also take PRs. 😄 )

**Comment by zooba** [comment]
To save you some time, here's the Markdown for the badge for your readme (you can customize the branch parameter if you like, also `label=` is an option to change the default "Azure Pipelines" text)

[Build Status](https://dev.azure.com/nteract/nteract/_build/latest?definitionId=1&branch=master)

```
[![Build Status](https://dev.azure.com/nteract/nteract/_apis/build/status/nteract.nteract?branch=master)]
(https://dev.azure.com/nteract/nteract/_build/latest?definitionId=1&branch=master)
```

**Comment by rgbkrk** [comment]
Oooh, nice.

**Comment by zooba** [comment]
Oh, and `label=` supports emoji characters, if you want to go there :)

**Pull request merged**
