### PR TITLE
Problem: too much going on in code cell

### PR DESCRIPTION
**Pull request by rgbkrk**
Solution: create an execute cell action

Problem: This is not pretty code, needs guidance from #123

### CODE REVIEW

**Comment by rgbkrk** [comment]
What I'd like to do after this is figure out how we can handle not having to pass dispatch or channels in here.

**Comment by rgbkrk** [comment]
This makes it easier for follow on actions that use the kernels like completion, doc requests, etc. while muddying what the story is for our redux-like store.

**Comment by kenwheeler** [comment]
This is great. That logic doesn't necessarily belong in the component. That said, it also doesn't necessarily belong in the action. I recently did something like this on a react native app, where I abstracted service calls to an API module. See below:

```
import Services from "../services";
import * as constants from "../constants";

import config from "../../config/development";
export const API = new Services(config.services);
```

The idea here being, the API (or our channels), can be instantiated and exported right from the actions file. That way we get:
- An abstraction to handle non-actiony logic
- A testable service (or channels) layer
- Access to the service (channel) layer right from actions.

**Comment by rgbkrk** [comment]
Should we be viewing actions as UI triggers?

When a new kernel is loaded, how do we update that service?

**Comment by jdfreder** [comment]
I like @kenwheeler 's suggestion for an `API` module, or something, to store non-action things, but I'd like to know how that would work with something like the declarative menu.  Right now menuitems can define actions by name, and those actions get dispatched on click.  With an API, the menu code would either have to know to look in both the API and actions/index (and we'd have to figure out which had precedence) _or_ you would have to define callbacks instead of actions (loosing some of the declarative goodness).  Do either of you see a way to deal with this in a clean way?

**Comment by jdfreder** [comment]
Let's continue the discussion here, I'm just merging because of C4.1.

**Comment by rgbkrk** [comment]
Yeah I think we can move forward with making services. We have a lot of unanswered questions there.

At the very least, this is no longer coupled to the cell and people can start iterating on some of the other interactions with the kernels.

**Pull request merged**
