### PR TITLE
chore: export display package

### PR DESCRIPTION
**Pull request by rgbkrk**
In order to get the display area extracted I had to finish off the transpilation of the transforms. Since I went through the trouble of it, I also set up a common testing environment for these components.

* [x] Transpile _everything_
* [x] Test the "new" module
* [x] Test all the `transform-*` modules
* [x] Rebase
* [x] Be thankful this PR is finished

### CODE REVIEW

**Comment by rgbkrk** [comment]
I miss when I could make small PRs. This package movement stuff is not for the faint of heart.

**Comment by rgbkrk** [comment]
In order for this to work, I need the transforms to all be transpiled. That's what I'll be onto next.

**Comment by jdetle** [comment]
Its certainly not for the faint of heart, thanks for tackling it!

**Comment by rgbkrk** [comment]
Rebasing soon now that I have this in a decent state.

**Comment by rgbkrk** [comment]
As part of this PR I had to finish off the transpiling of all our other components.

**Comment by rgbkrk** [comment]
I thought that creating "dev-scripts" would be super great at encapsulating all our common dependencies just like `react-scripts`, then I noticed it doesn't provide you the binaries for the dependencies -- I needed `jest`, `babel`, and `flow-copy-source` available.

**Comment by rgbkrk** [comment]
I should be doing this from the base anyways it looks like:

```
$(npm bin)/jest packages/**/__tests__
```

**Comment by rgbkrk** [comment]
Even better:

```
$(npm bin)/jest packages/**/__tests__ --coverage
```

**Comment by rgbkrk** [comment]
One problem we run into running jest from the root -- we would need our `@nteract/mockument` available for the jest config. It looks like we'll have to run these separately.

**Comment by rgbkrk** [comment]
Once I have the plotly tests fixed I'm ready for a _full_ rebase. I haven't been able to diagnose the Plotly test error yet (though I've fixed some things with it):

```
> jest

 FAIL  __tests__/plotly.test.js
  ● PlotlyTransform › plots some data from an object

    SyntaxError

      at HTMLUnknownElementImpl.<anonymous> (../../node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83:11)
      at HTMLUnknownElementImpl.querySelectorAll (../../node_modules/jsdom/lib/jsdom/utils.js:133:45)
      at HTMLUnknownElement.querySelectorAll (../../node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39:62)
      at d3_selectAll (../../node_modules/plotly.js/dist/plotly.js:11772:14)
      at HTMLUnknownElement.<anonymous> (../../node_modules/plotly.js/dist/plotly.js:11828:14)
      at Array.d3_selectionPrototype.selectAll (../../node_modules/plotly.js/dist/plotly.js:11819:55)
      at Object.plot (../../node_modules/plotly.js/dist/plotly.js:146696:18)
      at plotOne (../../node_modules/plotly.js/dist/plotly.js:119599:17)
      at Object.exports.plot (../../node_modules/plotly.js/dist/plotly.js:119563:9)
      at drawData (../../node_modules/plotly.js/dist/plotly.js:110301:32)

  ● PlotlyTransform › plots some data from a JSON string

    SyntaxError

      at HTMLUnknownElementImpl.<anonymous> (../../node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83:11)
      at HTMLUnknownElementImpl.querySelectorAll (../../node_modules/jsdom/lib/jsdom/utils.js:133:45)
      at HTMLUnknownElement.querySelectorAll (../../node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39:62)
      at d3_selectAll (../../node_modules/plotly.js/dist/plotly.js:11772:14)
      at HTMLUnknownElement.<anonymous> (../../node_modules/plotly.js/dist/plotly.js:11828:14)
      at Array.d3_selectionPrototype.selectAll (../../node_modules/plotly.js/dist/plotly.js:11819:55)
      at Object.plot (../../node_modules/plotly.js/dist/plotly.js:146696:18)
      at plotOne (../../node_modules/plotly.js/dist/plotly.js:119599:17)
      at Object.exports.plot (../../node_modules/plotly.js/dist/plotly.js:119563:9)
      at drawData (../../node_modules/plotly.js/dist/plotly.js:110301:32)

  ● PlotlyTransform › processes updates

    SyntaxError

      at HTMLUnknownElementImpl.<anonymous> (../../node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83:11)
      at HTMLUnknownElementImpl.querySelectorAll (../../node_modules/jsdom/lib/jsdom/utils.js:133:45)
      at HTMLUnknownElement.querySelectorAll (../../node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39:62)
      at d3_selectAll (../../node_modules/plotly.js/dist/plotly.js:11772:14)
      at HTMLUnknownElement.<anonymous> (../../node_modules/plotly.js/dist/plotly.js:11828:14)
      at Array.d3_selectionPrototype.selectAll (../../node_modules/plotly.js/dist/plotly.js:11819:55)
      at Object.plot (../../node_modules/plotly.js/dist/plotly.js:146696:18)
      at plotOne (../../node_modules/plotly.js/dist/plotly.js:119599:17)
      at Object.exports.plot (../../node_modules/plotly.js/dist/plotly.js:119563:9)
      at drawData (../../node_modules/plotly.js/dist/plotly.js:110301:32)

  PlotlyTransform
    ✕ plots some data from an object (458ms)
    ✕ plots some data from a JSON string (217ms)
    ✕ processes updates (191ms)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        3.659s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by rgbkrk** [comment]
Looks like my nested mock is not being loaded. :(

**Comment by rgbkrk** [comment]
yay, this is all set now. Doing the rebase.

**Comment by rgbkrk** [comment]
For the time being we can run:

```
$(npm bin)/lerna run test
```

to test across all the exported packages

**Comment by rgbkrk** [comment]
Rebased, ready for review. _phew_ 😅

**Review by lgeiger — APPROVED** [review]
Thank you so much for this 👍 🎉 

Sadly `dev-scripts` can't provide binaries. 

Aren't the other dev dependencies available anyway, even without `dev-scripts`, since we include them in the top level `package.json`?

**Comment by rgbkrk** [comment]
Yeah the other dev dependencies are still available so this makes it more like "nteract-presets-and-dev-stuff".

**Pull request merged**
