### PR TITLE
(docs) Add README to Display Area Package

### PR DESCRIPTION
**Pull request by aunyks**
In this commit, I added a README to the Display Area package (so that it can be published to NPM). If there are any changes that I need to make, please let me know!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Some suggested text to add in:

````markdown
Render Jupyter notebook outputs in a trim little React component.

## Installation

```
npm install @nteract/display-area
```

## Usage

```jsx
import Display from '@nteract/display-area`
<Display outputs={outputs} />
```

Here `outputs` is an Immutable.js structure with all the outputs of a cell. Note: this does require trim, clean editions of the multiline cells as is done in `@nteract/commutable`.

Used in context of a notebook, you will likely be extracting it from a cell:

```jsx
<Display outputs={this.props.cell.get('outputs')} />
```

````

**Comment by rgbkrk** [comment]
We can keep iterating on this -- it's worth checking out what's in [notebook-preview](https://github.com/nteract/nteract/blob/master/packages/notebook-preview/src/code-cell.js#L73-L82), one of the components that uses this.

**Comment by rgbkrk** [comment]
As for CI, I'm going to get that situated / fixed up.

**Comment by aunyks** [comment]
@rgbkrk I've made the additions. Also, thanks for linking me to a usage of the component. That really helped me understand it better.

**Review by rgbkrk — APPROVED** [review]
Thanks!

**Pull request merged**
