### PR TITLE
Remove cell toolbar ghosts

### LINKED ISSUE #465: Cell toolbar menu doesn't always hide
celltoolbar

### PR DESCRIPTION
**Pull request by jdfreder**
I hate having to do this, but it's the workaround I've settled on because both React and native mouseleave events are not firing reliably...

closes #465

### CODE REVIEW

**Comment by rgbkrk** [comment]
We do have access to the DOM with `electron-mocha` for testing. `setCellHoverState` seems like the most likely candidate for testing.

**Comment by rgbkrk** [comment]
One day I look forward to deeper testing than this. Good framing for a later pass. :smile:

**Comment by rgbkrk** [comment]
I can no longer click trash before the upper right cell toolbar disappears.

**Comment by jdfreder** [comment]
Oh you know what, I was testing on the classic theme.  It may be that the mask is different than the other themes.  I can look at this tomorrow

**Pull request merged**
