### PR TITLE
Add loading placeholder image and text

### PR DESCRIPTION
**Pull request by jdfreder**

### CODE REVIEW

**Comment by jdfreder** [comment]
Action shot:

loading

**Comment by captainsafia** [comment]
OMG. Is it the animated logo or a still?

**Comment by jdfreder** [comment]
I wish it was animated though...  I think I may look into the splash screen method @rgbkrk suggested in slack.

**Comment by rgbkrk** [comment]
Yup, this is pretty slick even when fading into the dark theme.

**Comment by Carreau** [comment]
Could be made SVG and have the color dynamic/pulsing.

**Comment by jdfreder** [comment]
No, animations, svg, iframe, gif etc, don't render during the synchronous require call :(

**Comment by Carreau** [comment]
> No, animations, svg, iframe, gif etc, don't render during the synchronous require call :(

:-(

**Pull request merged**
