### PR TITLE
Don't Merge: Proposed dep injected subject tests.

### PR DESCRIPTION
**Pull request by kenwheeler**
This is a proposed approach for testing our async flows within actions/agendas that uses `babel-plugin-rewire` to inject mocks into the tested module on the fly.

cc @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
Whoa, that's pretty neat. I've been wondering about the right way to do mocks with these.

**Comment by rgbkrk** [comment]
Should we go ahead and close this now that we're on redux with redux-observable?

**Comment by kenwheeler** [comment]
I should probably just refactor these right?

**Comment by rgbkrk** [comment]
Sounds good to me!

**Comment by rgbkrk** [comment]
Closing due to inactivity.

**Pull request closed without merging**
