### PR TITLE
fix(ui): hide status bar during pdf export

### PR DESCRIPTION
**Pull request by jarmokivekas**
Fixes issue #4389 by adding a missing class attribute to the top-level div of the status bar. 

The css class rule for hiding the status bar during pdf export already exists from before, but the div lost its class attribute at some point. This PR puts it back. 
 
https://github.com/nteract/nteract/blob/f63a01c4067b05541ebddd3932345d7102ea3e5b/applications/desktop/static/index.html#L276-L282

### CODE REVIEW

**Review by captainsafia — CHANGES_REQUESTED** [review]
Thanks for opening this PR! Given that we've recently moved to styled-components, can you try fixing this the other way around, by bringing the media query style on the `Bar` styled-component defined in this file. Essentially something like this

```
export const Bar = styled.div`
   ...
   @media print {
       display: none;
    }
`
```

**Comment by captainsafia** [comment]
This will also close https://github.com/nteract/nteract/issues/4346 when complete.

**Comment by jarmokivekas** [comment]
Thanks for the pointer @captainsafia. Having not used styled-component before I didn't realize this was an option. I've removed the old rule for `.status-bar`, which is not used anywhere, and replaced with a rule in `Bar` itself.

This way the export looks as expected, with no staus bar:
image

**Comment by jdetle** [comment]
There are a few more items listed here that also need to be addressed at some point: 
```
        .notifications-wrapper {
          display: none !important;
        }
        .cell-toolbar {
          display: none !important;
        }
        .cell-creator {
          display: none !important;
        }
        .cell.focused {
          border: none;
          background: 
		}
```

**Review by jdetle — CHANGES_REQUESTED** [review]
I left a comment, if you could address the rest of the changes that need to be made it would be much appreciated.

**Comment by jarmokivekas** [comment]
- `.notification-wrapper` , `.cell-toolbar` , `.cell-toolbar-mask`, `.cell-creator`, classes is not used anywhere anymore.
- notification popups behave well, and aren't visible in pdf exports
- cell toolbars are shown on the active/selected cell.
- active code cell has darker background color in the cell execution order number (left silde of the cell)
image

**Comment by jarmokivekas** [comment]
The css classes `notifications-wrapper`, `cell-toolbar`, `cell-creator`, `draggable-cell`, `cell-drag-handle`, `cell-toolbar-mask`, `invisible` aren't used by anything anymore, so I removed them.

- notification popups and the cell creator buttons were already well behaved, and aren't visible in pdf exports (even if you try to deliberately export pdf while they are visible in the application).
- cell toolbars are shown when a cell is focused, I added `@media print` rule to the component to hide them.
- selected code cell has darker background in the left silde of the cell (area with the `[ ]`)

PDF export in current master: 

image


These rules used to deal with the active cell color during print, but don't anymore (obsolete css rules):
https://github.com/nteract/nteract/blob/f63a01c4067b05541ebddd3932345d7102ea3e5b/applications/desktop/static/index.html#L292-L298

 It's not obvious to me how to fix the focused cell color in the components.

---

I also noticed that the z-order of the notification wrappers and the cell toolbar aren't configured quite right, but didn't look into it yet. Althoug it's not a problem when exporting, since both are hidden in the PDF.

Screenshot from 2019-05-06 19-46-16

**Comment by jdetle** [comment]
> It's not obvious to me how to fix the focused cell color in the components.

Maybe you can wrap that in `@media only screen`?

**Comment by jarmokivekas** [comment]
I think figured out the color of the focused Cell components.

With current changes:
- [x] no notification popups
- [x] no cell creator buttons
- [x] focused/hovered cell `[ ]` prompt color is correct
- [x] cell toolbars are hidden
- [x] no status bar displayed

Test notebook and exported pdf:

Screenshot from 2019-05-06 23-16-13

I'm happy with the the way the pdf is exported now. Comments?

**Comment by jarmokivekas** [comment]
There are tests  in `packages/notebook-app-component/__tests__/toolbar.spec.tsx` that fail because of changes in this PR. I guess the new toolbar no longer matches the snapshot the tests compare it against? If someone can give some pointers on how to update the failing tests, it would be much appreciated.

_Edit_: I think I figured it out. So many new frameworks...

**Comment by captainsafia** [comment]
@jarmokivekas It looks like you figured out how to update the tests. Sorry I couldn't respond sooner. Is this PR good for a re-review?

**Comment by jarmokivekas** [comment]
Yes, this PR is good for a re-review @captainsafia @jdetle

**Review by jdetle — APPROVED** [review]

**Pull request merged**
