### PR TITLE
chore: bring in all packages using jupyter-paths

### LINKED ISSUE #1794: Move more base modules into monorepo
All of these depend on `jupyter-paths` which means we end up going through a massive "migrate these packages" run through:

* [x] `enchannel-zmq-backend`
* [ ] `spawnteract`
* [ ] `jupyter-paths`
* [ ] `kernelspecs`

Let's just bring them all together.

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #1794 by squash merging with the subtree strategy, allowing unrelated histories (wayyyyy different repos), and then not letting git make the commit (there were more changes to make).

```
git merge --squash -s subtree --no-commit move-to-monorepo --allow-unrelated-histories
```

This keeps the commit history under the squashed commit (click the `...` then click the relevant commit).

Examples:

* https://github.com/nteract/nteract/commit/4902c7f7dfa16b2be6405d5f852d9c7b63ea072c
* https://github.com/nteract/nteract/commit/2300ba322487e0207513ae2be078521d6c13b6f6

Pros:

* Authors are credited and referenced by commit
* Our git repo is a bit smaller (or is it... the commits _are_ there)

Cons:

* History is not all merged in one (do these still count as contributors within the GitHub UI?)

What do you think @captainsafia, @lgeiger, @jdfreder, and @smashwilson?

## Modules to bring in

* [x] `enchannel-zmq-backend`
* [x] `spawnteract`
* [ ] `jupyter-paths`
* [ ] `kernelspecs`

### CODE REVIEW

**Comment by rgbkrk** [comment]
I think what I might try here is to use the Co-Authored commit message standard and move each repository as a separate commit with all the authors.

**Comment by rgbkrk** [comment]
Alright, the way I did this one was with:

```
git merge --squash -s subtree --no-commit move-to-monorepo --allow-unrelated-histories
```

Which keeps the commit history, just not all on one.

What do you think @captainsafia, @lgeiger, @jdfreder, and @smashwilson?

**Comment by rgbkrk** [comment]
This does still require the initial setup that was done in #1806 (for the originating repo).

**Comment by jdfreder** [comment]
:+1:

**Comment by smashwilson** [comment]
This works, but to inherit the _full_ history you might want to look at [`git subtree`]():

> add::
>
>	Create the <prefix> subtree by importing its contents
>	from the given <commit> or <repository> and remote <ref>.
>	A new commit is created	automatically, joining the imported
>	project's history with your own.  With '--squash', imports
>	only a single commit from the subproject, rather than its
>	entire history.

**Comment by rgbkrk** [comment]
Since this one seems fairly reasonable, I think I'll do this for all the packages we want merged into one.

**Comment by smashwilson** [comment]
Ohh, wait a minute... the destination prefix already exists in the target repo? Yeah, that changes things somewhat. Hmm. How about something like:

```bash
# In nteract/${NAME}
git checkout -b move-to-monorepo
mkdir -p packages/${NAME}
git mv !(packages) packages/${NAME}
git mv .SOMEFILE packages/${NAME} # Catch the dotfiles
git commit -am 'move stuff around'
git push origin move-to-monorepo

# In nteract/nteract
git remote add subpackage-${NAME} git@github.com:nteract/${NAME}.git
git fetch subpackage-${NAME}
git merge subpackage-${NAME}/move-to-monorepo
```

**Review by lgeiger — COMMENTED** [review]
Woa thanks for your work!

Are the tests for spawnteract run on CI? I don't think that happens automatically since we're using `jest` from the root for the other packages.

What about removing `packages/spawnteract/.gitignore`, `packages/spawnteract/.travis.yml` and ` packages/spawnteract/travis_after_success.sh`? I think they aren't used anymore.

**Comment by rgbkrk** [comment]
Yeah I can take those out. I was aiming for purity first, ensuring I gave out credit to the contributors then I figured I'd clean it up for our monorepo. I may not clean up all the tests in this first go round, just making sure it all passes for now. Modernization :soon:

**Comment by rgbkrk** [comment]
Closing in favor of #1810 and follow on PRs.

**Pull request closed without merging**
