### PR TITLE
Add dockerfile just for playground

### PR DESCRIPTION
**Pull request by yuvipanda**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by betatim** [comment]
Prodded travis to see if the failure is random or not. Don't really see why this should be failing.

**Comment by rgbkrk** [comment]
It looks like the build is failing on `master`, which is my fault in hastily fixing certain things for packaging so we could ship the app. I'm getting this locally on `master` now too... `O_____O`

**Comment by rgbkrk** [comment]
Hmmmm only with a fresh install, one dep must have changed that affects the flow definitions. It's bombing on all:

```
export type ...
```

declarations.

**Comment by betatim** [comment]
@yuvipanda 🔄🎸 (rebase) now that this is fixed, then we can merge this :)

Should we setup building and pushing for releases?

**Comment by rgbkrk** [comment]
We'd need all the packages it relies on to be released too. It would be nice to have a travis group that only runs on tagged releases and it would build & ship the docker images for apps that are webapps.

**Comment by rgbkrk** [comment]
Seeing if the close and reopen works, since it should be testing the merge commit rather than as is.

**Comment by betatim** [comment]
> Seeing if the close and reopen works, since it should be testing the merge commit rather than as is.

Smart!

**Comment by betatim** [comment]
🎉

**Comment by betatim** [comment]
This has been built and pushed to dockerhub at least once: https://hub.docker.com/r/yuvipanda/play.nteract.io/

**Comment by betatim** [comment]
> It would be nice to have a travis group that only runs on tagged releases

I had assumed you were  doing releases by tagging on GH and letting travis doing all the work.

**Comment by rgbkrk** [comment]
The JS package releases are pretty simple. I think things are just changing for the likely proliferation of apps built on the packages here.

**Comment by yuvipanda** [comment]
This is awesome!

Ideally, I'd love to have automated docker build + push whenever anything under here changes to something like `nteract/playground` (or `nteract/play` as you wish).

**Pull request merged**
