### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by lightsquared**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rgbkrk** [comment]
cc #3119

Thank you for updating us to contributor covenant 1.4! What I particularly like about 1.4 is the examples of behavior that create a positive environment. We likely need to give concrete examples for these to help people.

What I want to make sure we bring onto our code of conduct is our values statement of what we strive for as a project and how the code of conduct supports that.

Our vision:

> Create fantastic interactive computing experiences that allow people to collaborate with each other with ease.

Our CoC is about fostering this collaboration, interaction, and ease. It takes some recognizing that we must show empathy and understanding across various axes where we may not have the same perspectives.

Recently we got a review of our code of conduct that I'd love to make sure we incorporate (not publicly available at this moment). It's hard to get this right and make sure that we're building an inclusive environment consistent with our values. There are a few areas we need to improve upon for ourselves, since we adopt the code of conduct within a community guided by principles.

I think this is a great start and @captainsafia, @alexandercbooth, and I have some changes we'll make in a subsequent PR. Thank you very much for helping to foster a great environment.

**Review by rgbkrk — APPROVED** [review]

**Review by willingc — APPROVED** [review]
PR looks good. Thanks @lightsquared 👍 

@rgbkrk Do you want to merge this now or  wait for a more formal CoC review with the consultant recommendations?

**Review by alexandercbooth — APPROVED** [review]
Thanks for taking this on, @lightsquared!

**Comment by rgbkrk** [comment]
> Do you want to merge this now or wait for a more formal CoC review with the consultant recommendations?

This is great to merge now and we'll incorporate changes in a new PR.

**Pull request merged**
