### PR TITLE
Enable linkify in text-based outputs

### LINKED ISSUE #4479: Enable linkify in StreamText output renderer
Currently, the `StreamText` component sets the `linkify` flag to false. We should enable this by default or make it a prop that consumers of the component can pass in.

Note, that prior to enabling this, we should sanity check that our `linkify` component can sanitize data appropriately.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #4479.

### CODE REVIEW

**Comment by BenRussert** [comment]
I did a quick search to try and figure out why this was disabled in the first place. [Found this conversation](https://github.com/nteract/nteract/issues/993#issuecomment-253286167), but I don't yet follow what the issue is/was with linkify.

PR looks good other than that.

**Comment by BenRussert** [comment]
Oh, but snapshots :roll_eyes:

**Comment by captainsafia** [comment]
@BenRussert The linkify changes mentioned in that conversation are implemented [here](https://github.com/nteract/nteract/blob/master/packages/ansi-to-react/src/index.ts#L73). I believe things got shuffled around when the ansi-to-react package got moved to the monorepo.

**Review by BenRussert — APPROVED** [review]
Thanks!

**Pull request merged**
