### PR TITLE
chore(Components): Resolved all Flow errors for typed components

### PR DESCRIPTION
**Pull request by peggyrayzis**
Hey nteract team! I resolved all Flow errors for the components that were previously typed. I tried to maintain as much of the project's original style as I could, but I'm open for suggestions if you would like to make any adjustments. :) Looking fwd to your feedback!

```
❯ npm run flow

> nteract@0.0.13 flow /Users/mrayzis/projects/open-source/nteract
> flow; test $? -eq 0 -o $? -eq 2

No errors!
```

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome!

Did you mean to close this? I'm happy to review it (and be influenced if we should adjust style).

**Comment by peggyrayzis** [comment]
Yes, I just had to make a minor change to fix some linting errors. I squashed the commits & pushed again, so it should be good to go. Not sure why it's not letting me reopen!

**Comment by rgbkrk** [comment]
Whoa, that is weird... I can't click it either.

**Comment by lgeiger** [comment]
bildschirmfoto 2016-10-06 um 19 30 28

**Comment by rgbkrk** [comment]
I wonder if this is related to me locking the branches and settings down. Let me dig...

**Comment by rgbkrk** [comment]
Ah. Look at that tooltip.

To a new PR!

**Comment by peggyrayzis** [comment]
Sorry guys, I was just trying to keep my commits clean 😆 

I'll open a new one!

**Pull request closed without merging**
