### PR TITLE
Cleanup unused vars

### PR DESCRIPTION
**Pull request by lgeiger**
This is a follow up on #3419.

While most of the fixes are straight forward, in a few places I'm not sure if there are bugs present. I left TODOs in those places.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Each of those TODOs can be removed.

It looks like that `const config` (in the commuter view page) needs to be `config =`, since there's a `let config` above. I'm surprised that wasn't caught by flow or other linting.

**Comment by lgeiger** [comment]
> It looks like that const config (in the commuter view page) needs to be config =

Thanks for taking a look 👍 

> Each of those TODOs can be removed.

Also the `writable` TODO? It looks like this should be used in the content response below:

https://github.com/nteract/nteract/blob/cf6606e261900194749ceba0fea2462d6e34812e/applications/desktop/src/notebook/epics/loading.js#L51-L67

**Comment by rgbkrk** [comment]
I think we could just set `writable`, it just happens to be a bit silly since commuter doesn't have a way to write back with local mode.

**Comment by lgeiger** [comment]
> I think we could just set writable, it just happens to be a bit silly since commuter doesn't have a way to write back with local mode.

👍

**Pull request merged**
