### PR TITLE
Tech Debt: Babel + next.js edition

### PR DESCRIPTION
**Pull request by rgbkrk**
Getting babel and next.js all lined up.

Apps working 

* [x] Desktop
* [x] commuter
  * [x] dev
  * [x] prod
* [x] play
* [x] jext

### CODE REVIEW

**Comment by rgbkrk** [comment]
omg -- https://babeljs.io/docs/en/config-files#project-wide-configuration

Relevant snippet:

> These cases will primarily cause issues for users with a monorepo structure, because if you have ... (diagram of exactly our setup) ...  the config will now be entirely ignored, because it is across a package boundary.

Right now all our packages run their own `babel` in the working directory for each package
so they don't have the config. Time to figure out how this is done for babel 7.

**Comment by rgbkrk** [comment]
Ok, I haven't figured out a super slick way of handling this. For now, I can make this work for individual packages by setting the `build:lib` command to each to be:

```
"build:lib": "babel -d lib src --ignore '**/__tests__/**' --config-file ../../babel.config.js",
```

**Comment by rgbkrk** [comment]
Stuck on getting the next.js apps all synced up with this.

**Comment by rgbkrk** [comment]
```
$ npx next build
[17:15:30] Compiling client
[17:15:30] Compiling server
> Using external babel configuration
> Location: "/Users/kylek/code/src/github.com/nteract/nteract/applications/commuter/.babelrc"
[17:15:34] Compiled server in 4s
[17:15:40] Compiled client in 10s
> Failed to build
{ Error: (client) /Users/kylek/code/src/github.com/nteract/nteract/packages/directory-listing/src/components/entry.js
Module build failed (from /Users/kylek/code/src/github.com/nteract/nteract/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/kylek/code/src/github.com/nteract/nteract/packages/directory-listing/src/components/entry.js: Unexpected token, expected ";" (10:5)

   8 | import { LastSaved } from "./lastsaved";
   9 |
> 10 | type EntryProps = {
     |      ^
  11 |   children: React.Node
```

**Comment by alexandercbooth** [comment]
I _think_ this might be OK now  ¯\\_(ツ)_/¯.

🛌 💤

**Comment by rgbkrk** [comment]
Updating the list above while I try each

**Comment by rgbkrk** [comment]
Wow this is looking fit to ship!

**Comment by rgbkrk** [comment]
Heh, and I just tried play. It's... broken. Looks like it's the next redux wrapper. I had a feeling that would need some updates.

**Comment by rgbkrk** [comment]
Play is looking good now too!

**Review by alexandercbooth — APPROVED** [review]
This is rockin 🎉 Thanks for all the hard work bringing us up to date, @rgbkrk!

**Pull request merged**
