### PR TITLE
Switch to MPLv2.0

### LINKED ISSUE #76: Relicense as Mozilla Public License v2
In following with [C4.1](http://rfc.zeromq.org/spec:22), I'd like to propose that we relicense composition to [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/). 

In order to do this, I'd need a 'yay' from each contributor to relicense your contributions as MPLv2:
- [X] @rgbkrk
- [x] @kenwheeler  
- [x] @karissa 
- [x] @phfrohring 
- [x] @captainsafia 
- [x] @jdfreder 

Please let me know a yay or nay as soon as you can.

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #76

### CODE REVIEW

**Comment by rgbkrk** [comment]
ha, of course this has conflicts now

**Comment by rgbkrk** [comment]
I'll just re-open

**Comment by jdfreder** [comment]
rebase needed

**Comment by jdfreder** [comment]
ah beat me to it!

**Pull request closed without merging**
