### PR TITLE
test(epicSpecs): Add test and mocks for theme spec

### PR DESCRIPTION
**Pull request by captainsafia**
Just parking things here before my flight.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Sheesh Safia, I thought you wanted to be at 80% by today -- not 38.24%!

**Comment by captainsafia** [comment]
> Sheesh Safia, I thought you wanted to be at 80% by today -- not 38.24%!

Hahaha! Didn't realize this until I was up in the air and I was totally mortified. Weird that CodeCov isn't retriggering though because my run of `npm run coverage` is showing a slight increase.

**Comment by rgbkrk** [comment]
Yikes! I didn't want to freak you out. I was joking about codecov being odd.

**Comment by captainsafia** [comment]
Bleh! Go ahead and merge this. I'm trying to take a stab at testing some of the epics but I think I should leave that experimentation for another PR.

Also, yay, new PR/commit convention looks great!

**Comment by rgbkrk** [comment]
Might as well rebate out the executeSpec if it's going to show a revert. It's not like we've already merged this.

**Comment by captainsafia** [comment]
> Might as well rebate out the executeSpec if it's going to show a revert. It's not like we've already merged this.

Done! 👍

**Comment by jdetle** [comment]
👍

**Pull request merged**
