### PR TITLE
pass NotebookMenu in as child when a notebook file

### LINKED ISSUE #4135: Notebook menu is shown on editor page
screen shot 2019-01-28 at 4 38 15 pm

### PR DESCRIPTION
**Pull request by rgbkrk**
closes #4135

### CODE REVIEW

**Comment by stormpython** [comment]
I tested this branch against opening up a `txt` file and I still see the toolbar menu.

screen shot 2019-01-30 at 1 10 25 pm

**Comment by rgbkrk** [comment]
When you get a chance can you check this one out again? With the updated typescript & webpack settings on `master` it should be coming up properly.

**Comment by stormpython** [comment]
Taking a look now.

**Review by stormpython — APPROVED** [review]
LGTM!

**Pull request merged**
