### PR TITLE
Fix mythic-configuration: do not import node packages by default

### PR DESCRIPTION
**Pull request by erem-stripe**
Fixes issue #5445
https://github.com/nteract/nteract/issues/5445

- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [X] I have updated the changelogs/current_changelog.md file with some information about the change that I am making the appropriate file.
- [X] I have validated or unit-tested the changes that I have made.
- [ ] I have run through the TEST_PLAN.md to ensure that my change does not break anything else.

### CODE REVIEW

**Comment by erem-stripe** [comment]
Converting this to draft bc it turns out that, in the webpack setting, our nice little try/catch only tries and doesn't catch

**Comment by erem-stripe** [comment]
Ok unit tests pass and I've verified that this works for my use-case. It's a little janky with the require-fu and I'm open to feedback on that.

Regarding the test plan, I'm getting out-of-memory exceptions trying to get `dist:all` to work but I'm hoping the reviewer can help me by running through the test plan?

**Comment by erem-stripe** [comment]
Also, I noticed the nteract-web doesn't blow up in this way which had me going crazy! Turns out it's because of [this next.js configuration](https://github.com/nteract/nteract/blob/main/applications/web/next.config.js#L8-L13)

I think this PR (or a less janky version of it) is still worth it because not every web-based consumer of the UI libraries should have to remember to vigilantly stub out `fs` just to load a configuration package!

**Review by captainsafia — APPROVED** [review]
Thanks for the code change and the test!

I did a similar fix over in https://github.com/nteract/nteract/pull/5390 but missed that we had another Node-specific dependency in the platform-agnostic dependencies.

**Pull request merged**
