### PR TITLE
Use ts-loader in styleguidist config

### PR DESCRIPTION
**Pull request by captainsafia**
Still need to fix the `Host` and `Kernel` component rendering.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looking better and better. I wonder if we need a custom tsconfig for the styleguide.

**Comment by rgbkrk** [comment]
Hey it's passing!

**Comment by rgbkrk** [comment]
Did you mean to leave this in WIP?

**Comment by captainsafia** [comment]
I was gonna try to figure out why the Provider and Context types in the host-cache package weren’t being transpired but I guess that can be addressed later.

**Pull request merged**
