### PR TITLE
chore(deps): Bump versions.

### PR DESCRIPTION
**Pull request by jdetle**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [x] My PR title and commit messages are in [conventional-changelog-standard](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md#how-should-i-write-my-commit-messages-and-pr-titles) format.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Heh, the S3 outage means we can't download Electron. ¯\\\_(ツ)\_/¯

**Comment by jdetle** [comment]
The world is on fire right now.

**Comment by rgbkrk** [comment]
Rekicked your appveyor build, we're probably in a long backlog for Travis.

**Comment by rgbkrk** [comment]
I'm letting appveyor be the source of truth on this since you've tested this locally. I'll be closing greenkeeper's PRs too.

**Pull request merged**
