### PR TITLE
Move to the new updateOptions API to dynamically update editor options

### PR DESCRIPTION
**Pull request by vivek1729**
As we bumped up monaco editor to the latest version, we transition to the new [`updateOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#updateoptions) API to dynamically update some editor constructor options.

- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [X] I have updated the changelogs/current_changelog.md file with some information about the change that I am making the appropriate file.
- [X] I have validated or unit-tested the changes that I have made.
- [X] I have run through the TEST_PLAN.md to ensure that my change does not break anything else.

### CODE REVIEW

**Comment by captainsafia** [comment]
@vivek1729 What's the benefit of this API over the previous one?

**Comment by vivek1729** [comment]
@captainsafia, the older version of monaco editor did not have a generic API to update editor options dynamically. We therefore had to rely on specific getters/setters for individual props like `theme`. This completely simplifies the update process of editor props for re-renders. So instead of using specific methods like `setTheme`, `setPosition`, `setValue` etc, we can just move to a single `updateOptions` call for a set of configuration props.

**Comment by captainsafia** [comment]
@vivek1729 Got it. Should we be replacing instances of `setValue` and other properties with this then?

**Comment by vivek1729** [comment]
That's a good point @captainsafia. On digging deeper, it seems like the [`updateOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#updateoptions) API accepts a subset of properties ([IEditorOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html) and [IGlobalEditorOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.iglobaleditoroptions.html)) that we pass in as [constructor options](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html) when creating the editor. So the `value` property is a constructor option that has a dedicated setter namely `setValue`. Same goes for the position prop. So, I think we can continue using the `setValue` method and move to `updateOptions` for configuration properties like `theme`, `readOnly` etc highlighted in the two interfaces I linked earlier.

**Review by captainsafia — APPROVED** [review]
It looks like we're already using these for the two properties we care about.

**Comment by vivek1729** [comment]
Thanks @captainsafia. Ok to merge now?

**Pull request merged**
