### PR TITLE
WIP: Replace Leaflet with Mapbox GL

### PR DESCRIPTION
**Pull request by kitten**
Still a work in progress, but it works fine and is nice and smooth. I wish the gif wouldn't just be in 4 FPS...

http://recordit.co/BzFrDY3cRM
- [x] Switch Leaflet out for Mapbox GL
- [ ] Implement hovers and popups
- [ ] Better styling
- [ ] Handle properties smartly
- [ ] Automatically fit center and zoom to bounds of all points

### CODE REVIEW

**Comment by rgbkrk** [comment]
Whoa, fetching your remote now.

**Comment by kitten** [comment]
@rgbkrk Don't expect too much. I had to implement a GeoJSONLayer on the React Mapbox GL project, but I didn't do the rest of the work yet :P

**Comment by rgbkrk** [comment]
Are you planning on coming back to this one or should we close it for now?

**Comment by rgbkrk** [comment]
Still going after this or should we close it?

**Comment by rgbkrk** [comment]
I just noticed I made the same comment 30 days ago so I'll go ahead and close this. Feel free to come back to it any time @philpl. Thanks!

**Pull request closed without merging**
