### PR TITLE
Depend on official plotly bundle

### LINKED ISSUE #4463: Plotly dependency
Hello,

I work for Plotly and so we often get issues reported to us that are related to users of nteract or users of downstream systems, such as VSCode, that use nteract code under the hood. Much of the time, these issues are due to the version of Plotly.js that is being used. Digging a little bit, it looks like in this repo we depend on `@nteract/plotly`: https://github.com/nteract/nteract/blob/master/packages/transform-plotly/package.json but it's not super-clear why... that package basically just repackages the distribution bundle of plotly.js without modification: https://github.com/nteract/minimal-plotly/blob/master/package.json except that it trails our release cycle whenever it's not pushed up to NPM (e.g. https://github.com/nteract/minimal-plotly/issues/18)

Would it be possible/what would be the downside of having `transform-plotly` depend directly upon the official `plotly` package in NPM instead of this intermediate package?

Regards,
Nicolas Kruchten
VP Product at Plotly

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Closes #4463 cc @captainsafia 

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by captainsafia** [comment]
@nicolaskruchten Some updates will also need to be made to the `index.tsx` file within this package.

**Comment by jameskoch** [comment]
@nicolaskruchten if you need any help on this hop on over to https://nteract.slack.com. I'd love to see this land!

**Comment by nicolaskruchten** [comment]
@jameskoch thanks for the offer! Shouldn't be too hard :)

**Comment by captainsafia** [comment]
Hello @nicolaskruchten! Any updates on this? Would be great to see this go in soon!

**Comment by nicolaskruchten** [comment]
Ah yes, sorry about disappearing there.. Been under a rock working on the Plotly.py v4 release which happened today. I should be able to sort this out by the end of the week :)

Thanks for the nudge!

**Comment by captainsafia** [comment]
No problem. @nicolaskruchten. Best of luck with the v4 release!

**Comment by captainsafia** [comment]
@justvaldes completed this in https://github.com/nteract/nteract/pull/4550 so I will close this PR now.

I'll follow-up and deprecate the @nteract/plotly package.

**Comment by nicolaskruchten** [comment]
OK, thanks! Sorry I wasn't able to carry the ball all the way over the line, and thanks @justvaldes!

**Pull request closed without merging**
