### PR TITLE
Correct errors for JSON in styleguidist

### PR DESCRIPTION
**Pull request by willingc**
Addresses #3497 

- Add @component comment [Ref](https://react-styleguidist.js.org/docs/thirdparties.html#styled-components)

### CODE REVIEW

**Comment by lgeiger** [comment]
Well I think I know whats going on here:
It looks like the `JSON` component conflicts with the global `JSON` variable in the bundle.

I'm 99% confident that renaming our `JSON` component to `Json` will fix this problem.

**Comment by rgbkrk** [comment]
Ah yeah the old way I got around this was calling the component `JSONDisplay` or something like that.

**Comment by willingc** [comment]
Thanks @lgeiger and @rgbkrk. I've renamed to `Json` to avoid the global conflict and all seems well now.

**Comment by rgbkrk** [comment]
Thank you so much for figuring this one out, I was stumped.

**Comment by rgbkrk** [comment]
Guess we can deploy the components site after the next release. 😄

**Comment by lgeiger** [comment]
> Guess we can deploy the components site after the next release.

Awesome! Can we automate this somehow, to deploy with now automatically when there's a new tag?

**Comment by rgbkrk** [comment]
I tried that a bit ago and the electron deps and other gunk in the monorepo made it practically impossible.

**Comment by lgeiger** [comment]
> I tried that a bit ago and the electron deps and other gunk in the monorepo made it practically impossible.

Can't we do this on circle CI since we already build the static assets there?

**Comment by rgbkrk** [comment]
Yeah! We can do it with a separate Circle CI process -- that's actually why I did the artifact publishing. We just can't use zeit's integration to do it. If we wanted to use zeit directly, we'd have to make another repo for it. 😬

**Comment by rgbkrk** [comment]
For now I've published the packages and am now publishing the site.

**Comment by rgbkrk** [comment]
Looks good, I'll promote this: https://nteract-components-dwhmkfttcy.now.sh/#json

**Comment by rgbkrk** [comment]
https://components.nteract.io/ is now live

**Comment by willingc** [comment]
Thanks @lgeiger and @rgbkrk. I'm going to open an issue in the docs repo and/or project to keep visibility for auto deploy of docs on the radar (even if it's not elegant now).

cc/ @captainsafia

**Pull request merged**
