### PR TITLE
Another merger

### LINKED ISSUE #1794: Move more base modules into monorepo
All of these depend on `jupyter-paths` which means we end up going through a massive "migrate these packages" run through:

* [x] `enchannel-zmq-backend`
* [ ] `spawnteract`
* [ ] `jupyter-paths`
* [ ] `kernelspecs`

Let's just bring them all together.

### PR DESCRIPTION
**Pull request by rgbkrk**
This will close #1794. It is slightly insane as I've carried all the history over (the how is documented in #1794). I should _probably_ delete all the release commits (e.g. `0.0.1`), which are usually either me, @captainsafia, @lgeiger, or @jdfreder. It's kind of funny seeing these are they're some of the original commits from way back when this all started. :smile: Steps to do this:

In the original package:

```
git checkout -b move-to-monorepo
mkdir -p packages/NAME
git mv !(packages) packages/NAME/
git mv .SOMEFILE packages/NAME # Catch the dotfiles

# Double check things first
git commit -am "preparing NAME for move to monorepo"
```

In the monorepo (on branch "another-merger")

```
git remote add tmpNAME /Path/To/NAME
git fetch tmpNAME
git merge tmpNAME/move-to-monorepo --allow-unrelated-histories
# Make commit message be:
# chore: merge X into monorepo
```

If this looks clean, I'll finish the rest of the list from #1794.

Update: UNCLEAN UNCLEAN

### CODE REVIEW

**Comment by rgbkrk** [comment]
> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

Here I thought I was doing this properly. Time to see what's up.

**Comment by rgbkrk** [comment]
Oh lordy, the rebase is hell and maybe impossible.

**Comment by rgbkrk** [comment]
From http://www.gelato.unsw.edu.au/archives/git/0506/5511.html

> Now, I don't know how often this ends up being actually used in practice, 
> but at least in theory this is a totally generic thing, where you create a 
> "union" of two git trees. I did the union merge manually, but in theory it 
> should be easy to automate, with simply something like

```
	git fetch <project-to-union-merge>
	GIT_INDEX_FILE=.git/tmp-index git-read-tree FETCH_HEAD
	GIT_INDEX_FILE=.git/tmp-index git-checkout-cache -a -u
	git-update-cache --add -- (GIT_INDEX_FILE=.git/tmp-index git-ls-files)
	cp .git/FETCH_HEAD .git/MERGE_HEAD
	git commit
```

> (this is not exactly how I did it, but that's just because I'd never done
> this before so **I didn't think it through and I had some stupid extra steps
> in between that were unnecessary**).
> 
> ...
> Linus Torvalds

Um. Uh. I don't think I should try this with the vote of confidence coming from the originator of git.

😨

**Comment by rgbkrk** [comment]
> Um. Uh. I don't think I should try this with the vote of confidence coming from the originator of git.

Tried this, `git-*-cache` (and `git checkout-cache` etc.) are not commands on my system.

**Comment by rgbkrk** [comment]
Heh, I tried using an orphaned branch. That was a terrible idea.

screen shot 2017-07-27 at 5 18 39 pm

**Comment by jdfreder** [comment]
oof

**Comment by rgbkrk** [comment]
This is everything from `spawnteract` and `enchannel-zmq-backend`.

**Comment by rgbkrk** [comment]
Closing in favor of #1807.

**Pull request closed without merging**
