### PR TITLE
only run updateAndNotify on windows + macOS

### PR DESCRIPTION
**Pull request by rgbkrk**
Fixing up

image

https://twitter.com/chendaniely/status/915402770655608834

### CODE REVIEW

**Review by chendaniely — APPROVED** [review]
I've confirmed that this PR fixes the issue and runs on my arch machine (:

**Comment by rgbkrk** [comment]
Alright, I'll get this shipped then. It will be the first version that the macOS and Windows versions get an auto-update for amusingly. 😉

**Comment by chendaniely** [comment]
does it support marquees?

**Comment by rgbkrk** [comment]
Full blown enterprise level `<marquee>` support coming your way soon!

**Comment by rgbkrk** [comment]
(build running...)

**Comment by lgeiger** [comment]
I don't know why this is necessary. `updateAndNotify` should just be a [noop on linux](https://github.com/electron-userland/electron-builder/blob/c14a19300e426e6d99d20fdabb27ccbac529bb19/packages/electron-updater/src/AppUpdater.ts#L175).

I'm wondering if it's because it's build on mac instead of on Linux.

**Comment by rgbkrk** [comment]
> I'm wondering if it's because it's build on mac instead of on Linux.

Yeah that could be. I would hope webpack doesn't take a selective path while building the JS with an electron target.

**Pull request merged**
