### PR TITLE
Handle opening files directly from native OS

### PR DESCRIPTION
**Pull request by rgbkrk**
Relying on `open-file` event. Couldn't be any simpler.

You'll need a built copy of nteract to use this (with our new dist hooks).

### CODE REVIEW

**Comment by captainsafia** [comment]
This brings tears to my eyes! :')

**Comment by jdfreder** [comment]
This is great!!!

**Comment by rgbkrk** [comment]
I should have recorded a GIF with this, I'll do that later when I'm on one monitor.

**Comment by rgbkrk** [comment]
Not sure how one registers openers, we should figure that out too...

**Comment by betatim** [comment]
Ah, this answer my naive question of: where did you hide the magic of informing OSX that `nteract` is the new game in town for `.ipynb`.

**Comment by jdfreder** [comment]
> Not sure how one registers openers, we should figure that out too...

On Windows that's usually done by the installer, we could put it off for the installer to do on OSX too.

**Comment by Carreau** [comment]
Not sure what that does. Double click on `.ipynb` still open MacVim for me.

**Comment by jdfreder** [comment]
> Not sure what that does. Double click on .ipynb still open MacVim for me.

The double click require the filetype to be associated with the app, which nteract doesn't do yet...

**Pull request merged**
