### PR TITLE
chore(docs): Provide ⬆️ "verb"

### PR DESCRIPTION
**Pull request by rgbkrk**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Fun fact: PowerShell does not like emoji branch names.

**Comment by lgeiger** [comment]
Sorry for not complying with the contributing standard. It was late yesterday 😄 

@rgbkrk We can still use ⬆️ in the commit message.

**Comment by rgbkrk** [comment]
That's ok, it's a new standard for us. I'm on the fence about whether I care too deeply about the "conventional change log" commit message format. Commit messages can always be changed before merge, feel free to do what makes you productive and happy - we can always change things later.

**Pull request closed without merging**
