### PR TITLE
Fix webpack config I broke in rebase

### LINKED ISSUE #5222: `yarn build:desktop:watch` broken
Commit "Fix WebPack" in PR #5115 actually fixed webpack for webpack.prod.js but broke it for webpack.dev.js (Now there's an error when running `yarn build:desktop:watch`). The "Fix WebPack" change should be reverted for webpack.dev.js.

In webpack.prod.js, the import is `const merge = require("webpack-merge");`, so it makes sense to use `merge.merge()`.

But in webpack.dev.js, the import is `const { merge } = require("webpack-merge");`, so only `merge()` should be used directly.

_Originally posted by @jruales in https://github.com/nteract/nteract/pull/5115#issuecomment-663809525_

### PR DESCRIPTION
**Pull request by CrystallineCat**
Fixes #5222.

### CODE REVIEW

**Comment by CrystallineCat** [comment]
So, this is exactly the same change as #5223, but the build failed there, and is green here... I'm going to leave both PRs up, hoping someone will help me figure out the non-determinism with circleci with respect to installing electron... :scream_cat:

**Comment by willingc** [comment]
@CrystallineCat I reran the CircleCI tests on #5223. It looks like the earlier failure was a spurious CircleCI failure. It's passing now on #5223. I don't see anything that should prevent merging #5223 or this PR. Thanks for looking into it. Leaving for you to merge your favorite :wink:

**Review by willingc — APPROVED** [review]

**Review by willingc — APPROVED** [review]

**Comment by CrystallineCat** [comment]
@willingc Thank you! :smile_cat: This isn't the first time I ran into this issue with circleci; I had intermittent failures on the electron v9 branch, too. I thought it was caused by not having a prebuilt version available, but it looks like this isn't the cause. I didn't know about rerunning the tests; I'll look into that in the future. :cat:

**Comment by willingc** [comment]
@CrystallineCat All the CI systems have some intermittent failures. I suspect due to latency or momentary network issues. There's a little restart icon in CircleCI (upper right). If you don't see it, we can look at bumping privileges or just ping me/Safia to restart. Thanks :D

**Pull request merged**
