### PR TITLE
produce less errors and warnings from React DOM

### PR DESCRIPTION
**Pull request by rgbkrk**
Working on docs while doing the MathJax component and saw these areas for cleaning up. 😄

### CODE REVIEW

**Review by alexandercbooth — APPROVED** [review]
Good finds, thanks @rgbkrk!

**Comment by alexandercbooth** [comment]
We don't have `now` deploying a preview of the styleguidist components on PRs here, is that something we might want to consider? 

I wonder if it can be configured to PR a preview only when files deployed by it are changed (like our components) 🤔

**Comment by rgbkrk** [comment]
I tried to get our components docs auto-deploying with this repo, the monorepo proved to be too heavyweight.

**Comment by alexandercbooth** [comment]
Oh OK gotcha 👍

**Pull request merged**
