### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by rgbkrk**
An almost complete version of #1414.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Something I noticed while doing repeated iterations of `prettier 'src/**/*.js'` - the output is not always a stable state. I eventually got it to one here.

One thing to be really careful of / look over in the changes here - the comments sometimes get mangled or end up fully deleted. We should comb through to see if they're all right.

**Comment by rgbkrk** [comment]
On a separate note, I thought we would lose semi-colons with prettier. Drat!

P.S. We could totally do standard js instead, hint hint wink wink.

**Comment by peggyrayzis** [comment]
I was hoping the output would be...prettier? 🙈 I don't like how strict the max line length is and I'm not a fan of double quotes or semicolons.

Standard is looking like a better option, which makes me sad because I really wanted to love Prettier.

**Comment by rgbkrk** [comment]
Closing, not moving to prettier (for now). In other news, I've enabled my eslint plugin in Atom to auto-fix.

**Pull request closed without merging**
