### PR TITLE
Update cellStatuses on splitCell

### PR DESCRIPTION
**Pull request by captainsafia**
@jdetle — This fixes the split cell bug that went through. I ended up separating it out from the other PR that I was working on.

### CODE REVIEW

**Comment by jdetle** [comment]
@captainsafia I just checked this out and unfortunately split immediately followed by delete cell still breaks things. 

```
Warning: Failed prop type: Required prop `cellStatus` was not specified in `CodeCell`.
    in CodeCell (created by Cell)
    in Cell (created by CellContextMenuLayer)
    in div (created by CellContextMenuLayer)
    in CellContextMenuLayer (created by DraggableCell)
    in div (created by DraggableCell)
    in div (created by DraggableCell)
    in DraggableCell (created by DropTarget(DraggableCell))
    in DropTarget(DraggableCell) (created by DragSource(DropTarget(DraggableCell)))
    in DragSource(DropTarget(DraggableCell)) (created by Notebook)
    in div (created by Notebook)warning @ /home/jdetlefs/github/nteract/node_modules/fbjs/lib/warning.js:44checkReactTypeSpec @ /home/jdetlefs/github/nteract/node_modules/react/lib/checkReactTypeSpec.js:67validatePropTypes @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactElementValidator.js:153ReactElementValidator.createElement @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactElementValidator.js:187render @ /home/jdetlefs/github/nteract/build/notebook/components/cell/cell.js:157ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:785ReactCompositeComponentMixin._renderValidatedComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:811ReactCompositeComponentMixin.performInitialMount @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:353ReactCompositeComponentMixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:241ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactMultiChild.Mixin.mountChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:242ReactDOMComponent.Mixin._createInitialChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:704ReactDOMComponent.Mixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:529ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactCompositeComponentMixin.performInitialMount @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:367ReactCompositeComponentMixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:241ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactMultiChild.Mixin.mountChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:242ReactDOMComponent.Mixin._createInitialChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:704ReactDOMComponent.Mixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:529ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactMultiChild.Mixin.mountChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:242ReactDOMComponent.Mixin._createInitialChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:704ReactDOMComponent.Mixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:529ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactCompositeComponentMixin.performInitialMount @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:367ReactCompositeComponentMixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:241ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactCompositeComponentMixin.performInitialMount @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:367ReactCompositeComponentMixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:241ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactCompositeComponentMixin.performInitialMount @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:367ReactCompositeComponentMixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:241ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactMultiChild.Mixin.mountChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:242ReactDOMComponent.Mixin._createInitialChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:704ReactDOMComponent.Mixin.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:529ReactReconciler.mountComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:49ReactMultiChild.Mixin._mountChildAtIndex @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:427ReactMultiChild.Mixin._updateChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:343ReactMultiChild.Mixin.updateChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactMultiChild.js:303ReactDOMComponent.Mixin._updateDOMChildren @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:938ReactDOMComponent.Mixin.updateComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:767ReactDOMComponent.Mixin.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDOMComponent.js:723ReactReconciler.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:131ReactCompositeComponentMixin._updateRenderedComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:737ReactCompositeComponentMixin._performComponentUpdate @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:715ReactCompositeComponentMixin.updateComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:634ReactCompositeComponentMixin.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:534ReactReconciler.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:131ReactCompositeComponentMixin._updateRenderedComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:737ReactCompositeComponentMixin._performComponentUpdate @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:715ReactCompositeComponentMixin.updateComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:634ReactCompositeComponentMixin.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:534ReactReconciler.receiveComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:131ReactCompositeComponentMixin._updateRenderedComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:737ReactCompositeComponentMixin._performComponentUpdate @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:715ReactCompositeComponentMixin.updateComponent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:634ReactCompositeComponentMixin.performUpdateIfNecessary @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactCompositeComponent.js:548ReactReconciler.performUpdateIfNecessary @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactReconciler.js:165runBatchedUpdates @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactUpdates.js:151Mixin.perform @ /home/jdetlefs/github/nteract/node_modules/react/lib/Transaction.js:138Mixin.perform @ /home/jdetlefs/github/nteract/node_modules/react/lib/Transaction.js:138_assign.perform @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactUpdates.js:90flushBatchedUpdates @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactUpdates.js:173Mixin.closeAll @ /home/jdetlefs/github/nteract/node_modules/react/lib/Transaction.js:204Mixin.perform @ /home/jdetlefs/github/nteract/node_modules/react/lib/Transaction.js:151ReactDefaultBatchingStrategy.batchedUpdates @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63batchedUpdates @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactUpdates.js:98ReactEventListener.dispatchEvent @ /home/jdetlefs/github/nteract/node_modules/react/lib/ReactEventListener.js:150
2/home/jdetlefs/github/nteract/build/notebook/components/cell/code-cell.js:51 Uncaught TypeError: Cannot read property 'get' of undefined

```

**Comment by captainsafia** [comment]
What?!!? Crazy. Somehow this didn't happen when I tested before submitting the PR but I just did it now and it broke. Fixing it now....

**Comment by captainsafia** [comment]
Wow. What a silly bug. Fixed now.

**Comment by jdetle** [comment]
Success!

**Pull request merged**
