### PR TITLE
Depend on official plotly bundle

### PR DESCRIPTION
**Pull request by justvaldes**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

The version of plotly referenced in the plotly-transform package lagged the official version. Now that plotly publishes a version of its minified js to npm it made sense to change the dependency to the official plotly package. 

This is simply completing Nicolas K's PR 4464

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]
Awesome! Thanks so much for finishing this work off.

**Comment by nicolaskruchten** [comment]
🎉 This is great!

@captainsafia in order for this change to ripple through the ecosystem, we'll need a new version of `@nteract/transform-plotly` up on NPM, right? Say 5.0.1 ?

**Comment by captainsafia** [comment]
@nicolaskruchten Yes. For this to change to ripple through, we'll need to do a package release. This typical happens on Mondays so it'll roll out on the 9th. Does that work for you?

**Comment by nicolaskruchten** [comment]
Yes, that's great, thanks very much :)

**Comment by nicolaskruchten** [comment]
FYI what this will enable, as far as I can tell, is for me to now be able to routinely submit PRs into "downstream" files like https://github.com/microsoft/vscode-python/blob/master/package.json#L2564-L2568 that point to the latest version of `plotly.js-dist` bundle (which will be accepted by `@nteract/transform-plotly` due to the `^` in the dependency entry) without anyone on the nteract team having to do anything on a regular basis any more!

**Pull request merged**
