### PR TITLE
Remove blueprint styled-component from data-explorer

### PR DESCRIPTION
**Pull request by BenRussert**
Based on the discussion at today's weekly meeting, and #4019 

This would require docs to explain how to load blueprint stylesheets with a css loader (or other method) [Here is an example using the component from a project bootstrapped with create-react-app](https://github.com/BenRussert/data-explorer-web/blob/fe0ec69024c982f50bba31fd0b2f820d8129037b/src/App.tsx#L5-L9)

Here are some more [docs on this from blueprint](https://blueprintjs.com/docs/#blueprint.quick-start)

### CODE REVIEW

**Comment by rgbkrk** [comment]
I suppose we just have to stick these into the very root of both jupyter extension and desktop next (or use a webpack css loader like you said).

**Comment by BenRussert** [comment]
I think that's worth a shot. I think it would make the dx component more flexible if we uncouple the style component and provide as a separate option. We could outline potential style solutions in the docs.

**Comment by rgbkrk** [comment]
That's cool with me. Would you want to make a follow up PR that provides the style for data explorer to use to both jupyter extension and desktop?

**Comment by BenRussert** [comment]
> Would you want to make a follow up PR that provides the style for data explorer to use to both jupyter extension and desktop?

Should be able to do this week, hopefully tonight.

**Comment by rgbkrk** [comment]
Ok I'm happy to do the follow on work for this to move the blueprint styles into the right spot for the apps. We just won't publish until we've got the README and other bits situated for #4019. Sound like a plan?

**Comment by rgbkrk** [comment]
Alright, I've got a branch in the works that I'll submit in a few minutes here after testing how it goes.

**Comment by rgbkrk** [comment]
Yeeha. Same problem for codemirror styles.

I can't believe how much better `styled-jsx` was at handling injected global styles.

**Comment by rgbkrk** [comment]
😢 Components with global style we now have to extract out: 

* All global codemirror styles for the editor
* `connected-components`' menu
* `data-explorer`'s `react-table`
* `presentational-components`' `header-editor`*  
* `transform-geojson`'s `leafletCSS`

We can export these from the packages, but people _should_ move them up to the app level. I'll open my PR now.

**Comment by rgbkrk** [comment]
I probably need to update the way css variables for themes are handled as well.

**Comment by BenRussert** [comment]
> I probably need to update the way css variables for themes are handled as well.

The variables used in dx rely on declarations from other nteract components. That's why I loaded the `nteract.css` file in the web app above.


> I can't believe how much better styled-jsx was at handling injected global styles.

Agreed. We should probably open an issue if there isn't one.

**Comment by rgbkrk** [comment]
https://github.com/nteract/nteract/pull/4093 is the first pass, handling both data explorer and the editor. I'll open some issues after lunch.

**Pull request merged**
