### PR TITLE
[WIP] upgrade to rxjs 7, redux observable 2.0.0-rc.2

### PR DESCRIPTION
**Pull request by rgbkrk**
Rehash of #5526, this time with an upgrade to redux-observable as well.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Automatic branch closures when commits become empty is such a funny GitHub quirk.

**Comment by rgbkrk** [comment]
Looks like this webpack aliasing needs a fixup:

image

**Comment by rgbkrk** [comment]
One weird thing i’m noticing while updating this is that the `yarn.lock` includes packages from within the monorepo, like `@nteract/epics`. Is that a known artifact?

**Comment by rgbkrk** [comment]
Based on the build, it looks like typescript needs an upgrade in order to upgrade rxjs.

On a migration note, here's an old blog post about what's changing in RxJS 7: https://labs.thisdot.co/blog/rxjs-7-and-beyond-what-to-expect-and-prepare-for

**Comment by rgbkrk** [comment]
Breaking changes guide: https://rxjs.dev/deprecations/breaking-changes

**Comment by rgbkrk** [comment]
Ooooook we're not getting this package upgraded until we upgrade typescript. After that, it looks like we have to set a lot of generics that we weren't setting previously.

```
packages/rx-jupyter/src/contents.ts:101:15 - error TS2314: Generic type 'AjaxResponse<T>' requires 1 type argument(s).

101 ): Observable<AjaxResponse> {
                  ~~~~~~~~~~~~

```

**Comment by rgbkrk** [comment]
I'm going to create a separate PR for upgrading typescript to see if that's a neatly isolated set of changes.

**Comment by rgbkrk** [comment]
This will now be on hold until #5564 is merged.

**Comment by captainsafia** [comment]
Heads up that automatic releases are now enabled on the repo (see #5568 for more info). To support automated releases, please make sure that the commits in this PR adhere to the conventional commit format (see https://www.conventionalcommits.org/en/v1.0.0/). Once this PR is merged, a release will be triggered for the modified packages based on the commit message.

**Comment by rgbkrk** [comment]
Closing until we are able to upgrade typescript.

**Pull request closed without merging**
