### PR TITLE
New Code Cell Shortcut

### PR DESCRIPTION
**Pull request by jdetle**
Creating new shortcuts is easy thanks to #683

### CODE REVIEW

**Comment by rgbkrk** [comment]
You got that right!

Considering we have to support the shortcuts we choose in the long run, what's the reasoning for this key set?

**Comment by jdetle** [comment]
I think `command+shift+char` should imply that you are doing something to the cell, while `command+char` should be reserved for contents of the cell.

**Comment by rgbkrk** [comment]
It just now occurred to me this is the same keybinding as incognito mode in Chrome.

**Comment by jdetle** [comment]
That decision was entirely subconscious

**Comment by rgbkrk** [comment]
I'm calling cmd-shift-p for default publish, leaving normal cmd-p for printing.

**Pull request merged**
