### PR TITLE
chore: switch to npm@5, test node@8

### PR DESCRIPTION
**Pull request by rgbkrk**
Test across the [current long term stable (LTS) and the next LTS of node.js](https://github.com/nodejs/LTS).

### CODE REVIEW

**Comment by rgbkrk** [comment]
After this next one passes, we're set and ready for npm5+ (while still supporting npm4).

**Comment by lgeiger** [comment]
Looks like we run into https://github.com/lerna/lerna/issues/856 with npm 5.

**Comment by rgbkrk** [comment]
> Looks like we run into lerna/lerna#856 with npm 5.

ohhhhhhhhh

**Comment by rgbkrk** [comment]
Definitely going to rebase this one to squish down the changes after its working.

**Comment by rgbkrk** [comment]
Cool now Travis is passing and appveyor is failing. 
¯\\\_(ツ)\_/¯

**Comment by rgbkrk** [comment]
Fixed up some pieces, rebased. Time to see how this fairs across 6 and 8.

**Comment by rgbkrk** [comment]
There's an issue with [`fcopy-pre-bundled`](https://www.npmjs.com/package/fcopy-pre-bundled)'s latest release on node 6 it seems.

**Comment by rgbkrk** [comment]
xref: https://github.com/electron-userland/electron-builder/issues/1651

**Comment by rgbkrk** [comment]
Woo, everything passes!

**Comment by rgbkrk** [comment]
Closing in favor of #1738.

**Pull request closed without merging**
