### PR TITLE
[WIP] Prevent output from hijacking scroll

### PR DESCRIPTION
**Pull request by aaronraff**
This PR is not completely finished, just wanted to get some thoughts on this. I changed the output div so that the user must click on it before it can be scrolled. This way, you won't accidentally scroll on an output box while trying to scroll through your notebook. I'm also looking at adding a shortcut for this feature as well.  

outputscrolldemo  

This is what I currently have, any suggestions?

### CODE REVIEW

**Comment by aaronraff** [comment]
This is in response to #1927 by the way.

**Comment by rgbkrk** [comment]
Behavior wise this looks great! We do have a focused prop for the editor and cell, nothing about tracking output focus state. I'm looking at this from my phone so I can't tell if any of that logic is useful to incorporate from here.

When I get a free chance I would love to take this for a spin.

Couple questions I have for the future:

* Could we make outputs scroll to the bottom automatically as new outputs come in, provided that the user isn't actively scrolling on it?
* Would it look good if we showed something visual for when the outputs are focused or unfocused (yet larger than the minimum)?

**Comment by aaronraff** [comment]
I saw that there was a prop for focused cell and editor so I was thinking maybe I should create a prop to track output focus as well. As you said, I'm not sure if that would be something useful in the future or not. As far as your questions, I will look into them and see what I can come up with!

**Comment by rgbkrk** [comment]
Ok, cool. By the way, it would be great if your GIF had some more cells to drive home the scrolling a bit more. It's usually a notebook somewhere in the middle of the document with large outputs that "hijacks the scrolling".

**Comment by rgbkrk** [comment]
You'll need to rebase if you go after this again, though you'll probably want to start again from the current components. Closing for now, feel free to re-open or start a new PR. Thanks @aaronraff!

**Pull request closed without merging**
