### PR TITLE
[WIP] Add dropdown-menu component docs

### PR DESCRIPTION
**Pull request by willingc**
A rough pass at adding DropdownMenu components to docs.

### CODE REVIEW

**Comment by rgbkrk** [comment]
It looks like some imports need to be re-arranged, possibly just in tests:

```
 FAIL  packages/dropdown-menu/__tests__/index-spec.js
  ● Test suite failed to run

    Cannot find module '@nteract/dropdown-menu' from 'index.js'

      12 | import { DropdownTrigger } from "@nteract/dropdown-trigger";
      13 | import { DropdownContent } from "@nteract/dropdown-content";
    > 14 | 
         | ^
      15 | export { DropdownMenu, DropdownTrigger, DropdownContent };
```

To get this across the finish line, I'm going to see if I can fix it locally and push up some changes. Thank you for joining me on this React documentation adventure!

**Comment by willingc** [comment]
Ooh...fancy. Off today and tomorrow but will check back on stuff :sunny:

**Comment by rgbkrk** [comment]
Oops, I broke the styling within the main app while trying to make this work well inside of our docs. Definitely a WIP here. I'll see how far I get tomorrow. 😄 

Thanks Carol!

**Comment by rgbkrk** [comment]
This _might_ be in a better state for now, given that it's migrated over to TS and the components site is in a really good state. What do you think @captainsafia? I know this would probably need a rebase that would probably be more than its worth, compared to re-doing it.

**Comment by captainsafia** [comment]
Yeah. At this point it might be best to close this and copy over the contents of the documentation markdown file into a new PR off master.

**Pull request closed without merging**
