### PR TITLE
chore(pkg): bump deps, update testing infra

### PR DESCRIPTION
**Pull request by rgbkrk**
Getting dependencies up to date here. I've got more deprecations to handle as well as updates to the lerna packages.

~~Not ready for merging!~~

### CODE REVIEW

**Comment by lgeiger** [comment]
Great!

You'll probably need to use `electron-builder` version 16.8.1 since 16.8.0 has a regression: https://github.com/electron-userland/electron-builder/issues/1415#issuecomment-292797981

**Comment by rgbkrk** [comment]
Ok cool, I'll pin to 16.8.0.

**Comment by lgeiger** [comment]
> Ok cool, I'll pin to 16.8.0.

16.8.0 has the regression. It should be fixed in 16.8.1

**Comment by rgbkrk** [comment]
Thank you for repeating, Kyle not read so good.

**Comment by rgbkrk** [comment]
Taking https://github.com/facebook/immutable-js/releases/tag/v4.0.0-rc.2 for a spin now too, though we could merge this before I go crazy upgrading all the lerna packages. :wink:

**Comment by rgbkrk** [comment]
Ok since the changes enclosed here pass and the app is currently working, I'd like to go ahead and merge this.

I'm working with the newer Immutable and React+ReactDOM, it will take a bit to get us up to date.

**Pull request merged**
