### PR TITLE
Problem: Cells are hard to move around the document.

### PR DESCRIPTION
**Pull request by jdfreder**
Sln: Use ids instead of indices

### CODE REVIEW

**Comment by jdfreder** [comment]
This is ready now

**Comment by rgbkrk** [comment]
Great! What was the problem you ran into?

**Comment by jdfreder** [comment]
I opened an issue about it #119 , caused by me forgetting we were using immutable - I used `[]` instead of `get()`, see 5a22a27

**Comment by rgbkrk** [comment]
Hmmm, might be seeing something else needing some reflection:

screenshot 2016-02-12 00 02 26

**Pull request merged**
