### PR TITLE
[WIP] Fix typedoc packages build issues on Windows

### PR DESCRIPTION
**Pull request by BenRussert**
typedoc.js -> typedoc.json change to fix a weird windows issue where running the build script
opens the typedoc.js in your editor or default .js opener on windows.

`yarn package:docs` still fails on windows for now, but [this open PR could change that soon](https://github.com/unstubbable/typedoc-plugin-monorepo/pull/1)

### CODE REVIEW

**Comment by BenRussert** [comment]
I was trying to find the WIP or similar tag for this. It's waiting on an upstream change, but I don't want to forget to fix it.

**Comment by captainsafia** [comment]
Cool! Thanks for working on this!

**Comment by captainsafia** [comment]
I'm gonna go ahead and close this since there is no traction on the other PR.

For now, I'll add text to the RELEASING doc that outlines that TypeDoc won't run on Windows.

**Comment by BenRussert** [comment]
Cool thanks. I'm all about the WSL lately for stuff like this. I'll try it out on this sometime and see if it's worth adding a note about on the read me.

**Pull request closed without merging**
