### PR TITLE
Break it up

### PR DESCRIPTION
**Pull request by rgbkrk**
This (hopefully) makes it more clear what the main thread is and where the renderer thread lives (notebook here).

### CODE REVIEW

**Comment by rgbkrk** [comment]
If for any reason we switch to webpacking this up, this transition makes that a _lot_ simpler.

**Comment by jdfreder** [comment]
Thanks, this is great.  I still need to get the full circle tests working for the different CLI arg patterns

**Comment by jdfreder** [comment]
aka electron-compile working on electron-mocha

**Comment by rgbkrk** [comment]
Sweet, yeah.

I'm writing a README in the src/ directory as well right now to clarify the distinction between `main` and `notebook`.

**Pull request merged**
