### PR TITLE
Use a drag handle instead of the whole cell,

### LINKED ISSUE #136: Need to be able to select text in outputs
The current drag and drop is awesome!

I'd love to be able to select text and images in outputs and rendered markdown text, which currently conflicts with our drag handle. You can select code no problem, just nothing that's rendered.

### PR DESCRIPTION
**Pull request by jdfreder**
Allows users to select output
closes #136

### CODE REVIEW

**Comment by rgbkrk** [comment]
Now that's a sneaky handle

**Comment by rgbkrk** [comment]
Since we're variablizing our CSS anyways, we should probably make this match the input area width directly.

**Comment by rgbkrk** [comment]
Looking great! This works quite well. It feels (as a user) that the selection region should start a bit further in on the left of the output area.

**Comment by jdfreder** [comment]
> It feels (as a user) that the selection region should start a bit further in on the left of the output area.

Do you mean the array of selectable text?  IOW the drag handle width should be thinner?

**Comment by rgbkrk** [comment]
Yeah, thinner drag handle width.

**Pull request merged**
