### PR TITLE
[WIP] Create a conda env epic

### PR DESCRIPTION
**Pull request by rgbkrk**
WIP. This is just a start to resolving #357.

Precursors:
- [x] Splash screen for slow loading
- [ ] Main thread redux store

Possible precursor:
- [ ] Bring in/refactor spawnteract to use `spawn-rx`

TODO: 
- [ ] Load kernelspecs for conda in main thread (for menu)

/cc @damianavila for review of `conda` integration in the nteract desktop app.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Now that I've got this working, I'm tempted to move it and all kernelspecs usage to the main thread, only to run once on startup, providing the kernelspecs to all `BrowserWindow`s. The main thread could also `watch` to see if any environments are deleted or added.

**Comment by jdetle** [comment]
What would we lose if you were to do that?

**Comment by rgbkrk** [comment]
Step right up! You have nothing to lose and only something to gain! Conda based kernels! Environment synchronization!

image

Ok, no, startup for the main app is going to become a tad slower while investigating all the conda environments (if you have any). However, running it in the main thread means it's only slow _once_ on app startup.

**Comment by jdetle** [comment]
Speaking of which, should we agree on sort of performance goal/metric where we say startup should never take more than X amount of time on a machine with some set of specifications? Or is that too arbitrary?

**Comment by rgbkrk** [comment]
Yeah, it's pretty arbitrary. We can evaluate based on how things work with users. This slows things down for people with conda, who are also likely the ones to _want_ this. If they don't have conda it's really quick, little cost. I feel like the tradeoff here is worth it if we manage it well. It's still < half a second on my machine with many conda environments.

**Comment by captainsafia** [comment]
> I feel like the tradeoff here is worth it if we manage it well.

Yep! If we end up having other things happening during startup that slow us down, we can go ahead and implement that loading splash screen we've been thinking about.

**Comment by rgbkrk** [comment]
Rebased on master now that a bunch of pre-requisites to making this work well are done or outlined.

Still a WIP, I'm back to hacking on this.

**Comment by rgbkrk** [comment]
Closing since we have part of this implemented for the main process now.

**Pull request closed without merging**
