### PR TITLE
Use next-gen components for notebook

### PR DESCRIPTION
**Pull request by captainsafia**
* [x] Move Cell creation into the `<NotebookApp />`
* [x] Remove old Cell tests

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is looking great! We can probably extract the pinned cell and other component to nextgen or otherwise here.

**Comment by rgbkrk** [comment]
I forget, was this superseded by another PR @lgeiger & @captainsafia ?

**Comment by captainsafia** [comment]
Nope! It's WIP still. I think the thing that was holding us up was wanting to waiting for your new DropDown component so we could use that....

**Comment by rgbkrk** [comment]
I’m so close on the drop down! After I’m done Ice skating with the kiddos I’ll finish it up.

**Comment by rgbkrk** [comment]
Oooooook the dropdown menu, and by extension the toolbar, is ready to go so you can rebase and charge ahead here.

**Comment by captainsafia** [comment]
@rgbkrk: Thanks! Let me update this.

**Comment by rgbkrk** [comment]
I've taken over this branch while @captainsafia is doing the valiant effort of upgrading our immutable to 4.0.0-rc9 and the latest in flow technology.

Some initial TODOs / steps ahead to take note of where I think this needs to go:

* [x] Create this current notebook as a `provider` component
* [ ] See if there is a "view" level of component we can have as our base component
* [x] Move StickyCellContainer and PinnedCellPlaceholder to their own component files

I'll keep adding to this list (and moving it to the top of this PR).

**Comment by rgbkrk** [comment]
Ok this is _mostly_ in order here. Seems to work well with desktop, I'll do some more checking of behavior here and review this thoroughly. Next up is tests. I'll add on to the PR description for the TODO.

**Comment by rgbkrk** [comment]
Finished up each of those, now for the exercising of the app in case this touched parts that it shouldn't have.

**Comment by rgbkrk** [comment]
Lookin' good on the apps side!

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
