### PR TITLE
[WIP] Move more packages out of monorepo

### PR DESCRIPTION
**Pull request by captainsafia**
Moving out more of the packages outline in #4981.

I also pinned TypeScript to 3.7.3 since 3.8 contained some configuration changes that affect the `noEmit` option we had configured for the nteract desktop app build.

### CODE REVIEW

**Comment by willingc** [comment]
When I run locally I'm getting a bunch of import errors for the tests. Perhaps due to the movements out of the monorepo.

**Review by willingc — COMMENTED** [review]
Looks like the imports are causing CircleCI to hang and timeout too

**Comment by captainsafia** [comment]
> Looks like the imports are causing CircleCI to hang and timeout too

I saw the same as well. Been working on figuring out why and will push more commits once I am done.

In the meantime, I'll add the WIP label to this to let folks know that it is still in progress.

**Comment by captainsafia** [comment]
This is getting rather bothersome so I'm closing this in favor of PRs migrating each of the packages one by one to make it easier to debug.

**Pull request closed without merging**
