### PR TITLE
[WIP] Add Autocompletion for IJulia

### PR DESCRIPTION
**Pull request by willingc**
Addresses #4415

### CODE REVIEW

**Comment by captainsafia** [comment]
@willingc What else do we need to do so that this PR is mergeable?

**Comment by willingc** [comment]
@captainsafia I think that we need to fix a wider issue with autocomplete. It wasn't working with the Python kernel.

**Comment by captainsafia** [comment]
@willingc Do you get completions when you type Ctrl-Space in the editor? Typeahead completions were temporarily moved a while back since a lot of users found them arbitrary and annoying and we didn't have a configurability layer for it.

**Comment by willingc** [comment]
Closing since the solution isn't correct and the rebase mucked things up.

**Pull request closed without merging**
