### PR TITLE
Revert "Allow Nteract on Jupyter to build on Firefox >= 31"

### PR DESCRIPTION
**Pull request by rgbkrk**
Reverts nteract/nteract#3251

😬 Was meant to be a demo, my bad.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Squashed this revert in since one of the generated commits was the electron upgrade (shouldn't have been part of it).

**Comment by alexandercbooth** [comment]
😅, whoops -- thought that seemed an old version of firefox to be using as a base. Sorry!

**Comment by rgbkrk** [comment]
It's cool to push back on me when your intuition says that. 😅

**Comment by alexandercbooth** [comment]
OK, will do 😄

**Pull request merged**
