### PR TITLE
adapt notebook preview to @nteract/core

### PR DESCRIPTION
**Pull request by rgbkrk**
This switches `notebook-preview` to use our next gen components out of nteract. There's still more to do, including:

* [x] Don't show hover style within notebook-preview
* [x] Include (built-in) styles for outputs 
* [x] Delete old styles
* [x] Include our built in themes as strings within `@nteract/core`
* [x] Update documentation for notebook preview
* [x] ~~Hook the showcase up to a collection of notebooks to render~~ re-use the render by gistID from notebook-preview-demo
* [x] ensure the code loading path for the nextgen components doesn't include the older components in order to save webpack bundling time
* [x] Convert `notebook` to commutable notebook in `<NotebookPreview />`
* [x] fix up all the flow, tests, etc.
* [x] fix the desktop tests

As is, it's looking pretty good. 😄  Once I've finished those, I'm super excited to make a notebook preview release as this should be a much lighter weight component once fully cleaned up.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Woo, three left to go on my checklist. 😄

**Comment by rgbkrk** [comment]
Yeah I don't think this theming is fully fleshed out here.

screen shot 2017-11-13 at 8 37 03 am

**Comment by rgbkrk** [comment]
(looks like I need to make sure that rendered markdown and outputs are using the themes... I'll have to do some other checking here...)

**Comment by rgbkrk** [comment]
Looks like it's likely because of the lack of the top level styling from `main.css`:

```css
body {
  font-family: "Source Sans Pro";
  font-size: 16px;
  line-height: 22px;
  background-color: var(--main-bg-color);
  color: var(--main-fg-color);
}
```

**Comment by rgbkrk** [comment]
@tlyon3 -- this is the work in progress re-write / simplification of `<NotebookPreview />` using the `@nteract/core` components and a static viewer (no codemirror). It would be great to have you look over it, especially with regards to how you're currently theming Quantecon  bookshelf.

**Comment by tlyon3** [comment]
@rgbkrk Awesome! Thanks! I'll look over it once I get a chance :)

**Comment by rgbkrk** [comment]
Everything is lookin' good. Time to fix up flow and tests.

screen shot 2017-11-13 at 12 03 18 pm
screen shot 2017-11-13 at 12 03 22 pm

This is definitely ready for reviewing!

**Comment by rgbkrk** [comment]
Note: our use of `react-syntax-highlighter` will need adaptation to match our code styling. I would love if someone picked that up as another PR.

**Review by captainsafia — APPROVED** [review]
This looks good to me!

**Comment by rgbkrk** [comment]
Here's where I'm stuck after doing a fresh `git clean -xfd && npm i`:

```
 FAIL  packages/desktop/__tests__/renderer/index-spec.js
  ● Test suite failed to run

    /Users/kylek/code/src/github.com/nteract/nteract/packages/desktop/node_modules/@nteract/core/src/components/notebook.js:3
    import React from "react";
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (packages/desktop/src/notebook/index.js:13:17)
      at Object.<anonymous> (packages/desktop/__tests__/renderer/index-spec.js:1:116)

Summary of all failing tests
 FAIL  packages/desktop/__tests__/renderer/index-spec.js
  ● Test suite failed to run

    /Users/kylek/code/src/github.com/nteract/nteract/packages/desktop/node_modules/@nteract/core/src/components/notebook.js:3
    import React from "react";
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (packages/desktop/src/notebook/index.js:13:17)
      at Object.<anonymous> (packages/desktop/__tests__/renderer/index-spec.js:1:116)

```

**Comment by rgbkrk** [comment]
Ooooook, now this is good to go

**Comment by rgbkrk** [comment]
screen shot 2017-11-13 at 6 46 21 pm

**Comment by rgbkrk** [comment]
😄

**Pull request merged**
