### PR TITLE
Collect and report coverage

### PR DESCRIPTION
**Pull request by rgbkrk**
Coveralls!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looks like I need to adapt this for the test matrix.

**Comment by jdfreder** [comment]
Yeah, there's also a failure when trying to run coveralls that I see on Travis

**Comment by rgbkrk** [comment]
I got codecov working, I'll be posting a PR when I get back home.

**Comment by jdfreder** [comment]
:tada:

**Pull request merged**
