### PR TITLE
Fix windows CLI

### LINKED ISSUE #2084: Install Shell Commands produces Javascript Error
When I click ```Help > Install Shell Commands``` in a freshly installed nteract (Windows 10, x64 release 0.3.4). I get following Javascript Error message:  

nteract_javascript_error

### PR DESCRIPTION
**Pull request by lgeiger**
This should fix #2084

Could anybody test this on Windows?

Side Note: I think refactoring this file to use `async` / `await` would probably make this more readable.

### CODE REVIEW

**Review by rgbkrk — APPROVED** [review]
This looks right to me!

**Comment by rgbkrk** [comment]
I wonder if there’s a way to test the script from appveyor. I really wish there was some magical way to only test the code that only affects windows (path handling). We end up mocking all the things that touch the system when we probably should have a few integration or functional tests.

**Comment by rgbkrk** [comment]
I'm going to operate under the assumption that this is in a good state and make it part of the shipped app tonight.

**Comment by lgeiger** [comment]
:+1:

**Pull request merged**
