### PR TITLE
docs(commutable): Add a link to the commuter docs in the README

### PR DESCRIPTION
**Pull request by Madhu94**
I didn't know these docs existed! I was going through the code to figure out how commutable worked, I just want to make sure no one else misses this..

### CODE REVIEW

**Comment by rgbkrk** [comment]
🤔  Those are probably from the "old" https://github.com/nteract/commutable, we should probably figure out a way to document all our packages in one handy spot.

**Comment by Madhu94** [comment]
Yeah, I should remove the typescript reference and put flow there, but otherwise the tutorial still holds good.

Do you have any docs about how nteract transforms work ? I'm guessing they are the nteract equivalent of the notebook's custom mime-types, but don't know how they work..(Not that figuring out stuff from code isn't fun :) )

**Comment by rgbkrk** [comment]
nteract transforms are similar to the notebook's custom mimetype. They take mimetyped data and turn it into a react element. The nteract transforms library has some helpers for picking which of the transforms to use given a bundle of output data from a notebook file.

**Comment by Madhu94** [comment]
> The nteract transforms library has some helpers for picking which of the transforms to use given a bundle of output data from a notebook file.

Thanks, will try it soon..! I'm trying out some nteract packages these days and would love more unified docs.

edit:- Instead of saying I could use some docs, I should add more docs myself. :)

**Comment by rgbkrk** [comment]
Yeah I've been really hoping we could feature them on the main site in a nice way.

**Pull request merged**
