### PR TITLE
[WIP] feat(menu): expand cells on export pdf

### PR DESCRIPTION
**Pull request by jkornblum**
Addresses issue #1610.

It will expand collapsed (default state) cells before export to PDF via modifying CSS. After export is
complete it will restore the cells to as before the export PDF.

Print to PDF still respects if you have the output hidden.

### CODE REVIEW

**Comment by jdetle** [comment]
Looks great, and it looks like regression tests are working ;) If you can mock some of the cellmap stuff I imagine these tests will pass.

**Comment by jkornblum** [comment]
I'll change this to WIP while I fix/add unit tests.

**Comment by jdetle** [comment]
Did you have some trouble rebasing?

**Comment by jkornblum** [comment]
Hmm I didn't think so but it looks something got out of sync....

If I can't get it back on track I might just close this PR and open a new one with a fresh branch.

**Comment by jdetle** [comment]
Whatever git workflow is the least amount of time for you is the one I support fully! Good luck, I'm quite excited to see this get merged :)

**Comment by jkornblum** [comment]
Closing this for #1671

**Pull request closed without merging**
