### PR TITLE
Conditionally display empty cell message depending on state

### PR DESCRIPTION
**Pull request by jdfreder**
Suggested in #202

@betatim @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
This certainly captured the intent of what I said!

I was thinking it would be a div you add in conditionally, this works even better since you get to set the message using Markdown. :wink:

**Comment by rgbkrk** [comment]
One thing I noticed here is that we're not focusing the editor when we double click (were we before?)

**Comment by jdfreder** [comment]
No, I don't think so.  In jupyter/notebook we do

**Comment by betatim** [comment]
Why the `!==`?

```
 this.state.source !== '' ?
                this.state.source :
                `*Empty markdown cell, double click me to add content.*`
```

vs

```
 this.state.source ?
                 this.state.source :
                 `*Empty markdown cell, double click me to add content.*`
```

Does it make any difference in JS? I python I spend my time telling people to use `if some_string` :-/

**Comment by jdfreder** [comment]
Looks like that works too @betatim , thanks!  Want to open a PR?

**Comment by rgbkrk** [comment]
:+1: @betatim

**Pull request merged**
