### PR TITLE
[WIP] Add more tests

### PR DESCRIPTION
**Pull request by captainsafia**
Not ready to merge yet.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Just a note to get started and make your life simpler - @kenwheeler suggested we use [enzyme](https://github.com/airbnb/enzyme) which we've started using in [transformime-react](https://github.com/nteract/transformime-react).

**Comment by jdfreder** [comment]
Closing and reopening to trick travis into rerunning...

**Comment by jdfreder** [comment]
I guess I could have just clicked the little restart wheel, but I was hoping coveralls was ready now @rgbkrk

**Comment by rgbkrk** [comment]
Nah, not yet. I'm going to prep and eat some lunch then I can tackle coveralls.

**Comment by captainsafia** [comment]
> Just a note to get started and make your life simpler - @kenwheeler suggested we use enzyme which we've started using in transformimp-react.

This is really useful! Thanks @rgbkrk and @kenwheeler.

**Comment by rgbkrk** [comment]
I've switched over one test to enzyme, rebasing will make your work easier here.

**Comment by rgbkrk** [comment]
Since @jdfreder cherry picked the commit from here in #362, closing.

**Pull request closed without merging**
