### PR TITLE
Remove createExecuteRequest functions from @nteract/messaging | issue #4780

### PR DESCRIPTION
**Pull request by ramantehlan**
Remove `createExecuteRequest` functions from @nteract/messaging.

> [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by captainsafia** [comment]
Hi @ramantehlan! I see this is still in Draft phase but you've requested a review. Is it ready to look at?

**Comment by ramantehlan** [comment]
Hi @captainsafia, no it's not ready for the review yet. :p 

Also, when I run `yarn test`, some tests were ignored, is that normal?

**Comment by captainsafia** [comment]
> Also, when I run yarn test, some tests were ignored, is that normal?

Yes, there are 5 tests that are currently skipped. One in @nteract/messaging and four in @nteract/vega-transform. There are some config-related issues to get these tests working.

**Comment by ramantehlan** [comment]
Changes by this PR are already merged by PR #4933.

**Pull request closed without merging**
