### PR TITLE
Immutable app state

### PR DESCRIPTION
**Pull request by rgbkrk**
Bringing that immutable to the app state too. Tests likely won't pass right away here, bear with me a sec.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Now we await news from Travis and CodeCov!

**Comment by rgbkrk** [comment]
Oh wait, tests pass yet the app is not running locally. Hit the pause button on this one for a bit.

**Comment by rgbkrk** [comment]
Back and forth, ready to go now. Rebased this down to more sensible commits while I was at it.

**Comment by captainsafia** [comment]
Waiting on our old pal, Travis! 👦

**Pull request merged**
