### PR TITLE
feature(notebook): Improve cell/editor focusing UX

### LINKED ISSUE #1065: Document Cell Focus UX Design
I'd :heart: to see us write documentation for what a notebook is in user experience terms. Right now it's a bit implicit ("it's the implementation!") -- I think we can capture different behaviors and user intents in some solid documentation/specifications. Let's tackle Cell Focus UX design first!

@captainsafia is currently solving the input focus on click in code cells problem in #1055 (our current setup is rather pesky). Hopefully we can solve all our focus problems with a clear declaration + implementation.
## Cell Focus UX

cell focus user experience

User intents, written:
### `shift enter`
- Focus on next cell (and create it if it doesn't exist)
- Scroll to next cell
- Focus Editor at top of next cell (first line) if a code cell or a markdown cell in edit mode

Note: this is the same set of changes expected with the down arrow (for focus, not execution).
### `up arrow`
- Focus on previous cell
- Scroll to previous cell
- Focus editor at bottom of previous cell (last line) if a code cell or a markdown cell in edit mode
### `down arrow`
- Focus on next cell (and create it if it doesn't exist)
- Scroll to next cell
- Focus Editor at top of next cell (first line) if a code cell or a markdown cell in edit mode
### Click editor area
- Focus clicked cell
- Don't scroll
- Don't _manually_ focus the editor, let CodeMirror do the handling
### Click display area
- Focus clicked cell
- Don't scroll
- Don't focus the editor
### Drag cell
- Focus clicked cell
- Don't scroll
- Don't focus the editor

Since I by no means think this is a decree, I've drawn my initial thoughts on cell focus UX with crayon. We should refine this as necessary and produce a document. Happy to turn this into a Sketch document when ready.

/cc @willingc and @peggyrayzis who expressed interest in this

### PR DESCRIPTION
**Pull request by peggyrayzis**
When finished, this will close #1065 🎉 

Checklist:
- [X] Up focuses previous cell & its editor
- [X] Down focuses next cell & its editor
- [X] Shift + enter properly focuses editor
- [x] Clicking properly focuses editor but needs to sync up w/ Codemirror (right now, it's a bit wonky)
- [x] Editor needs to focus correctly when in a markdown cell (I'm having trouble describing this one well, help?)
- [x] Fix tests to reflect updated functionality

Please add if there are any I'm missing or reword if I should be more clear! @rgbkrk @captainsafia - thanks again for all your help with this issue 😀

### CODE REVIEW

**Comment by rgbkrk** [comment]
One thing that @captainsafia's PR #1055 exposed was that we needed to use the `onClick` handler from the CodeMirror component: 

https://github.com/nteract/nteract/pull/1055/files#diff-d28163d397f24b7e0cde9ddf00d9cb0dR263

Effectively, let CodeMirror handle the click into the editor (which it will regardless) while registering that click as setting the focus cell (without changing scroll).

**Comment by rgbkrk** [comment]
Also, thank you thank you thank you for working on the cell focus - this is the most important user experience piece we've needed to address.

**Comment by peggyrayzis** [comment]
I changed the logic so CodeMirror solely handles clicking onto the editor, roughly based on Safia's earlier PR that you linked. The problem now is that we still need to keep some sort of focusing logic based on the editorFocused prop in componentDidMount/componentDidUpdate - otherwise, the editor won't focus properly when the user presses up/down or shift + enter.

**Comment by peggyrayzis** [comment]
I added the editorFocused logic back in componentDidMount/componentDidUpdate to preserve the up/down/shift+enter functionality. I think clicking works as expected now, but would love a second set of eyes to confirm!

**Comment by rgbkrk** [comment]
Tried this out just now, it appears to be working exactly like I expect as a user. 😄

**Comment by rgbkrk** [comment]
Also looks like unfocusing from the codemirror editor happens properly now!

**Comment by rgbkrk** [comment]
The only thing that I think we probably want to refine later is scroll within larger notebooks. I don't have anything concrete to articulate yet, I'll do some thinking. As it stands, this PR is excellent and I look forward to bringing it in!

**Comment by rgbkrk** [comment]
As noted above, the markdown editing still needs to be addressed.

Most of the markdown cell appears correct. The primary fix here is that when a markdown cell switches to edit mode from view mode, either by:
- hitting enter
- double clicking the markdown cell to edit

that the codemirror editor will be focused.

**Comment by rgbkrk** [comment]
Awesome, markdown is working stellar now!

**Comment by peggyrayzis** [comment]
Some weird stuff going on with the linter - AppVeyor fails because of this:
`C:\projects\nteract\src\notebook\components\cell\cell.js
  138:11  error  Expected indentation of 12 space characters but found 10  react/jsx-indent
✖ 1 problem (1 error, 0 warnings)
`

When I fix the error and run the linter locally, I get this:
`/Users/mrayzis/projects/open-source/nteract/src/notebook/components/cell/cell.js
  138:13  error  Expected indentation of 10 space characters but found 12  react/jsx-indent
`

Any reason why there would be a conflict?

**Comment by jdetle** [comment]
@peggyrayzis, I've gotten similar errors, but then they don't show up in travis. So you're not alone.

**Comment by rgbkrk** [comment]
🎉

**Pull request merged**
