### PR TITLE
Add: Open recent to file menu on osx

### PR DESCRIPTION
**Pull request by piercefreeman**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

As proposed in #263, this PR adds an open recent menu to macOS.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Excellent! Thank you for adding this! I've been wanting for Open Recent for a loooong time.

One thing that's held me back from adopting a new version of Electron was builds of zeromq.js working with our setup across platforms. I'll have to check that aspect out.

**Comment by rgbkrk** [comment]
Ooook, now that the desktop build is fixed (thanks @lgeiger!) I'm going to give this a spin.

**Comment by rgbkrk** [comment]
Since I need the latest changes on master to evaluate if the production version can build with electron 2.0, I'm going to rebase this PR and force push it. I'll keep you posted @piercefreeman!

**Comment by rgbkrk** [comment]
Verified that Electron 2.x works on Windows and Mac! Merging! Thank you so much @piercefreeman. Welcome to nteract! 🎉

**Comment by piercefreeman** [comment]
Happy to help @rgbkrk!

**Comment by piercefreeman** [comment]
@rgbkrk Interesting... When I build fresh from master "Open Recent" works great but in the released package it comes up with a blank list. Does this work on your end?

**Comment by rgbkrk** [comment]
Nope, doesn't work on my mac. Perhaps I should try again with a fresh build on master.

**Comment by piercefreeman** [comment]
Let me know if you do.  I was doing `npm run app:desktop` and it worked fine.

**Pull request merged**
