### PR TITLE
Svg docs bugfix

### PR DESCRIPTION
**Pull request by stormpython**
- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

Fixes minor issue with a typo in the default props.

### CODE REVIEW

**Comment by captainsafia** [comment]
Great catch! Thank you.

**Review by emeeks — APPROVED** [review]

**Review by rgbkrk — CHANGES_REQUESTED** [review]
Looks like we will need a jest snapshot update with "yarn test --updateSnapshot"

**Comment by rgbkrk** [comment]
Thank you Shelby!

**Review by rgbkrk — APPROVED** [review]

**Comment by rgbkrk** [comment]
Welcome to the nteract party! 🎉

**Comment by stormpython** [comment]
Woo hoo, my first PR🎂!!! Hopefully, the first of many!

**Pull request merged**
