### PR TITLE
feat: launch by kernelspec

### PR DESCRIPTION
**Pull request by rgbkrk**
Beginning efforts to make it so we can launch by kernelspec rather than
kernelspec name. This is to enable conda environments, an embedded JS kernel,
and make it easier to do remote kernels by refactoring how we launch.

* [x] Launch new notebook from command line
* [x] Launch new notebook from menu
* [x] Change kernel
* [x] Open old notebook
* [x] More test coverage
* [x] Ensure notebook schema conformance

### CODE REVIEW

**Comment by rgbkrk** [comment]
This PR is excellent proof of missing tests for main. :wink:

**Comment by alexandercbooth** [comment]
I'd be happy to start chipping away on some tests for main, if someone wouldn't mind giving me a little guidance on where to start.

**Comment by rgbkrk** [comment]
> I'd be happy to start chipping away on some tests for main, if someone wouldn't mind giving me a little guidance on where to start.

I'm going to break so many things right now that I might as well make a testing harness for some of what's in main here.

The _main_ thing is that much of main can be tested just like the notebook. Try to find functions that don't require the filesystem or electron APIs (there are a few I know of) and you'll be off to a start.

**Comment by jdetle** [comment]
> The _main_ thing is that  

I c wut u did thar

**Comment by rgbkrk** [comment]
Ok this is now "ready". By that I mean that it's ready for me to update tests now that I have it working.

**Comment by rgbkrk** [comment]
This still fails conformance tests, I'll come back to it later.

**Comment by rgbkrk** [comment]
Rebased, going to see what likely lint errors exist now.

**Comment by rgbkrk** [comment]
Sure enough, this PR still has an issue with conformance:

```
$ npm run test:conformance

> nteract@0.0.15 test:conformance /Users/kylek/code/src/github.com/nteract/nteract
> node scripts/conformance.js

✅	/Users/kylek/code/src/github.com/nteract/nteract/example-notebooks/altair.ipynb
❌	/Users/kylek/code/src/github.com/nteract/nteract/example-notebooks/blah.ipynb
[ ValidationError {
    property: 'instance.metadata.kernelspec',
    message: 'requires property "display_name"',
    schema:
     { description: 'Kernel information.',
       type: 'object',
       required: [Object],
       properties: [Object] },
    instance: { name: 'python3' },
    name: 'required',
    argument: 'display_name',
    stack: 'instance.metadata.kernelspec requires property "display_name"' } ]
```

I'll see if I can iron that out. Otherwise, kernels are executing just fine.

**Comment by rgbkrk** [comment]
Finally finished off this branch -- the kernel info is set properly in the document now. It's very ready for review. :smile:

**Review by jdetle — COMMENTED** [review]
Per advice in https://github.com/redux-observable/redux-observable/issues/108, 

```
ActionsObservable.of(executeCell('id', 'source')));
  executeCellEpic(action$, store)
    .toArray()
    .subscribe(actions => {
      expect(actions).to.deep.equal([
        kernelNotConnected() // whatever action creators
      ]);
      done();
    });
});
```
is a more succinct pattern to follow in the future.

**Pull request merged**
