### PR TITLE
Import rx jupyter

### PR DESCRIPTION
**Pull request by rgbkrk**
Bring [`rx-jupyter`](https://github.com/nteract/rx-jupyter) into the monorepo. I assume we'll want to adapt this to use jest as well. These are the pure commits, so if they come in cleanly then I think we can start adapting after.

/cc @captainsafia

### CODE REVIEW

**Comment by rgbkrk** [comment]
🤔 Oh yeah I should delete the tag commits probably. Did I do that for the other imports? I'll come back to this after family things.

**Comment by captainsafia** [comment]
Very nice! I will merge.

**Comment by rgbkrk** [comment]
Oops I meant to delete the old release commits / reword them to match the lerna style like I did for other PRs.

**Comment by captainsafia** [comment]
Oops. 🤦🏽‍♀️

**Comment by rgbkrk** [comment]
All good, I'm going to see if I can fix it real quick. I will either rebase master or just revert this PR. I'm really sorry, I should have put WIP in the title after I initially noticed the tag commits.

**Comment by rgbkrk** [comment]
Since the revert is a single commit and all the commits are interwoven, I think we'll just go with this. 😬  Time to make my clean up PR next.

**Pull request merged**
