### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by Carreau**
And command to generate the icns (could be automatized more).

Transition we at 32px in finder:

ico-trans

Might need a bit more white in the background for the dock:
screen shot 2016-04-19 at 15 14 05

Maybe even a flashier Blue if you look at other blue-ish icon. 

screen shot 2016-04-19 at 15 16 25

Not sure how to generate the `.ico` for windows...

### CODE REVIEW

**Comment by betatim** [comment]
💎

**Comment by Carreau** [comment]
bash bonus:

```
convert -density 200 -resize 256x256 <(cat nteract-desktop.svg|sed 's/5995f3/ffffff/' ) test.png ; qlmanage -p test.png
```

(replace `ffffff` by the a color you like)

**Comment by rgbkrk** [comment]
Whoa, love how the icon changes based on the size.

**Comment by rgbkrk** [comment]
We could probably do without the little `n(t)` that I put together on a whim to think about alternate icons.

**Comment by rgbkrk** [comment]
This is quite an enhancement on the sloppily chopped logo I handed Jon for testing. :wink:

We have a [logos repo](https://github.com/nteract/logos) for us to iterate on the logo by the way.

**Comment by Carreau** [comment]
Ok, will try to put logo there.

**Comment by jdfreder** [comment]
This is fantastic!  Thanks @Carreau !

**Pull request merged**
