### PR TITLE
fix(path): fix cwd for dialogs and kernels

### LINKED ISSUE #919: Restarting kernel does not preserve working directory
when the kernel is restarted with a previously saved notebook, the working directory is reset to the user's home directory, rather than the path of the open ipython notebook.

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #919 and a follow on for #945 for the frontend.

Created some helper methods to make this more sane across the entire app.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Let me get some extra tests in here.

**Review by jdetle — APPROVED** [review]
Thanks for changing the 'wat' error :)

**Comment by rgbkrk** [comment]
Oh, thanks for merging. I've got some tests I haven't been able to commit yet because I've been talking to people.

**Comment by jdetle** [comment]
I'll ask for a ready-for-merge next time, my bad.

**Comment by rgbkrk** [comment]
Tis ok, I'd rather see this in. It solves a lot of issues. I'll be increasing code coverage later tonight for this, just a few lines.

**Pull request merged**
