### PR TITLE
Removing execution from markdown cell toolbar

### PR DESCRIPTION
**Pull request by kenwheeler**
Because that's silly

### CODE REVIEW

**Comment by betatim** [comment]
I spent a good few minutes clicking that play button the other day wondering if it should do raw -> rendered markdown.

**Comment by jdfreder** [comment]
Without this can we still go from unrendered markdown to rendered via the mouse?

**Comment by kenwheeler** [comment]
@jdfreder @betatim should we introduce a new toggle button for MD cells for that behavior?

**Comment by betatim** [comment]
For me the play button didn't go from raw -> rendered, which made me wonder if it should or not.

**Comment by betatim** [comment]
Having a button is probably a good idea. Not sure if it should have a different symbol as I can't think of one that really conveys "rendering only" without being totally abstract (but then I also have to think for a moment which one of the new cell buttons gives me a new code cell every time I use it ...)

**Comment by rgbkrk** [comment]
Definitely fine to be deleting it now and letting someone come in to make the button later.

It seems like the pencil/edit icon would work well here for entering edit mode on a markdown cell.

**Pull request merged**
