### PR TITLE
completely overhaul gist publishing

### PR DESCRIPTION
**Pull request by rgbkrk**
This has been a complete overhaul of gist publishing. Quite a few things happened in here:

* [x] Switch to pure RxJS `ajax` calls for creating and updating gists
* [x] Completely remove anonymous gist publishing as github no longer allows it
* [x] Co-locate more of the publishing logic together
* [x] Formally declare our types for github publishing
* [x] Show notification when starting publishing (again)
* [x] Fix up tests
* [x] Detect when the github token used doesn't have gist scope

This had the extra effect of reducing our app size due to sub-dependencies being cut out. 💇🏻‍♂️

### CODE REVIEW

**Comment by rgbkrk** [comment]
~~I've started getting 404s with the github api on the simplest of POSTs against their API. I'm unsure what's going on...~~

```
$ curl \
>   -H "Content-Type: application/json" \
>   -H "Accept: application/vnd.github.v3+json" \
>   -H "Authorization: token $GITHUB_TOKEN" \
>   -d '{"files": {"Untitled.ipynb": {"content": "some file"}}}' \
>   https://api.github.com/gists
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

~~I reported it to GitHub support as well since everything appears right to me.~~

This happens when a token doesn't have gist scopes. I'm going to make sure that gets detected as part of this PR.

**Comment by rgbkrk** [comment]
Hey @jdetle, I took the liberty of completely refactoring the github publishing flow. Wanna check it out?

**Comment by jdetle** [comment]
Yes! Thanks for messaging me, I feel bad about not getting around to this.

**Comment by rgbkrk** [comment]
Hey no problem. Since the module we were relying on was going through enough changes I figured it was time for me to take a full look at this.

**Pull request merged**
