### PR TITLE
include missing external types for data explorer

### PR DESCRIPTION
**Pull request by rgbkrk**
Should help with finalizing this effort.

In order to add these, I just looked for missing definitions while in VS Code

screen shot 2019-01-02 at 10 28 15 am

then ran, for example:

```
yarn add -W --dev @types/d3-scale
```

### CODE REVIEW

**Comment by rgbkrk** [comment]
Updated the snapshots while I was at it, looks like a test is failing possibly due to changes that occurred while typescripting this:

```
Summary of all failing tests
 FAIL  packages/transform-dataresource/__tests__/index-spec.js (6.403s)
  ● DataExplorerMetadata › creates a data explorer without metadata
  1 update snapshot

    TypeError: Cannot read property 'chart' of undefined

      159 |     const { dx: baseDX } = metadata;
      160 |
    > 161 |     const { chart = {}, ...dx } = baseDX;
          |             ^
      162 |
      163 |     const { fields = [], primaryKey = [] } = props.data.schema;
      164 |

      at new chart (packages/transform-dataresource/src/index.tsx:161:13)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:398:26)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:480:35
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:137:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:479:68)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous> (packages/transform-dataresource/__tests__/index-spec.js:225:21)

```

**Comment by jdetle** [comment]
is the right side of that supposed to be dx rather than baseDX?

**Comment by rgbkrk** [comment]
Sure looks like it.

**Comment by rgbkrk** [comment]
Or nope, it's trying to unpack it as a new variable. Worth a separate PR.

**Comment by rgbkrk** [comment]
Made it in this PR for now.

**Comment by rgbkrk** [comment]
Since the branch itself has this same problem, I'll just merge this.

**Pull request merged**
