### PR TITLE
Start moving tests over to jest

### PR DESCRIPTION
**Pull request by lgeiger**
Partially adresses #1911

### CODE REVIEW

**Comment by rgbkrk** [comment]
Wow this is a lot! Did you use a codemod or did you refactor by hand?

**Comment by rgbkrk** [comment]
Bye bye coverage and hello new coverage coming soon!

**Comment by rgbkrk** [comment]
I should probably just disable codecov for now...

**Comment by lgeiger** [comment]
> Wow this is a lot! Did you use a codemod or did you refactor by hand?

Yeah I used a code mod.

Only sinon and the electron mocks needed some refactoring by hand.

**Pull request merged**
