### PR TITLE
Add undo/redo functionality

### PR DESCRIPTION
**Pull request by captainsafia**

### CODE REVIEW

**Comment by captainsafia** [comment]
Jon's summary from #419:

Okay, this post may not be comprehensive, but it's all I've thought about now.
I think you'll want to tackle this in steps,

## First

You'll want to make sure that the document state is decoupled from the rest of the application state.  For example, in the following app state:

``` js
{
  cellPagers: Map,
  cellStatuses: Map,
  channels: Object,
  connectionFile: "/run/user/1000/jupyter/kernel-aaf19a34-c0da-4968-bc2f-d2f8c8ba904b.json",
  executionState: "idle",
  filename: "/home/jon/github.com/nteract/nteract/intro.ipynb",
  focusedCell: "260f6a26-9623-46b7-a83f-ce5f1830d21a",
  github: module.exports,
  notificationSystem: Constructor,
  spawn: ChildProcess,
  notebook: {
    cellMap: {
      "260f6a26-9623-46b7-a83f-ce5f1830d21a": {
        cell_type: "markdown",
        metadata: {},
        source: "a"
      },
      "2bc3af2b-43e7-4284-94a4-1bf135b15110": {
        cell_type: "code",
        execution_count: 2,
        metadata: {
          collapsed: false
        },
        outputs: [ ],
        source: "b"
      },
    },
    cellOrder: [
      "260f6a26-9623-46b7-a83f-ce5f1830d21a",
      "2bc3af2b-43e7-4284-94a4-1bf135b15110",
    ],
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        mimetype: "text/x-python",
        nbconvert_exporter: "python",
        name: "python",
        pygments_lexer: "ipython2",
        version: "2.7.10",
        file_extension: ".py",
        codemirror_mode: {
          version: 2,
          name: "ipython"
        }
      }
    },
    nbformat: 4,
    nbformat_minor: 0
  },
```

`cellPagers`, `cellStatuses`, `focusedCell`, `notebook` probably should be
recorded in the undo/redo stack.  It may make sense to sort the state (this is
something we'll have to do when we get to implementing RTC anyways):

``` js
{
  appState: { ... },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

## Second

You'll want two stacks in the application state, undo and redo.  

``` js
{
  appState: {
    undo: [],
    redo: [],
    ...
  },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

and two corresponding reductions, SET_FORWARD_CHECKPOINT and 
SET_BACKWARD_CHECKPOINT.  SET_BACKWARD_CHECKPOINT takes the current `userState`
and `documentState` and stores it in the `appState` under an `undo` stack.  For 
example, this would result in:

``` js
{
  appState: {
    undo: [
      {
        userState,
        documentState,
      },
    ],
    redo: [],
    ...
  },
  userState: {
    cellPagers
    cellStatuses
    focusedCell
  },
  documentState: {
    notebook
  }
}
```

You'll want to have sane limits on the number of recorded undo and redo actions.

SET_FORWARD_CHECKPOINT does the same thing but into the `redo` stack.

Lastly, the corresponding action for the SET_BACKWARD_CHECKPOINT reducer should
have a flag that optionally clears the redo stack (via a CLEAR_REDO reducer).

## Third

Create UNDO and REDO actions & reductions.

UNDO action will do the following:
- abort if `undo` stack length = 0
- SET_FORWARD_CHECKPOINT
- UNDO reduction: pop state from `undo` stack over `userState` and `documentState`

REDO action will do the following:
- abort if `redo` stack length = 0
- SET_BACKWARD_CHECKPOINT (clear redo = false)
- REDO reduction: pop state from `redo` stack over `userState` and `documentState`

## Forth

Call SET_BACKWARD_CHECKPOINT (clear redo = true) at the beginning of relevant, 
top-level user actions.

## Fifth

Implement menu items that point to the UNDO REDO reduction actions.

#### Checklist
- [x] Add SET_FORWARD_CHECKPOINT and SET_BACKWARD_CHECKPOINT reducers
- [x] Add tests for SET_FORWARD_CHECKPOINT and SET_BACKWARD_CHECKPOINT reducers
- [x] Add CLEAR_FUTURE reducer to erase entire future stack (stack of redos)
- [x] Add tests for CLEAR_FUTURE
- [x] Add `clearFuture` flag to SET_BACKWARD_CHECKPOINT
- [x] Add tests for SET_BACKWARD_CHECKPOINT with `clearFuture` flag
- [x] Add UNDO and REDO reducers for popping items of `past` and `future` stack
- [x] Add tests for UNDO and REDO reducers
- [ ] Identify notebook actions that should trigger an push to the `past` stack
  - Delete cell
- [ ] Remap Undo and Redo menu options
- [ ] QA test entire thing

**Comment by captainsafia** [comment]
I'm a little bit stuck on how to get the UNDO/REDO reducer working.

So far, I'm thinking of having a an UNDO/REDO app reducer that pops out the appropriate element from the list.

I'm also thinking of having an UPDATE_DOCUMENT document reducer that overwrites the current `document` with a `newDocument`.

I'm a little confused as to how to connect the two since each reducer operates on a certain part of the state and there is no way to access the document state/reducers from inside the app state/reducers.

Advice appreciated.

cc: @rgbkrk @jdfreder

**Comment by jaredly** [comment]
So another way of orchestrating this is:
just have a `state_history` list, that contains a list of states, and a `current_position` int that indicates where in history you are. The way I've done this in other settings, a `current_location` of `0` means you are at the most recent state.
Undo increments `current_position`, and redo decrements `current_position`.

Therefore, when accessing the current state:
`current_state = state_history[state_history.length - current_position]`.

Actions that result in a new state do `state_history.slice(state_history.length - current_position).concat([new_state])`.

**Comment by rgbkrk** [comment]
That's definitely the approach for history! The extra detail we run into is that not all of the document is intended to be undo-able (primarily outputs).

**Comment by captainsafia** [comment]
@jaredly — Yep! That was the approach that I started in #419. But we've since upgraded our state store from holding everything in a single store to holding the state relevant to the `app` and the state relevant to the `document` in separate stores.

The problem would persist in that implementation as well because you would need a reducer that has broader access outside just `app` or `state`.

I'm reading up on how to create reducers with broader access at the moment.  

EDIT: Or whether it is a good idea to do this.

**Comment by captainsafia** [comment]
This is close to done-ish. I'm working on QAing and making sure that everything works squeaky clean. Hoping to have it wrapped up either tonight or tomorrow AM!

**Comment by captainsafia** [comment]
OK! I think this is good to be merged. I did some QA and it seems to be working as intended. You can currently undo and redo cell deletions, additions, and sticky celling. More actions can be added as it makes sense.

Here's a quick overview of how it works.
1. `SET_BACKWARD_CHECKPOINT` appends items to the `past` stack.
2. `triggerUndo` middleware calls the `SET_BACKWARD_CHECKPOINT` reducer on `store.document` if `action.type` is one of the actions that is considered undoable.
3. `UPDATE_DOCUMENT` overwrites `store.document` with the `newDocument` passed to it.
4. When the user hits undo, the last items is selected from the past stack and set to `UPDATE_DOCUMENT`. Then `SET_FORWARD_CHECKPOINT` is called to add it to the redo stack. Then `UNDO` is called which pops the last item off the stack.
5. When the user hits redo, the last item is selected from the future stack and passed to `UPDATED_DOCUMENT`.

Anyways, I think this is good for review and entry into master and we can iterate on it from there.

**Comment by rgbkrk** [comment]
Happy to review soon, looks like you'll need a rebase. It would be cool if you squash the merge commits as well.

**Comment by captainsafia** [comment]
OK! Rebased!

**Comment by rgbkrk** [comment]
We're all set here then? Exciting! I'll go ahead and pull the trigger!

**Pull request merged**
