### PR TITLE
Refactor: reducers minimize getIn

### PR DESCRIPTION
**Pull request by Shinigami92**
This improved some typeings

### CODE REVIEW

**Comment by Shinigami92** [comment]
What .-.
`notebook` is not defined everywhere?
But how did it work before?

**Comment by rgbkrk** [comment]
> notebook is not defined everywhere?
> But how did it work before?

`getIn` will return `undefined` if that path doesn't exist at any point in that array of paths.

**Comment by rgbkrk** [comment]
Is this all the reducer tests for document failing or just certain ones that aren't fully set up properly?

**Comment by Shinigami92** [comment]
Ok, then I will put this branch in a trash can

**Comment by rgbkrk** [comment]
Might be worth just doing one of these and seeing if the tests pass locally (or more until you find one failing), in case it's the test that needs updating.

**Comment by Shinigami92** [comment]
I do not know if it's worth it
We should maybe typedef the lhs instead

**Pull request closed without merging**
