### PR TITLE
chore(Cell): Add Flow types to Cell, edited .flowconfig to reduce errors

### PR DESCRIPTION
**Pull request by peggyrayzis**
Happy Hacktoberfest!

As requested, I added Flow typing for the props of the Cell component. When I ran Flow, I noticed a lot of node_module errors and adjusted the flowconfig to suppress those errors. Please let me know if you would also like me to Flow type the rest of the file. There are still a lot of errors when you run Flow because nothing else is typed. Also, I created an actual type for Props instead of defining them inline like this PR: 
https://github.com/nteract/nteract/blob/master/src/notebook/components/status-bar.js#L15-L20

I have no problem reverting to inline, just wasn't sure what you preferred.

Here's a list of the remaining Flow errors, I'd be happy to clean them up for you! :)

``` bash

src/notebook/components/cell/cell-creator-buttons.js:21
 21:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:22
 22:     this.createCodeCell = this.createCell.bind(this, 'code');
              ^^^^^^^^^^^^^^ property `createCodeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:23
 23:     this.createTextCell = this.createCell.bind(this, 'markdown');
              ^^^^^^^^^^^^^^ property `createTextCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:24
 24:     this.createCell = this.createCell.bind(this);
              ^^^^^^^^^^ property `createCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:25
 25:     this.mergeCell = this.mergeCell.bind(this);
              ^^^^^^^^^ property `mergeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:37
 37:   createCell(type) {
                  ^^^^ parameter `type`. Missing annotation

src/notebook/components/cell/cell-creator-buttons.js:61
 61:         <button onClick={this.createTextCell} title="create text cell" className="add-text-cell">
                                   ^^^^^^^^^^^^^^ property `createTextCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:64
 64:         <button onClick={this.createCodeCell} title="create code cell" className="add-code-cell">
                                   ^^^^^^^^^^^^^^ property `createCodeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator.js:12
 12:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:13
 13:     this.setHoverElement = this.setHoverElement.bind(this);
              ^^^^^^^^^^^^^^^ property `setHoverElement`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:14
 14:     this.updateVisibility = this.updateVisibility.bind(this);
              ^^^^^^^^^^^^^^^^ property `updateVisibility`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:33
 33:   setHoverElement(el) {
                       ^^ parameter `el`. Missing annotation

src/notebook/components/cell/cell-creator.js:34
 34:     this.hoverElement = el;
              ^^^^^^^^^^^^ property `hoverElement`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:42
 42:   updateVisibility(mouseEvent) {
                        ^^^^^^^^^^ parameter `mouseEvent`. Missing annotation

src/notebook/components/cell/cell-creator.js:46
 46:       const regionRect = this.hoverElement.getBoundingClientRect();
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `getBoundingClientRect`. Method cannot be called on
 46:       const regionRect = this.hoverElement.getBoundingClientRect();
                              ^^^^^^^^^^^^^^^^^ property `hoverElement` of unknown type

src/notebook/components/cell/cell.js:38
 38:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
 30: export class Cell extends React.Component {
                  ^^^^ Cell

src/notebook/components/cell/cell.js:39
 39:     this.selectCell = this.selectCell.bind(this);
              ^^^^^^^^^^ property `selectCell`. Property not found in
 30: export class Cell extends React.Component {
                  ^^^^ Cell

src/notebook/components/cell/cell.js:40
 40:     this.focusAboveCell = this.focusAboveCell.bind(this);
              ^^^^^^^^^^^^^^ property `focusAboveCell`. Property not found in
 30: export class Cell extends React.Component {
                  ^^^^ Cell

src/notebook/components/cell/cell.js:41
 41:     this.focusBelowCell = this.focusBelowCell.bind(this);
              ^^^^^^^^^^^^^^ property `focusBelowCell`. Property not found in
 30: export class Cell extends React.Component {
                  ^^^^ Cell

src/notebook/components/cell/cell.js:42
 42:     this.setCellHoverState = this.setCellHoverState.bind(this);
              ^^^^^^^^^^^^^^^^^ property `setCellHoverState`. Property not found in
 30: export class Cell extends React.Component {
                  ^^^^ Cell

src/notebook/components/cell/inputs.js:6
  6:   constructor(props) {
                   ^^^^^ parameter `props`. Missing annotation

src/notebook/components/cell/inputs.js:8
  8:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
  5: export default class Inputs extends React.Component {
                          ^^^^^^ Inputs

r 8b5e2a6 Fixed flowconfig to avoid node_modules related errors
fix(flowconfig): Fixed flowconfig to avoid node_modules related errors

Found 22 errors
```

### CODE REVIEW

**Comment by rgbkrk** [comment]
Welcome!

> Here's a list of the remaining Flow errors, I'd be happy to clean them up for you! :)

Yes please!

**Comment by rgbkrk** [comment]
We're new to flow, having only started to adopt it this week. I noticed this earlier today and asked @alexandercbooth to see if he could tackle the bits that weren't covered. It's ok with me if you both end up tackling getting that cleaned up.

We could enable flow on Travis as well so we'll notice these in advance, which is open as an issue here: https://github.com/nteract/nteract/issues/896

**Comment by rgbkrk** [comment]
There's one tiny linting change (which annoyingly happens for each `flow` PR), related to where props are in the ES6 class. We'll either have to move the props or adapt our linting config.

**Review by rgbkrk — APPROVED** [review]

**Comment by peggyrayzis** [comment]
Hi! I edited the linter config to support defining type-annotations at the top of the component, which is common practice among other projects I've worked on w/ Flow typing: 
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md

I also edited the previously merged components so that the type-annotations are defined at the top & consistent w/ the style in my previous commits. :) I'll work on typing the rest throughout the week!

**Comment by rgbkrk** [comment]
Wow, you are incredible. _Thank you_.

**Comment by rgbkrk** [comment]
Welcome to the nteract party! :tada:

**Comment by alexandercbooth** [comment]
Thanks @peggyrayzis! 
Happy to have help from someone with more flow experience.

**Pull request merged**
