### PR TITLE
feat(vega): implement transform for vega

### PR DESCRIPTION
**Pull request by rgbkrk**
This enables the ability to use vega and vega-lite, either through Altair, ipyvega, or generally with the right vega(-lite) mimetype (`application/vnd.vega+json` and `application/vnd.vegalite+json`).

screen shot 2016-10-30 at 10 25 25 pm

Items to follow up with:

* [x] Handling height and width
* [x] Dealing with the external links (shown above)
* [x] Tests!

/cc @ellisonbg

### CODE REVIEW

**Comment by rgbkrk** [comment]
screen shot 2016-10-31 at 4 54 13 pm

**Comment by rgbkrk** [comment]
screen shot 2016-10-31 at 10 33 39 pm

Altair's declarative syntax makes this all just _too easy_. ❤️ it.

**Comment by rgbkrk** [comment]
Note: until ipyvega exports the vega mimetypes used above, folks have to wrap altair objects with the little `vegify` function I wrote:

``` python
import IPython.display
def vegify(spec):
    IPython.display.display({
        'application/vnd.vegalite+json': spec.to_dict()
    }, raw=True)

v = vegify
```

**Comment by captainsafia** [comment]
Looks good!

**Comment by lgeiger** [comment]
Webpack throws the following error on my machine:

```
ERROR in ./app/~/vega-scenegraph/src/util/canvas.js
Module not found: Error: Cannot resolve module 'canvas' in /Users/lukasgeiger/code/nteract/app/node_modules/vega-scenegraph/src/util
 @ ./app/~/vega-scenegraph/src/util/canvas.js 11:17-34

ERROR in ./app/~/vega-scenegraph/src/util/ImageLoader.js
Module not found: Error: Cannot resolve module 'canvas' in /Users/lukasgeiger/code/nteract/app/node_modules/vega-scenegraph/src/util
 @ ./app/~/vega-scenegraph/src/util/ImageLoader.js 51:19-36
```

**Comment by rgbkrk** [comment]
Does it finish building for you though? I can add an escape for that, as we have native browser canvas as soon as it's in the Browser Window.

**Comment by lgeiger** [comment]
Yes it builds fine

**Pull request merged**
