### PR TITLE
Bump enchannel-zmq-backend

### PR DESCRIPTION
**Pull request by captainsafia**
Now with working zmq-prebuilt!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Woo!

**Comment by rgbkrk** [comment]
Time to make another nteract alpha release!

**Comment by captainsafia** [comment]
OMG SO HYPED.

**Comment by rgbkrk** [comment]
I'll make a signed release later tonight or tomorrow morning. Thanks much @captainsafia!

**Comment by jdfreder** [comment]
Thanks @captainsafia , this is excellent!

**Pull request merged**
