### PR TITLE
chore: test and update for node8 (keep yarn)

### PR DESCRIPTION
**Pull request by rgbkrk**
This is an alternative to #1728.

If it's good, I'll rebase this down to the one commit it should be since I did it on top of #1728.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Everything passes here too!

**Comment by rgbkrk** [comment]
Oh wait, I have some more to make this use all the `yarn` steps.

**Comment by rgbkrk** [comment]
I'll go ahead and merge this since it keeps thing as they were with `yarn` while allowing npm 5 to work.

**Review by lgeiger — COMMENTED** [review]
Thanks for bringing us up-to-date!

**Pull request merged**
