### PR TITLE
Second take on cell creator toolbar,

### PR DESCRIPTION
**Pull request by jdfreder**
- cell creator now exists at document level
- use pixel hover boundaries instead of percentage
- show creator when no cells exist

### CODE REVIEW

**Comment by jdfreder** [comment]
:tada:

**Comment by jdfreder** [comment]
Licecap doesn't want to record my cursor today, but here's a cap anyways:
spawner

**Comment by betatim** [comment]
I just came here to tell you how cool this is!

**Comment by jdfreder** [comment]
Thanks @betatim !

**Pull request merged**
