### PR TITLE
Switch to commonJS import of rxjs 5

### PR DESCRIPTION
**Pull request by rgbkrk**
Getting us partway to #444 by installing `rxjs@5.0.0-beta.6` and `enchannel-zmq-backend@2.0.0`, as well as switching imports to use `require('rxjs/Rx')`.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Really unsure what's going on with Travis. I have a nice clean install working locally just fine. Travis keeps bombing out trying to `require('rxjs/rx')`. There is a warning about not being able to build native modules (even though `zmq` appears to be built just fine).

¯\_(ツ)_/¯

**Comment by jdfreder** [comment]
I wonder if something's up with the cache...

**Comment by rgbkrk** [comment]
The part that is worrying me right now is this:

```
> execSync@1.0.2 install /home/travis/build/nteract/nteract/node_modules/execSync
> node install.js
[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
> zmq@2.15.1 install /home/travis/build/nteract/nteract/node_modules/zmq
> node-gyp rebuild
```

**Comment by jdfreder** [comment]
Looks like the problem is in enchannel zmq.  Specifically imports of `rxjs/rx` instead of `rxjs/Rx`.

**Comment by rgbkrk** [comment]
Since I'm on a Mac, the _one_ place where I used `rxjs/rx` was fine for me everywhere (because of case insensitivity). For some reason everywhere else I used `rxjs/Rx`. Thanks for diagnosing @jdfreder, followed by merging the enchannel-zmq-backend patch. 😅

**Comment by jdfreder** [comment]
:+1:

**Pull request merged**
