### PR TITLE
Live rendered markdown

### PR DESCRIPTION
**Pull request by jdetle**
Check it!

markdown

The live-ness of it has its perks and its downside, we should probably make this a toggleable feature?

### CODE REVIEW

**Comment by jdetle** [comment]
markdown_2

^ what happens upon executing the cell.

**Comment by jdetle** [comment]
togglability

**Comment by rgbkrk** [comment]
Awesome!

As for the latex rendering flicker, we can probably make that a lot cleaner by actually coordinating with MathJax. Our LaTeX render is a bit greedy right now.

**Comment by rgbkrk** [comment]
I'm not a fan of using the input/output semantics here, hiding the "input" on markdown seems weird - it _is_ the text after all. We default to render when not in render mode after.

**Comment by jdetle** [comment]
nbd I just increased coverage by 2% 0.o

**Comment by rgbkrk** [comment]
> nbd I just increased coverage by 2% 0.o

and then... not?

**Comment by jdetle** [comment]
I rebased?

**Comment by rgbkrk** [comment]
Codecov so silly.

You have a wonderful day too John!

**Pull request merged**
