### PR TITLE
Problem: we don't have simple ways of creating messages

### PR DESCRIPTION
**Pull request by rgbkrk**
Solution: Write a simple `createMessage` and `createExecuteRequest`

Note: this treats the session id as a module level closure. I honestly don't know if we need to track on sessions.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Usage:

```
import { createExecuteRequest } from './api/messaging';

const msg = createExecuteRequest('print(3)');
shell.subscribe(console.log);
iopub.subscribe(console.log);
shell.next(msg);
```

**Comment by jdfreder** [comment]
Lol - `Pull requests that have a failing status can’t be merged from a phone.`

**Comment by rgbkrk** [comment]
Tests pass locally, `nvm` is stalling out again.

**Comment by rgbkrk** [comment]
Of note: something is munging up the channels/subjects, resulting in non-fun Rx errors:

image

**Pull request merged**
