### PR TITLE
[play] expand display-area by default

### PR DESCRIPTION
**Pull request by rgbkrk**
Without this PR:

screen shot 2017-12-02 at 5 43 46 pm

With this PR:

screen shot 2017-12-02 at 5 43 37 pm

/cc @betatim @yuvipanda

### CODE REVIEW

**Comment by yuvipanda** [comment]
am testing this locally now

**Comment by yuvipanda** [comment]
So the output area expands and I can scroll down, but the code are a does not seem to expand. This causes a color difference on the left side as you scroll down. Is that intentional?

**Comment by yuvipanda** [comment]
so it looks like https://screenshots.firefox.com/Dpnh9FSK4KjWvbfU/localhost (after pressing 'enter' to trigger scrollbar on left). Am ok to merge as is though, since it's clearly an improvement over current setup.

**Comment by rgbkrk** [comment]
> This causes a color difference on the left side as you scroll down. Is that intentional?

Nope. Definitely need to make that full height with both. Not sure how to fix that at the moment. 🤔

**Comment by yuvipanda** [comment]
Do you wanna do that in a separate PR?

**Comment by rgbkrk** [comment]
Yeah it’s ok to call this an iterative improvement and create an issue for the color on the left down below.

**Comment by yuvipanda** [comment]
w00t, my first merge!

**Pull request merged**
