### PR TITLE
Fix perf issue in KeyboardShortcuts decorator

### LINKED ISSUE #4885: 0.21.0 Desktop | Very slow editing markdown and code cell blocks
**Application or Package Used**
nteract desktop 0.21.0 | macOS 10.15.2
 - upgraded from nteract desktop 0.15.0 to 0.21.0 using dmg file release

**Describe the bug**
Editing cells is very slow and sluggish.

For example: When I type in '3333333' just fast, it takes about four seconds to render it.

**Expected behavior**

- Rendering while editing should be fluid.

**Desktop (please complete the following information):**

macOS 10.15.2 & macOS 10.15.3

### PR DESCRIPTION
**Pull request by captainsafia**
Fixes issue where KeyboardShortcuts component re-renders on every keypress.

### CODE REVIEW

**Comment by eimfach** [comment]
Hi @captainsafia , I just created a build with your latest commit `63d764871`. I am afraid the issue still persists on my side... It is still as sluggish as before on my 59KB Python Notebook ... If I open a new Notebook everything types in fine and fluid, but I guess this has to do with that there is no content rendered at all ...

**Comment by eimfach** [comment]
Also I noticed something weird: Two (I guess non related tests) fail:
- KeyboardShortcuts › executes focused cell if the correct key combination is pressed
```
    Expected number of calls: >= 1
    Received number of calls:    0
```
- KeyboardShortcuts › should not focus next cell's editor if it is markdown
```
    Expected number of calls: >= 1
    Received number of calls:    0
```

**Comment by eimfach** [comment]
Did I overlook something maybe ?

**Comment by captainsafia** [comment]
@eimfach The test failure is a transient issue that happens locally. The test work in the build and on some dev's machines so it hasn't been too serious thus far.

As for the issue that you are running into, I'm not sure what it is now considering you are still experiencing it on this branch. This PR resolves an issue where the `KeyboardShortcuts` decorator was being aggressively re-rendered on every keypress.

Do you mind sharing the notebook you are using?

**Comment by eimfach** [comment]
@captainsafia Hey, so the notebook itself doesn't matter. It is the same issue with every notebook I have including the sample Notebooks from nteract itself. Are there some build artifacts for macOS from this repository somewhere at circleci or related (just so I can verify) ?

**Comment by captainsafia** [comment]
Unfortunately, the build for the desktop app is too memory intensive and the artifacts a little too large for our CircleCI tier.

Generating them through the `yarn dist` command should showcase the desired result.

Some follow-up questions:
- What are the specs of the machine you are on?
- Can you run the Chrome profiler while editing a notebook in the desktop app?

Here's information on how to profile in the desktop app in case you don't know:

1. Open the nteract desktop app (try a version built using `yarn dist` from this PR).
2. Navigate to View > Toggle Developer Tools in the menu.
3. Navigate to the "Performance" tab in dev tools.
4. Select "Memory" under the Performance tab.
5. Hit the record button on the left and do some typing then pause.
6. Once you are done, hit the download icon and upload the exported JSON and share a link to it here.

Let me know if you have follow-up questions.

**Comment by eimfach** [comment]
[nteract-Profile-20200130T224148.json.zip](https://github.com/nteract/nteract/files/4136380/nteract-Profile-20200130T224148.json.zip)

**Comment by eimfach** [comment]
The specs are : 
MacOS 10.15.3
2,9 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3

**Comment by rgbkrk** [comment]
I'm going to go ahead with merging this one and we'll keep iterating on this.

**Pull request merged**
