### PR TITLE
Problem: issue #887 addressed for cell creator component

### PR DESCRIPTION
**Pull request by alexandercbooth**
Solution: Added flow type to cell creator component.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome, thanks. In terms of the commit prefix, this should be `chore` instead of feature since it's not adding a new feature.

**Comment by rgbkrk** [comment]
There is exactly one linting "issue" to be adapted here:

```
  8:3  error  props should be placed after setHoverElement  react/sort-comp
```

Which just means you have to move the props further down in the component (this comes from our AirBnB-styled linting config.

**Comment by rgbkrk** [comment]
As for updating the commit message, if you're comfortable with rebasing feel free. Otherwise, let me know and I'll fix it up while I merge.

**Comment by alexandercbooth** [comment]
Thanks for the feedback, @rgbkrk! 

I have tried to make the changes you suggested. Please forgive me if I made a mistake anywhere -- I had never rebased before. 

Let me know if there is anything further I can do. 

Thanks!

**Comment by rgbkrk** [comment]
Ah, yeah. The rebase didn't go very well. I can get it fixed up for you.

Here's a [decent tutorial on likely rebase ways](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history). In particular, you'd want to do an interactive rebase against master.

**Comment by rgbkrk** [comment]
You did the reword part _perfectly_. What I ran to fix it up (while on your branch):

```
$ git rebase -i origin/master
Successfully rebased and updated refs/heads/add-flow-to-cell-creator.
$ git push -f
```

**Comment by alexandercbooth** [comment]
Sorry about that, will do better in the future. Thanks for the reference, I definitely needed a better understanding on rebasing. 

Thanks for understanding and fixing it up for me!

**Comment by rgbkrk** [comment]
Awesome, thank you. 

Again, welcome to the nteract party! 🎉

**Comment by alexandercbooth** [comment]
Thanks so much, excited to help out!

What would you recommend for adding flow to other components, one at a time (with PR for each) or add it to multiple components and submit one PR? I just want to make sure I follow best practices.

**Comment by jdetle** [comment]
I can't put words in Kyle's mouth but in my mind the best PR is the one
that keeps you coming back :)

**Comment by rgbkrk** [comment]
I'd err on the side of making a PR for each. If you end up doing several in one PR, that's ok too.

**Comment by alexandercbooth** [comment]
OK, that makes sense. Thanks so much!

**Pull request merged**
