### PR TITLE
[WIP] Create a builtin victory renderer

### PR DESCRIPTION
**Pull request by rgbkrk**
This lets a user plot data from e.g. Python and render it with a [Victory chart component](https://github.com/FormidableLabs/victory).

screen shot 2016-08-30 at 11 09 49 am

Mostly a prototype for handling a custom mimetype. Not intended to be merged anytime soon.

/cc @captainsafia @kenwheeler

### CODE REVIEW

**Comment by rgbkrk** [comment]
Might as well cc @mathisonian. 💃

**Comment by rgbkrk** [comment]
~~Ok yuck, loading `victory.ipynb` is kind of weird because our field is pure JSON. Checking that out so y'all can play.~~ Fixed

**Comment by rgbkrk** [comment]
screen shot 2016-08-30 at 11 19 45 am

Update: fixed!

**Comment by rgbkrk** [comment]
I'll fix that in commutable so that JSON can be included as is. That's what the notebook format spec says anyways. https://nbformat.readthedocs.io/en/latest/format_description.html#display-data

Need to fix cleanMultiline.

**Comment by captainsafia** [comment]
> Need to fix cleanMultiline.

Yeah I think there was an issue open for this on commutable for a while now.

Playing with this now.

**Comment by rgbkrk** [comment]
Fixed the commutable library up. This is good to play with and run locally with either:

```
npm run start victory.ipynb
```

or with the redux logger enabled:

```
NODE_ENV=development npm run start victory.ipynb
```

**Comment by rgbkrk** [comment]
screen shot 2016-08-30 at 11 54 35 am

**Comment by rgbkrk** [comment]
Now with props passthrough!

screen shot 2016-08-30 at 12 36 27 pm

**Comment by rgbkrk** [comment]
screen shot 2016-08-30 at 1 36 14 pm

**Comment by rgbkrk** [comment]
My hokey little `victorize` function could really do with auto-determining label names and other bits from data frames for plotting with Victory. Totally out of scope for this PR, more of a mantle to be taken up by the Python library that chooses to implement this.

**Comment by rgbkrk** [comment]
Since we really need a spec for both sides here and it was fairly ad-hoc from me I'll go ahead and close this. Still awesome. Cool if someone wants to pick the mantle back up.

**Pull request closed without merging**
