### PR TITLE
feature(sourcemaps): Sourcemaps!!!

### PR DESCRIPTION
**Pull request by jdetle**
This seems to work swimmingly!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Sweet!

IIRC, they were taken out because `npm run build:renderer:watch` would run out of memory. That was webpack 1 though. On to the new future. Thanks @jdetle!

**Review by rgbkrk — APPROVED** [review]

**Review by lgeiger — APPROVED** [review]

**Comment by jdetle** [comment]
Don't merge this yet, I need to double check things.

**Comment by jdetle** [comment]
screen shot 2017-05-22 at 3 00 47 pm

**Comment by jdetle** [comment]
@rgbkrk @lgeiger, works great. Not hogging much memory with `npm run build:renderer:watch` as far as I can tell.

**Comment by rgbkrk** [comment]
You'll have to trigger successive builds to see the memory leak's effect.

Since all seems well, let's go with it!

**Pull request merged**
