### PR TITLE
Call finalize on Vega embed result or view upon unmounting

### PR DESCRIPTION
**Pull request by domoritz**
Follow up for https://github.com/nteract/nteract/pull/4726.

### CODE REVIEW

**Comment by captainsafia** [comment]
@domoritz Can you add me as a collaborator on your fork so I can submit a commit to your branch with an updated yarn.lock?

**Comment by domoritz** [comment]
I added you.

**Comment by captainsafia** [comment]
@domoritz Thanks. I've updated the `yarn.lock` file.

**Comment by domoritz** [comment]
Thank you @captainsafia.

Looks like we also need Vega 5.8.1 since Vega-Embed uses `vega.writeConfig`. I pushed the updates but still can't update the yarn.lock file.

**Comment by captainsafia** [comment]
@domoritz Updated again.

**Comment by domoritz** [comment]
Let's see whether tests are passing now. @CrystallineCat sais that there are problems with Typescript since nteract is not using the latest version of TypeScript.

**Comment by domoritz** [comment]
As expected, tests are failing because of an old TypeScript version. 

Screen Shot 2019-12-04 at 18 12 05

Can you update TS or is there a reason not to?

**Comment by captainsafia** [comment]
There's no technical limitation, AFAIK, for not upgrading to TS. Moreso about finding the time/resources to do so.

I'm not sure if the upgrade will be relatively painless or if there will be an extensive set of bugs for us to chase.

Can you open an issue about the minimum version of TS required for this vega upgrade?

**Comment by domoritz** [comment]
I should try to build nteract so I can actually test different versions ;-) Stay tuned.

**Comment by captainsafia** [comment]
@domoritz Sounds good! Feel free to ping on slack.nteract.io with any questions.

**Comment by domoritz** [comment]
I can build nteract by downgrading to node 10. I also managed to upgrade to TypeScript 3.7 without too much trouble.

**Comment by domoritz** [comment]
Oh, I see @CrystallineCat just sent a pull request to do the same in https://github.com/nteract/nteract/pull/4751. I will wait for that to be merged.

**Comment by rgbkrk** [comment]
Merged the TS update PR, go ahead with the rebase now.

**Comment by domoritz** [comment]
The fix is contained in https://github.com/nteract/nteract/pull/4757

**Pull request closed without merging**
