### PR TITLE
chore(PULL_REQUEST_TEMPLATE): clarity for first timers.

### PR DESCRIPTION
**Pull request by vperezma**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Hey there! Thanks for making the PR. Did you mean to close it?

**Comment by rgbkrk** [comment]
Ah I see, you've made a new PR. Thanks!

**Comment by vperezma** [comment]
Sorry, I forgot to add a description to it.

**Comment by rgbkrk** [comment]
Ah, cool. You can also click the pencil icon in the upper right of each message/PR/issue to edit the description next time.

**Pull request closed without merging**
