### PR TITLE
Problem: issue #887 addressed for MarkdownCell component

### PR DESCRIPTION
**Pull request by alexandercbooth**
Solution: Added flow type to markdown-cell component

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome.

**Comment by rgbkrk** [comment]
When I run `flow` on master now I'm seeing a lot of reports from flow:

```
$ npm run flow

> nteract@0.0.13 flow /Users/kylek/code/src/github.com/nteract/nteract
> flow; test $? -eq 0 -o $? -eq 2

src/notebook/components/cell/cell-creator-buttons.js:21
 21:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:22
 22:     this.createCodeCell = this.createCell.bind(this, 'code');
              ^^^^^^^^^^^^^^ property `createCodeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:23
 23:     this.createTextCell = this.createCell.bind(this, 'markdown');
              ^^^^^^^^^^^^^^ property `createTextCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:24
 24:     this.createCell = this.createCell.bind(this);
              ^^^^^^^^^^ property `createCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:25
 25:     this.mergeCell = this.mergeCell.bind(this);
              ^^^^^^^^^ property `mergeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:37
 37:   createCell(type) {
                  ^^^^ parameter `type`. Missing annotation

src/notebook/components/cell/cell-creator-buttons.js:61
 61:         <button onClick={this.createTextCell} title="create text cell" className="add-text-cell">
                                   ^^^^^^^^^^^^^^ property `createTextCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator-buttons.js:64
 64:         <button onClick={this.createCodeCell} title="create code cell" className="add-code-cell">
                                   ^^^^^^^^^^^^^^ property `createCodeCell`. Property not found in
 14: export class CellCreatorButtons extends React.Component {
                  ^^^^^^^^^^^^^^^^^^ CellCreatorButtons

src/notebook/components/cell/cell-creator.js:12
 12:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:13
 13:     this.setHoverElement = this.setHoverElement.bind(this);
              ^^^^^^^^^^^^^^^ property `setHoverElement`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:14
 14:     this.updateVisibility = this.updateVisibility.bind(this);
              ^^^^^^^^^^^^^^^^ property `updateVisibility`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:33
 33:   setHoverElement(el) {
                       ^^ parameter `el`. Missing annotation

src/notebook/components/cell/cell-creator.js:34
 34:     this.hoverElement = el;
              ^^^^^^^^^^^^ property `hoverElement`. Property not found in
  7: export default class CellCreator extends React.Component {
                          ^^^^^^^^^^^ CellCreator

src/notebook/components/cell/cell-creator.js:42
 42:   updateVisibility(mouseEvent) {
                        ^^^^^^^^^^ parameter `mouseEvent`. Missing annotation

src/notebook/components/cell/cell-creator.js:46
 46:       const regionRect = this.hoverElement.getBoundingClientRect();
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `getBoundingClientRect`. Method cannot be called on
 46:       const regionRect = this.hoverElement.getBoundingClientRect();
                              ^^^^^^^^^^^^^^^^^ property `hoverElement` of unknown type

src/notebook/components/cell/inputs.js:6
  6:   constructor(props) {
                   ^^^^^ parameter `props`. Missing annotation

src/notebook/components/cell/inputs.js:8
  8:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
  5: export default class Inputs extends React.Component {
                          ^^^^^^ Inputs

src/notebook/components/cell/markdown-cell.js:24
 24:   constructor(props) {
                   ^^^^^ parameter `props`. Missing annotation

src/notebook/components/cell/markdown-cell.js:26
 26:     this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
              ^^^^^^^^^^^^^^^^^^^^^ property `shouldComponentUpdate`. Property not found in
 15: export default class MarkdownCell extends React.Component {
                          ^^^^^^^^^^^^ MarkdownCell

src/notebook/components/cell/markdown-cell.js:27
 27:     this.state = {
                      ^ object literal. This type is incompatible with
 15: export default class MarkdownCell extends React.Component {
                                               ^^^^^^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:32
 32:     this.openEditor = this.openEditor.bind(this);
              ^^^^^^^^^^ property `openEditor`. Property not found in
 15: export default class MarkdownCell extends React.Component {
                          ^^^^^^^^^^^^ MarkdownCell

src/notebook/components/cell/markdown-cell.js:33
 33:     this.editorKeyDown = this.editorKeyDown.bind(this);
              ^^^^^^^^^^^^^ property `editorKeyDown`. Property not found in
 15: export default class MarkdownCell extends React.Component {
                          ^^^^^^^^^^^^ MarkdownCell

src/notebook/components/cell/markdown-cell.js:34
 34:     this.renderedKeyDown = this.renderedKeyDown.bind(this);
              ^^^^^^^^^^^^^^^ property `renderedKeyDown`. Property not found in
 15: export default class MarkdownCell extends React.Component {
                          ^^^^^^^^^^^^ MarkdownCell

src/notebook/components/cell/markdown-cell.js:41
 41:   componentWillReceiveProps(nextProps) {
                                 ^^^^^^^^^ parameter `nextProps`. Missing annotation

src/notebook/components/cell/markdown-cell.js:42
 42:     this.setState({
         ^ call of method `setState`
 42:     this.setState({
                       ^ property `source` of object literal. Property cannot be assigned on possibly undefined value
 15: export default class MarkdownCell extends React.Component {
                                               ^^^^^^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:70
 70:   editorKeyDown(e) {
                     ^ parameter `e`. Missing annotation

src/notebook/components/cell/markdown-cell.js:74
 74:       this.setState({ view: true });
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 74:       this.setState({ view: true });
                         ^^^^^^^^^^^^^^ property `view` of object literal. Property cannot be assigned on possibly undefined value
 15: export default class MarkdownCell extends React.Component {
                                               ^^^^^^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:79
 79:     this.setState({ view: false });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 79:     this.setState({ view: false });
                       ^^^^^^^^^^^^^^^ property `view` of object literal. Property cannot be assigned on possibly undefined value
 15: export default class MarkdownCell extends React.Component {
                                               ^^^^^^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:85
 85:   renderedKeyDown(e) {
                       ^ parameter `e`. Missing annotation

src/notebook/components/cell/markdown-cell.js:89
 89:       this.setState({ view: true });
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 89:       this.setState({ view: true });
                         ^^^^^^^^^^^^^^ property `view` of object literal. Property cannot be assigned on possibly undefined value
 15: export default class MarkdownCell extends React.Component {
                                               ^^^^^^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:135
135:                input={this.state.source}
                                      ^^^^^^ property `source`. Property cannot be accessed on possibly undefined value
135:                input={this.state.source}
                           ^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?

src/notebook/components/cell/markdown-cell.js:144
144:                { mdRender(this.state.source) }
                                          ^^^^^^ property `source`. Property cannot be accessed on possibly undefined value
144:                { mdRender(this.state.source) }
                               ^^^^^^^^^^ undefined. Did you forget to declare type parameter `State` of property `Component`?


Found 32 errors
```

**Comment by rgbkrk** [comment]
Can you tackle some of these before adding more typing to props?

**Comment by alexandercbooth** [comment]
Sure, happy to. Thanks!

**Pull request merged**
