### PR TITLE
build a minimal server for deployment using ncc

### PR DESCRIPTION
**Pull request by rgbkrk**
This packages up the `kernel-relay` as a single\*  webpacked file for ease of deployment across clusters, by way of [`ncc`](https://github.com/zeit/ncc#readme).

What I said with "single" is a bit of a lie because we still have our zeromq native dependency and this also emits typescript bindings. Pretty tidy though.

```
$ tree -h lib
lib
├── [  96]  build
│   └── [  96]  Release
│       └── [1.1M]  zmq.node
├── [  11]  index.d.ts
├── [2.8M]  index.js
├── [6.7M]  index.js.map
└── [ 263]  server.d.ts
```

Note: we don't _have_ to include the sourcemap. It seemed like a wise idea while we're still building on top of our initial prototype though.

### CODE REVIEW

**Review by willingc — APPROVED** [review]
LGTM.

**Review by stormpython — APPROVED** [review]
LGTM!

**Comment by stormpython** [comment]
Need to resolve conflicts with these changes before it can be merged.

**Comment by rgbkrk** [comment]
Rebased! Now we wait on CI.

**Comment by willingc** [comment]
Ding. Ding. Ding. CI is done.

**Pull request merged**
