### PR TITLE
adapt styled-blueprintjsx to styled-components

### PR DESCRIPTION
**Pull request by rgbkrk**
Packages up blueprint styles as a styled-components global style to subvert the need for a CSS loader.

```jsx
import { BlueprintCSS } from "@nteract/styled-blueprintjsx

<React.Fragment>
  <SuperCoolComponent />
  <BlueprintCSS />
</React.Fragment>
```

Still to be done:

* [x] Change how this package is used in dependents.

### CODE REVIEW

**Comment by rgbkrk** [comment]
This may or may not cause conflict with #3874

**Comment by rgbkrk** [comment]
If this does cause conflict I'm happy to resolve the rebase on the dx -> ts branch

**Comment by rgbkrk** [comment]
Something to note for styled-components and jest -- If you see an error like this:

```
yarn run v1.12.3
$ jest --reporters=default --reporters=jest-junit -u blueprintjsx
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
        at HTMLStyleElementImpl._updateAStyleBlock (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
        at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
        at TextImpl.replaceData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
        at TextImpl.appendData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
        at Text.appendData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
```

Then you have one of these:

* A multi-line comment (that JSDOM can't handle), according to https://github.com/styled-components/styled-components/issues/1931
* Maybe something else (I'm still investigating)

**Comment by rgbkrk** [comment]
Whoa whoa whoa if the `/*` is the cause of problems, it's also getting injected by styled-components for globals:

```
yarn run v1.12.3
$ jest --reporters=default --reporters=jest-junit -u blueprintjsx
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
        at HTMLStyleElementImpl._updateAStyleBlock (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
        at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
        at TextImpl.replaceData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
        at TextImpl.appendData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
        at Text.appendData (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
        at Object.insertRules (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/styled-components/dist/styled-components.cjs.js:674:16)
        at StyleSheet.inject (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/styled-components/dist/styled-components.cjs.js:1105:11)
        at GlobalStyle.createStyles (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/styled-components/dist/styled-components.cjs.js:2292:16)
        at GlobalStyle.renderStyles (/Users/kylek/code/src/github.com/nteract/nteract-maint/node_modules/styled-components/dist/styled-components.cjs.js:2308:10)
    /* sc-component-id: sc-global-3928022545 */
    {.bp3-dark .bp3-file-input input:disabled + .bp3-file-upload-input,.bp3-dark;.bp3-dark .bp3-html-select select:hover,.bp3-dark .bp3-select select:hover,.bp3-dark .bp3-html-select select:active,.bp3-dark .bp3-select select:active,.bp3-dark .bp3-html-select select.bp3-active,.bp3-dark;.bp3-dark .bp3-html-select select:active,.bp3-dark .bp3-select select:active,.bp3-dark .bp3-html-select select.bp3-active,.bp3-dark;.bp3-dark .bp3-html-select select:disabled,.bp3-dark .bp3-select select:disabled,.bp3-dark .bp3-html-select select.bp3-disabled,.bp3-dark;.bp3-dark .bp3-html-select select:disabled.bp3-active,.bp3-dark .bp3-select select:disabled.bp3-active,.bp3-dark .bp3-html-select select.bp3-disabled.bp3-active,.bp3-dark;}
    /* sc-component-id: sc-global-3401609285 */
```

**Comment by captainsafia** [comment]
As you mentioned, @rgbkrk, the failure is related to the fact that JSDOM can't parse the stylesheet because of the multiline comments generated by styled-components. These comments are generated by styled-components to help with rehydration in server-side contexts.

The issue is ultimately a result of JSDOM's CSS parser having rather poor support for CSS syntax. There's a couple of issues related to this on their issue board.

I tried a couple of different things but ultimately settled on mocking out the styled-components API in our tests.

**Comment by rgbkrk** [comment]
Thanks for investigating and figuring out a workaround for now. One thing I think we should do is another test that applies the raw stylesheet to the DOM (pre-styled components modifying it) to make sure it is a valid stylesheet otherwise.

**Comment by rgbkrk** [comment]
For now though I'll merge and we can start using this.

**Pull request merged**
