### PR TITLE
fix github publish

### PR DESCRIPTION
**Pull request by jdetle**
Will get tests to pass, this is a start.

### CODE REVIEW

**Comment by rgbkrk** [comment]
The `data` key came from an update to `github`?

**Review by rgbkrk — APPROVED** [review]

**Comment by jdetle** [comment]
Yes: https://github.com/mikedeboer/node-github/commit/ceeefb2c478ca4302e1fe60dece10bc40075eaaf

**Comment by rgbkrk** [comment]
Perhaps we should pin this more tightly (only patch releases with `~`) since we don't touch this section of the code all that often. Then again, I guess it forces us to keep moving it forward.

**Comment by jdetle** [comment]
I wasn't aware of that as an option, lets do it.

**Pull request merged**
