### PR TITLE
[WIP] feat: prototype a table component + mimetype for tabular data

### PR DESCRIPTION
**Pull request by rgbkrk**
A transform for [JSON Table Schema](http://specs.frictionlessdata.io/json-table-schema/) + data (record oriented). The nteract side of https://github.com/pandas-dev/pandas/issues/14386. 

Takes an overall structure like:

```json
{
  "schema": {
    "fields": [
      {
        "type": "any",
        "name": "Date"
      },
      {
        "type": "number",
        "name": "Open"
      },
      {
        "type": "number",
        "name": "High"
      },
      {
        "type": "number",
        "name": "Low"
      },
      {
        "type": "number",
        "name": "Close"
      },
      {
        "type": "integer",
        "name": "Volume"
      },
      {
        "type": "number",
        "name": "Adj Close"
      }
    ]
  },
  "data": [
    {
      "Date": "2000-03-01",
      "Adj Close": 33.68,
      "Open": 89.62,
      "Low": 88.94,
      "Volume": 106889800,
      "High": 94.09,
      "Close": 90.81
    },
    {
      "Date": "2000-03-02",
      "Adj Close": 34.63,
      "Open": 91.81,
      "Low": 91.12,
      "Volume": 106932600,
      "High": 95.37,
      "Close": 93.37
    }
  ]
}
```

and creates a table.

screen shot 2016-12-12 at 5 29 22 pm

Definitely a prototype, only putting this up to promote discussion. We have enough information here to align columns according to types, format tables accordingly, etc.

We should be able to map from `schema, data` to a reasonable table after iterating on this.

### CODE REVIEW

**Comment by gnestor** [comment]
@rgbkrk I started work on this for jupyterlab and notebook: https://github.com/gnestor/jupyterlab_table/blob/labextension-build/component/index.js

I haven't fully adopted the JSON Table schema yet, I'm just rendering `data_frame.to_dict()` data.

Great to see that you're working the pandas side! I spoke to @ellisonbg about this earlier today!!

**Comment by rgbkrk** [comment]
Went ahead and created the table directly, mirrored the current structure style of the pandas HTML we're used to seeing. Check the source out 👀. Result:

screen shot 2016-12-13 at 2 42 19 pm

I haven't used the typing information yet, this only sets us up for later allowance of theming and utility across other languages - we've broken up the presentational components and the data.

## What's missing?

The indexes on the data frame. They're not captured with this current `data, schema` approach.

**Comment by gnestor** [comment]
@rgbkrk Nice! A couple things:

* Could you create a todo list in this issue so I can track what you've done and what you're working on? I'd like to help but I don't want to overlap.
* Why not use the `FixedDataTable` component?
* I updated the mimerender extensions today to provide their own display method, which would allow something like: 

```py
from jupyterlab_table import Table
Table(df)
```

See jupyterlab_plotly for a reference implementation: https://github.com/gnestor/jupyterlab_plotly#usage

I'd appreciate your feedback regarding this approach and I'd like to explore how our mimerender efforts can be better combined. For example, is it possible to register new transforms/mimetypes that are not bundled with nteract? If so, it would be nice if these mimerender extensions could also support nteract since they already support notebook and lab. I see some discussion at https://github.com/nteract/nteract/issues/670 and https://github.com/nteract/nteract/issues/481.

**Comment by rgbkrk** [comment]
> Could you create a todo list in this issue so I can track what you've done and what you're working on? I'd like to help but I don't want to overlap.

Sure. I'm not working on this in any serious sense, it's only up as a prototype for the pandas discussion (this doesn't have to be the end component, just enough to rely on the JSON spec and messaging).

> Why not use the FixedDataTable component?

My first commit and comment used the fixed data table component. It required a lot more configuration to get right as opposed to creating the table directly. Feel free to iterate on a component that uses this `{ schema, data }` spec to match pandas while using the FixedDataTable. I don't have the time to fuss too much with it.

> I updated the mimerender extensions today to provide their own display method, which would allow something like...

Cool! I'm glad you're making Python side versions for exploring. I tend to defer to either providing these methods directly in `IPython.display.*` utilities or in the core libraries. In the case of Plotly, it would be cool if you picked up https://github.com/plotly/plotly.py/pull/562 from where @chriddyp left off. I'd rather the support be built into the libraries being supported and used by users.

>  is it possible to register new transforms/mimetypes that are not bundled with nteract?

Not currently, continue the discussion in #670. An externally facing API is not something I want to support until we finish up higher priority issues. For now, bundling many renderers is the approach I've been going with. The API in this case is the mimetype and the expected payload. We rely on specs, not the implementation.

**Comment by rgbkrk** [comment]
Technicality:

`application/vnd.dataresource+json` is what we want and the structure is:

```js
{
  "resources": [
    {
      "schema": {...jsonTableSchemaHere},
      "data": [...rows],
    }
  ]
}
```

**Comment by rgbkrk** [comment]
Closing for now to reimplement later instead of rebase.

**Pull request closed without merging**
