### PR TITLE
fix(executeEpic): Dispatch error via Observable

### LINKED ISSUE #1094: switch !kernelConnected from notification to error dispatch
currently on no kernel connected the app sends a message via notificationSystem; need to change this to dispatch an error instead.  
in `executeCellEpic` function within `src/notebook/epics/execute.js`

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #1094.

### CODE REVIEW

**Comment by jdetle** [comment]
Yayyyyy regression tests are working!

**Comment by rgbkrk** [comment]
I think what John is saying is that he's really excited that all his work to test this (including a mock for the notification) is alive. Tests can now be greatly simplified because of this fix.

**Comment by captainsafia** [comment]
Yeah, I actually have to update the tests for this.

**Comment by jdetle** [comment]
Oh, yeah. Didn't mean to be rude, I just thought it was cool that the tests failed when behavior changed. Tone is hard to convey over the internet.

**Pull request closed without merging**
