### PR TITLE
chore(tests): Run package tests on CI

### PR DESCRIPTION
**Pull request by lgeiger**
This currently fails with:
```bash
FAIL  __tests__/text-spec.js
  > Text › renders plain text

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "<code><span>hey</span></code>"
    Received:
      "<code><span><!-- react-text: 3 -->hey<!-- /react-text --></span></code>"
```

### CODE REVIEW

**Comment by lgeiger** [comment]
I guess this error is caused by the `ansi-react` upgrade in #1427.

Any idea, how we should fix it?

**Comment by rgbkrk** [comment]
The output looks alright, we should change the test up.

**Comment by lgeiger** [comment]
👍 I fixed the failing test.

**Review by rgbkrk — APPROVED** [review]

**Comment by rgbkrk** [comment]
Thanks! I think we'll want a check that's more agnostic of inner structure in the future -- works for now though!

**Pull request merged**
