### PR TITLE
Revert "Constants Helper"

### PR DESCRIPTION
**Pull request by rgbkrk**
Reverts nteract/nteract#189

### CODE REVIEW

**Comment by rgbkrk** [comment]
Tests pass with this though the notebook doesn't boot properly (actions aren't registered).

**Comment by rgbkrk** [comment]
screenshot 2016-03-02 13 24 35

**Comment by jdfreder** [comment]
Hopefully we can get a fix for this

**Comment by rgbkrk** [comment]
Got one!

**Comment by jdfreder** [comment]
see https://github.com/nteract/nteract/pull/191

**Pull request merged**
