### PR TITLE
Create @nteract/selectors package

### PR DESCRIPTION
**Pull request by captainsafia**
Working on splitting up @nteract/core into smaller TypeScript packages.

### CODE REVIEW

**Comment by captainsafia** [comment]
OK! I finally got this working correctly. I published a new major version of the types package and brought it into the nteract/selectors package.

**Review by rgbkrk — APPROVED** [review]
Ah great I'm glad you got all the monorepo stuff together in this too

**Comment by rgbkrk** [comment]
How much do we want these todo comments as is created as issues?

**Comment by captainsafia** [comment]
@rgbkrk I don't want these to-dos to be created as issues. I don't know why the bot re-ran for every commit. Is it going to make as many issues as it made comments or?

**Comment by rgbkrk** [comment]
It won't make issues until the PR is merged, basically any for a left behind TODO.

@JasonEtco - there might be issues with todo bot creating and dealing with comments after an interactive rebase.

**Comment by JasonEtco** [comment]
Yikes, definitely looks bad. Sorry about that folks - would you mind opening an issue in https://github.com/JasonEtco/todo @rgbkrk?

**Comment by rgbkrk** [comment]
Done deal, posted https://github.com/JasonEtco/todo/issues/166. Thanks Jason!

**Pull request merged**
