### PR TITLE
feat(CSS): add styling for blockquotes in markdown cells

### LINKED ISSUE #810: Add styling to blockquotes in markdown cells
There's currently no styling to blockquotes, which makes it hard to tell if it's a paragraph vs. a quote.

screen shot 2016-09-20 at 3 26 28 pm

Tempted to make an overly styled version:

screen shot 2016-09-20 at 3 24 43 pm

CSS:

``` css

blockquote{
  padding: .75em .5em .75em 1em;
  background: white;
  border-left: 0.5em solid #DDD;
}

blockquote::before {
  display: block;
  height: 0;
  content: "“";
  margin-left: -.95em;
  font: italic 400%/1 Open Serif,Georgia,"Times New Roman", serif;
  color: #999;
}

/* for nested paragraphs in block quotes */
blockquote p {
  display: inline;
}
```

### PR DESCRIPTION
**Pull request by evanuk**
Resolves #810 by adding in @rgbkrk's css for the blockquote styling.  Modified it to use the `main-bg-color` and `primary-border` colours so it looks nice with the dark theme.  Let me know if I put the CSS in the right place!

### CODE REVIEW

**Review by jdetle — APPROVED** [review]
Nice catch on figuring out the css variables.

**Comment by jdetle** [comment]
Welcome to nteract @evanuk! Hope this is the first of many PRs!

**Comment by rgbkrk** [comment]
Excellent!

**Comment by rgbkrk** [comment]
Yup, this is great with the dark theme.

screen shot 2016-09-28 at 8 55 10 pm

**Comment by rgbkrk** [comment]
I'm somewhat thinking the bar line should be thinner next, but I could squabble about CSS all day and get nowhere. This is awesome!

**Pull request merged**
