### PR TITLE
When at end of doc, create new cell after run cell

### PR DESCRIPTION
**Pull request by rgbkrk**
This creates a new cell when at the end of the document.

### CODE REVIEW

**Comment by rgbkrk** [comment]
This _seems_ to come down to a case where on initial componentDidUpdate the `prevProps` are equivalent to the next props since it's the beginning. I need to look at lifecycle stuff here.

**Comment by rgbkrk** [comment]
The React lifecycle cheat sheet was super helpful here, since a new cell won't run through `componentDidUpdate`. For a brand new cell, we need to check for focused after mounted and focus if so.

**Comment by rgbkrk** [comment]
thank you react lifecycle chart

**Comment by rgbkrk** [comment]
I'd love to make it so that on initial notebook load we focus on the first cell. I can do that in a follow up PR.

**Comment by jdfreder** [comment]
Sweet, thanks for sharing the cheat sheet too!

**Pull request merged**
