### PR TITLE
chore(build): fix the Windows builds

### PR DESCRIPTION
**Pull request by rgbkrk**
Going backwards on `electron-builder`.

### CODE REVIEW

**Comment by rgbkrk** [comment]
~~Looks like that will do. One more patch to clean this up then.~~ Nevermind, good to go.

**Comment by lgeiger** [comment]
@rgbkrk The fix was released in `electron-builder` 7.21.0

I pushed a commit to update it

**Comment by rgbkrk** [comment]
Heh, last night (my time) there was only the 7.20.0 pre release. This looks ready to go now.

**Comment by lgeiger** [comment]
One hour later and it would have been there 😄 : https://github.com/electron-userland/electron-builder/releases

**Pull request merged**
