### PR TITLE
Use jest to report code coverage

### PR DESCRIPTION
**Pull request by lgeiger**
Since most of our test are now jest based, we should rely on it to report coverage.

We can fine-tune the coverage report later.

### CODE REVIEW

**Comment by rgbkrk** [comment]
niiiice

**Comment by rgbkrk** [comment]
```
 FAIL  packages/transforms/__tests__/text-spec.js
  ● Test suite failed to run
    TypeError: /home/travis/build/nteract/nteract/packages/transforms/__tests__/text-spec.js: Cannot read property 'forEach' of undefined
```

Interesting, I started seeing this one locally a little bit ago too.

**Comment by lgeiger** [comment]
Restarted the build, now we get another error. Time to clear the cache.

**Comment by lgeiger** [comment]
This is now good to go. The remaining CI failures will be fixed by #1956

**Comment by rgbkrk** [comment]
I'll entrust that these are good to go and get them merged in as is then.

**Pull request merged**
