### PR TITLE
chore(tests): Initial fs-observable testing

### PR DESCRIPTION
**Pull request by lgeiger**
Very rudimentary `fs-obselvable` testing.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Very. We'll definitely want to come back to these.

**Comment by rgbkrk** [comment]
We are so close to 90%!

**Comment by lgeiger** [comment]
> We are so close to 90%!

That was the motivation 😄

**Comment by rgbkrk** [comment]
~14 more PRs like this

**Comment by rgbkrk** [comment]
Though you'll be saddened to see the coverage drop if we start testing main. 😉

**Comment by jdetle** [comment]
If we don't then we're just living a lie anyways.

**Pull request merged**
