### PR TITLE
Bump Semiotic to 1.13

### PR DESCRIPTION
**Pull request by emeeks**
Up to semiotic@^1.13.1 to fix annotation bug and introduce facets

### CODE REVIEW

**Review by alexandercbooth — APPROVED** [review]
Thanks, @emeeks!

**Comment by alexandercbooth** [comment]
Whoops, didn't notice the requested review, sorry!

**Comment by emeeks** [comment]
That's okay just pro forma this version is stable and the lead developer of
the Semiotic project personally assured me of such.

**Comment by rgbkrk** [comment]
One of the semiotic contributors said this was a great release too!

**Pull request merged**
