### PR TITLE
chore: upgrade packages

### PR DESCRIPTION
**Pull request by rgbkrk**
Following up with the jupyter paths dependent upgrades, doing it directly.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thanks to @haraldschilly (in https://github.com/nteract/kernelspecs/issues/28), this fixes what was a bug for me that I thought was just an issue with the kernels I have.

**Comment by rgbkrk** [comment]
Looks like there are updates to be made for `sinon`:

```
  1) forceShutdownKernel fully cleans up the kernel and uses SIGKILL:
     TypeError: stub(obj, 'meth', fn) has been removed, see documentation
      at stub (node_modules\sinon\lib\sinon\stub.js:17:15)
      at Object.stub (node_modules\sinon\lib\sinon\collection.js:95:33)
      at Context.it (C:/projects/nteract/test/renderer/api/kernel-spec.js:53:32)
  2) cleanupKernel cleans out artifacts from the kernel object:
     TypeError: stub(obj, 'meth', fn) has been removed, see documentation
      at stub (node_modules\sinon\lib\sinon\stub.js:17:15)
      at Object.stub (node_modules\sinon\lib\sinon\collection.js:95:33)
      at Context.it (C:/projects/nteract/test/renderer/api/kernel-spec.js:82:32)
  3) setTitleFromAttributes sets the window title:
     TypeError: stub(obj, 'meth', fn) has been removed, see documentation
      at Object.stub (node_modules\sinon\lib\sinon\stub.js:17:15)
      at Context.it (C:/projects/nteract/test/renderer/native-window-spec.js:48:11)
  4) unlinkObservable it errors on unlink issue:
     TypeError: stub(obj, 'meth', fn) has been removed, see documentation
      at stub (node_modules\sinon\lib\sinon\stub.js:17:15)
      at Object.stub (node_modules\sinon\lib\sinon\collection.js:95:33)
      at Context.done (C:/projects/nteract/test/utils/fs-spec.js:25:32)
```

I'll get those done now.

**Comment by rgbkrk** [comment]
All set and ready.

**Review by lgeiger — APPROVED** [review]
🚀 📦 Thanks Kyle!

**Pull request merged**
