### PR TITLE
Adhere to kabob-style casing

### PR DESCRIPTION
**Pull request by captainsafia**
Kabob nation!

🍢 🍢 🍢

### CODE REVIEW

**Comment by rgbkrk** [comment]
That was totally me, wasn't it? Thanks @captainsafia!

**Comment by captainsafia** [comment]
> That was totally me, wasn't it? Thanks @captainsafia!

You need to seek forgiveness from our master, the Great Kabob.

**Comment by rgbkrk** [comment]
:bow: 🍢

**Comment by jdetle** [comment]
"And thou shalt arrange thine vegetables and meats in a linear, cubed medley, piercing with divine rod of balsa, and thou shalt knowest barbecue perfection"-  The Great Kebab

**Pull request merged**
