### PR TITLE
[WIP] New React & MathJax approach

### PR DESCRIPTION
**Pull request by rgbkrk**
I started this PR as a WIP before JupyterCon and am posting it here on GitHub so I hold myself accountable in finishing the work.

What I'm trying to do is move us towards the React 16 API for context & refs within the mathjax components. I'd love if MathJax wasn't a global with our loader component, but hey what can ya do when MathJax isn't available as a node package in an easy way?

### CODE REVIEW

**Comment by rgbkrk** [comment]
Note: I went after handling this one as a precursor to other `<Media />` helpers.

**Comment by lgeiger** [comment]
>  I'd love if MathJax wasn't a global with our loader component, but hey what can ya do when MathJax isn't available as a node package in an easy way?

Maybe MathJax version 3 beta is worth checking out, they even talk about server-side rendering: https://www.mathjax.org/MathJax-v3-beta/ https://github.com/mathjax/mathjax-v3

**Comment by rgbkrk** [comment]
Yeah! I was just playing with it and found it extra cumbersome to get through their current examples to know what we need. Perhaps that'll shape up. 😬  I'd love if you find a good way for us to balance our MathJax amongst web + electrons (Hydrogen & Desktop). 😄  You've certainly done it before.

**Comment by rgbkrk** [comment]
Closing for now since I'm doing this suite of changes as smaller changes. 😄

**Pull request closed without merging**
