### PR TITLE
feat(CSS): add 'nteract' theme

### LINKED ISSUE #848: Add a theme with the nteract color scheme
Currently we have two default themes, light and dark. As a project for new contributors, it would be nice to have a theme that incorporates the color scheme of nteract's logo into the background and/or cell aesthetic. Changing CSS, although not a programming heavy task, is a good way to get started making contributions after installing.

### PR DESCRIPTION
**Pull request by stephymiehle**
Add 'nteract' to theme selector
Create 'nteract' theme

This theme uses colors pulled from the nteract logo animation (and a few new ones for syntax highlighting). Cells in this theme are a bit different than they are in Light or Dark: unfocused cells are slightly dimmed to help you focus only on your active cell.

Visual preview:

Screenshot

Closes #848

### CODE REVIEW

**Comment by captainsafia** [comment]
Nice! Is there any way to add a background color to the status bar?

**Comment by stephymiehle** [comment]
@captainsafia Absolutely; this one just has a partially-transparent thing going on. I can switch that to a solid color!

_Edit:_ Solidified! Let me know if you'd like the commits squashed.

screen shot 2016-10-02 at 1 28 10 pm

**Comment by captainsafia** [comment]
Yay! Thanks! Definitely easier to read the status bar text now.

**Comment by rgbkrk** [comment]
This is really awesome.

It makes me think we should expose a class name for running cells (and a running notebook in general) -- when I saw the vertical stripes I figured they were for the running cells which would be pretty awesome.

**Comment by rgbkrk** [comment]
Whoa, I love this dimming! It gives the app an entirely different feel - the focus is on the "active" cell, which hones you in. I could see myself swapping between themes just for that - the current `light` and `dark` themes are great when I'm reading content as a whole, this new theme feels like the right environment for focusing on exactly the code segment I'm in.  _So neat_ to evoke new emotion out of the same environment.

**Comment by captainsafia** [comment]
By the way, @blindingstars – do you have a Twitter? And if so, are you comfortable with us giving you a shoutout for doing this on our Twitter account?

**Comment by rgbkrk** [comment]
There are so many aesthetics in this theme that I wish I had in the dark and light theme: the curved edges on the toolbars, the shadow on the cell toolbar, the color on the pushpin when pinned, the list styling, ...

**Comment by stephymiehle** [comment]
@captainsafia Have, but practically never use! Regardless, https://twitter.com/stephymiehle is me :)

@rgbkrk Thanks so much! Happy to know that someone else enjoys it as much as I do. I'm a big fan of the little details. Also, that idea about exposing a class for running cells is fantastic; I'd gladly move the stripes to that class!

**Comment by rgbkrk** [comment]
Added a CSS class for running cells in #900!

**Pull request merged**
