### PR TITLE
chore(ExampleNotebooks): resolve path in exampleNotebooksDirectory

### PR DESCRIPTION
**Pull request by alexandercbooth**
As per conversation in #1001, changed how the exampleNotebooksDirectory is defined.

### CODE REVIEW

**Comment by alexandercbooth** [comment]
Just realized there are some linting issues. Fixing up now, sorry!

**Comment by alexandercbooth** [comment]
OK, changed to this: 

``` jsx
const exampleNotebooksDirectory = path.resolve(path.join(__dirname, '..',
    '..', 'example-notebooks'));
```

Looks kind of ugly, but no screaming from the linter. Is this OK?

**Comment by rgbkrk** [comment]
'Tis fine. Style-wise, you may like this better:

``` js
const exampleNotebooksDirectory = path.resolve(
  path.join(__dirname, '..', '..', 'example-notebooks')
);
```

**Comment by alexandercbooth** [comment]
I like the looks of that much better, thanks!

**Pull request merged**
