### PR TITLE
Upgrade to electron@5.0.12

### PR DESCRIPTION
**Pull request by lgeiger**
This upgrades Electron to version 5 since zeromq.js@5.1.1 now includes correct prebuilt binaries for recent versions of Electron.
Electron changed the default for `nodeIntegration` so I explicitly enabled it for all windows except the splash screen.
Upgrade to Electron 7 is blocked by zeromq.js support (https://github.com/zeromq/zeromq.js/pull/348 might fix that).
Upgrading to Electron 6 broke the save before quit dialog.
I also upgraded `electron-builder` and tested that it builds correctly for mac. This was required by Electron 6, not sure if we really need the upgrade for v5, but I think it doesn't hurt.
Closes #4657

### CODE REVIEW

**Comment by rgbkrk** [comment]
Whoa thank you!

**Comment by rgbkrk** [comment]
The error on Circle CI looks unrelated, is this something erroring on master too?

```
packages/messaging/src/index.ts:237:3 - error TS2322: Type 'Observable<unknown>' is not assignable to type 'Observable<PayloadMessage>'.
  Type 'unknown' is not assignable to type 'PayloadMessage'.
    Type 'unknown' is not assignable to type 'AskExitPayloadMessage'.

237   source.pipe(
      ~~~~~~~~~~~~
238     ofMessageType("execute_reply"),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
241     mergeMap(p => from(p))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
242   );
    ~~~

packages/messaging/src/index.ts:241:24 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'ObservableInput<any>'.
  Type 'unknown' is not assignable to type 'Iterable<any>'.

241     mergeMap(p => from(p))
                           ~
```

Guess I'll take it for a spin!

**Comment by lgeiger** [comment]
> The error on Circle CI looks unrelated, is this something erroring on master too?

I think this is because I recreated `yarn.lock` let's see if I can revert this.

**Comment by rgbkrk** [comment]
Ok cool, I just verified master as well.

**Comment by lgeiger** [comment]
Reverted the `yarn.lock` changes in de443c6ee151f633a20bfd6ee7a2f84dcc8e4440 hopefully this will fix the typescript build

**Review by rgbkrk — APPROVED** [review]
Quite an upgrade, thank you!

**Pull request merged**
